erigontech/silkworm

- cmd/dbtool.cpp
- silkworm/db/chaindb.cpp
- silkworm/db/chaindb.hpp
Raw copy of data.
Eliminates all free pages.
> Implementation of copy flag for dbtool compact action

- cmd/CMakeLists.txt
- cmd/check_changes.cpp
- cmd/scan_txs.cpp
Implements code required to do initial analysis for #78
> 078 tx analysis

- silkworm/db/buffer.cpp
That should hep with performance on HDD
> Sort storage entries before writing to DB

- cmd/execute.cpp
- silkworm/db/access_layer.cpp
- silkworm/db/access_layer.hpp
- tg_api/silkworm_tg_api.cpp
- tg_api/silkworm_tg_api.h
Silkworm does not yet support https://github.com/ledgerwatch/turbo-geth/pull/1342
> Guard against DupSort change sets

- silkworm/db/access_layer.cpp
- silkworm/db/access_layer.hpp
- silkworm/db/access_layer_test.cpp
- silkworm/db/buffer.cpp
- silkworm/execution/execution_test.cpp
- silkworm/execution/processor_test.cpp
See https://codecov.io/gh/torquem-ch/silkworm/src/master/silkworm/db/access_layer.cpp
> Improve test coverage of DB access layer

- silkworm/db/access_layer.cpp
- silkworm/db/access_layer.hpp
- silkworm/db/access_layer_test.cpp
- silkworm/db/tables.hpp
- silkworm/db/util.cpp
- silkworm/db/util.hpp
- tg_api/silkworm_tg_api.cpp
Port TG DB migration https://github.com/ledgerwatch/turbo-geth/pull/1358
> Store transactions individually

- CMakeLists.txt
Reduce number of Windows headers processed
> Few definitions for Windows build

- .circleci/config.yml
- cmd/CMakeLists.txt
> Run core tests with Wasm

- db/silkworm/db/chaindb.hpp
See https://github.com/ledgerwatch/turbo-geth/pull/1433/files
> Let transaction commit do fsync

- CMakeLists.txt
- cmd/consensus.cpp
- core/silkworm/execution/analysis_cache.cpp
- core/silkworm/execution/evm.cpp
- core/silkworm/execution/state_pool.cpp
- core/silkworm/state/delta.cpp
- core/silkworm/state/delta.hpp
- core/silkworm/state/intra_block_state.cpp
- core/silkworm/state/intra_block_state.hpp
(since IntraBlockState is supposed to be used inside a single block, not across blocks).
Also fix a corner case by introducing `StorageCreateDelta`.
> Use StateBuffer instead of IntraBlockState for consensus tests

- README.md
- cmd/consensus.cpp
- core/silkworm/execution/execution.hpp
- core/silkworm/state/memory_buffer.cpp
- core/silkworm/state/memory_buffer.hpp
- wasm/silkworm_wasm_api.cpp
- wasm/silkworm_wasm_api.hpp
> Support postStateHash consensus tests

- db/silkworm/etl/collector.cpp
Amend wrong std::max -> std::min
> Update collector.cpp - quick patch

- cmd/consensus.cpp
- core/silkworm/chain/config.hpp
- core/silkworm/chain/validity.cpp
- core/silkworm/execution/evm.cpp
- core/silkworm/execution/processor.cpp
- core/silkworm/state/intra_block_state.cpp
- core/silkworm/state/intra_block_state.hpp
- core/silkworm/state/memory_buffer.cpp
- core/silkworm/state/memory_buffer.hpp
- wasm/silkworm_wasm_api.cpp
- wasm/silkworm_wasm_api.hpp
Also fix GasLimitHigherThan2p63m1 (see [EIP-1985](https://eips.ethereum.org/EIPS/eip-1985)).
> Handle RIPEMD deletion anomaly closer to how geth handles it

- cmd/consensus.cpp
- core/silkworm/chain/validity.cpp
- core/silkworm/chain/validity.hpp
- core/silkworm/execution/evm.cpp
- core/silkworm/execution/execution.hpp
- core/silkworm/state/buffer.hpp
- core/silkworm/state/memory_buffer.cpp
- core/silkworm/state/memory_buffer.hpp
- db/silkworm/db/access_layer.cpp
- db/silkworm/db/access_layer.hpp
- db/silkworm/db/buffer.cpp
- db/silkworm/db/buffer.hpp
- wasm/silkworm_wasm_api.cpp
- wasm/silkworm_wasm_api.hpp
> Fix remaining InvalidBlocks tests. Reorgs are not supported yet

- db/silkworm/db/tables.hpp
Port https://github.com/ledgerwatch/turbo-geth/pull/1464
> Remove hashed changesets

- README.md
- cmake/Hunter/config.cmake
- cmake/wasi.cmake
- cmd/CMakeLists.txt
> Update Catch for Apple M1 compatibility

- .circleci/config.yml
- CMakeLists.txt
- README.md
- appveyor.yml
Remove _manual_ step for submodules initialization.
Directly initialize submodules on build (as TG)
> Git submodule automation on build

- db/silkworm/common/log.cpp
- db/silkworm/common/log.hpp
- db/silkworm/common/log_test.cpp
Previous merge of this branch left date changes behind.
> Welcome to 2021!!!

- cmd/consensus.cpp
- cmd/scan_txs.cpp
- core/silkworm/chain/blockchain.cpp
- core/silkworm/chain/blockchain.hpp
- core/silkworm/chain/validity.cpp
- core/silkworm/chain/validity.hpp
- core/silkworm/execution/execution.cpp
- core/silkworm/execution/execution.hpp
- core/silkworm/execution/processor.cpp
- core/silkworm/execution/processor.hpp
- core/silkworm/execution/processor_test.cpp
- core/silkworm/state/buffer.hpp
- core/silkworm/state/memory_buffer.cpp
- core/silkworm/state/memory_buffer.hpp
- core/silkworm/types/account.cpp
- core/silkworm/types/block.cpp
- core/silkworm/types/block.hpp
- db/silkworm/db/access_layer.cpp
- db/silkworm/db/access_layer.hpp
- db/silkworm/db/buffer.cpp
- db/silkworm/db/buffer.hpp
- db/silkworm/db/util.cpp
- db/silkworm/db/util.hpp
- tg_api/silkworm_tg_api.cpp
- wasm/silkworm_wasm_api.cpp
- wasm/silkworm_wasm_api.hpp
> Blockchain reorgs

- core/silkworm/execution/precompiled.cpp
- core/silkworm/execution/precompiled.hpp
- core/silkworm/execution/precompiled_test.cpp
- core/silkworm/execution/protocol_param.hpp
> EIP-2565: ModExp Gas Cost

- core/silkworm/execution/execution.hpp
- db/silkworm/db/tables.hpp
Port https://github.com/ledgerwatch/turbo-geth/pull/1500
> New trie DB layout. Add missing snapshot info tables

- .circleci/config.yml
- .gitmodules
- CMakeLists.txt
- appveyor.yml
- cmake/Hunter/config.cmake
- cmd/CMakeLists.txt
- cmd/consensus.cpp
- core/silkworm/chain/config.hpp
- core/silkworm/execution/evm.cpp
- core/silkworm/execution/evm.hpp
- core/silkworm/execution/evm_test.cpp
> EIP-2315: Simple Subroutines for the EVM

- db/silkworm/db/access_layer.cpp
No need to traverse 2 tables (and some rlp decoding) to get genesis hash.
Is already canonical key in headers table
> Genesis lookup simplified

- cmd/blockhashes.cpp
- cmd/check_blockhashes.cpp
- cmd/check_senders.cpp
- cmd/extract_headers.cpp
- db/silkworm/db/access_layer.cpp
- db/silkworm/db/access_layer_test.cpp
- db/silkworm/db/chaindb.cpp
- db/silkworm/db/chaindb.hpp
- db/silkworm/db/tables.hpp
- db/silkworm/db/util.cpp
- db/silkworm/db/util.hpp
See https://github.com/ledgerwatch/turbo-geth/pull/1556
> Split header bucket to headers, td and canonical

- core/silkworm/chain/config.cpp
- core/silkworm/chain/config.hpp
- db/silkworm/db/access_layer.cpp
- db/silkworm/db/access_layer.hpp
- db/silkworm/db/access_layer_test.cpp
Also fixes a chain config parsing issue with GCC (see https://github.com/nlohmann/json/issues/2204)
> Test chain config parsing

- cmd/check_senders.cpp
Amends an error for large bacthes where the last very final batch was not processed.
> Final knobs on stage senders

- cmd/blockhashes.cpp
- cmd/check_blockhashes.cpp
- cmd/check_hashstate.cpp
- cmd/check_senders.cpp
- cmd/check_tx_lookup.cpp
- cmd/execute.cpp
- cmd/hashstate.cpp
- cmd/history_index.cpp
- cmd/tx_lookup.cpp
- db/silkworm/common/log.cpp
- db/silkworm/common/log.hpp
- db/silkworm/common/log_test.cpp
- db/silkworm/db/access_layer.cpp
- db/silkworm/db/access_layer.hpp
- db/silkworm/etl/collector.cpp
- tg_api/silkworm_tg_api.cpp
- tg_api/silkworm_tg_api.h
* Always prefer `enum class` vs `enum` to avoid clashes
* Throw exceptions instead of enum
> Enum exceptions

- cmake/Hunter/config.cmake
- db/silkworm/etl/buffer.cpp
- db/silkworm/etl/buffer.hpp
- db/silkworm/etl/collector.cpp
- db/silkworm/etl/file_provider.cpp
Higher-level alternative to PR #207. Kudos to @Giulio2002
> Optimize etl::Buffer

- db/silkworm/db/access_layer_test.cpp
- db/silkworm/db/stages.cpp
- db/silkworm/db/stages.hpp
- db/silkworm/db/tables.hpp
* Valid stage names
* get/set for Progress and Unwind
* clear Unwind
> Little extension on stages namespace

- cmd/consensus.cpp
- cmd/history_index.cpp
- cmd/initialize_with_genesis.cpp
- cmd/log_index.cpp
- core/silkworm/common/cast.hpp
- core/silkworm/common/util.hpp
- core/silkworm/state/intra_block_state.cpp
- core/silkworm/trie/hash_builder.cpp
- core/silkworm/types/block.cpp
- db/silkworm/db/access_layer.cpp
- db/silkworm/db/bitmap.cpp
- db/silkworm/etl/file_provider.cpp
Kudos to @eb: https://discord.com/channels/687972960811745322/733288466837799002/836534650197377024
> Backport C++20 std::bit_cast + other casting improvements

- cmd/CMakeLists.txt
- cmd/check_pow.cpp
- core/silkworm/rlp/encode.hpp
- core/silkworm/types/block.cpp
- core/silkworm/types/block.hpp
- db/silkworm/db/access_layer_test.cpp
- ethash/CMakeLists.txt
- ethash/ethash/endianess.hpp
- ethash/ethash/ethash.cpp
- ethash/ethash/ethash.hpp
- ethash/ethash/hash_types.hpp
- ethash/ethash/keccak.cpp
- ethash/ethash/keccak.hpp
* Complete ethash verification based on light cache
* check_pow processes all blocks in search of boundary violations or mix_hash mismatch
> Ethash implementation

- cmd/check_pow.cpp
- cmd/consensus.cpp
- core/silkworm/chain/config.cpp
- core/silkworm/chain/config.hpp
- core/silkworm/chain/config_test.cpp
- core/silkworm/chain/validity.cpp
- core/silkworm/chain/validity.hpp
- ethash/ethash/ethash.cpp
- ethash/ethash/ethash.hpp
> BlockHeader PoW Verification

- .gitmodules
- CMakeLists.txt
- core/silkworm/execution/analysis_cache.cpp
- core/silkworm/execution/analysis_cache.hpp
- core/silkworm/execution/evm.cpp
- core/silkworm/execution/state_pool.cpp
- core/silkworm/execution/state_pool.hpp
Utilize https://github.com/ethereum/evmone/pull/313
> Switch to the new evmone execution API

- .gitmodules
- core/silkworm/chain/config.hpp
- core/silkworm/chain/config_test.cpp
- core/silkworm/chain/difficulty.cpp
- core/silkworm/execution/evm.cpp
> Initial support for London + Difficulty bomb delay (EIP-3554)

- core/silkworm/chain/protocol_param.hpp
- core/silkworm/execution/evm.cpp
- core/silkworm/execution/execution_test.cpp
- core/silkworm/execution/precompiled.cpp
- core/silkworm/execution/processor.cpp
- core/silkworm/state/intra_block_state.cpp
- core/silkworm/state/intra_block_state.hpp
> EIP-3529: Reduction in refunds

- db/silkworm/common/os.hpp
- db/silkworm/db/chaindb.cpp
- db/silkworm/db/chaindb.hpp
Small reduction from boost's headers
> Less boost

- cmd/consensus.cpp
- core/silkworm/chain/intrinsic_gas_test.cpp
- core/silkworm/chain/protocol_param.hpp
- core/silkworm/chain/validity.cpp
- core/silkworm/chain/validity.hpp
- core/silkworm/chain/validity_test.cpp
- core/silkworm/execution/evm.cpp
- core/silkworm/execution/execution_test.cpp
- core/silkworm/execution/processor.cpp
- core/silkworm/execution/processor_test.cpp
- core/silkworm/rlp/decode.hpp
- core/silkworm/types/block.cpp
- core/silkworm/types/block.hpp
- core/silkworm/types/block_test.cpp
- core/silkworm/types/transaction.cpp
- core/silkworm/types/transaction.hpp
- core/silkworm/types/transaction_test.cpp
- db/silkworm/db/access_layer_test.cpp
> EIP-1559: Fee market change for ETH 1.0 chain

- core/silkworm/chain/validity.cpp
- core/silkworm/chain/validity.hpp
- core/silkworm/chain/validity_test.cpp
- core/silkworm/execution/processor.cpp
See https://github.com/ethereum/EIPs/pull/3594
> EIP-1559: add more constraints to the tx validation

- .gitmodules
- CMakeLists.txt
Pick up https://github.com/ethereum/evmone/pull/339
> Update evmone to prevent out of range access

- cmd/CMakeLists.txt
- cmd/check_hashstate.cpp
- cmd/hashstate.cpp
- cmd/trie.cpp
- db/silkworm/db/chaindb.hpp
- db/silkworm/trie/db_trie.cpp
- db/silkworm/trie/db_trie.hpp
> First cut of cmd/trie

- cmd/consensus.cpp
There are several test failures due to https://github.com/ethereum/tests/issues/865 and https://github.com/ethereum/tests/issues/869 <- **Fixed in [9.0.1](https://github.com/ethereum/tests/releases/tag/9.0.1)**
> Consensus tests: London update 9.0.1

- core/silkworm/chain/config.hpp
- db/silkworm/common/genesis_goerli.json
- db/silkworm/common/genesis_rinkeby.json
See https://github.com/ethereum/eth1.0-specs/commit/51053d6a57187ae1e3cc61368853593e44462076
> London blocks for testnets

- cmd/history_index.cpp
- cmd/log_index.cpp
- cmd/tx_lookup.cpp
See https://www.learncpp.com/cpp-tutorial/uninitialized-variables-and-undefined-behavior/
> Fix unitialized variables

- db/silkworm/db/tables.hpp
Rename database tables as per schema version 3.0.0
Remove unused table names
> Rename database tables as per schema version 3.0.0

- cmd/check_blockhashes.cpp
- cmd/check_hashstate.cpp
- cmd/check_senders.cpp
- cmd/check_tx_lookup.cpp
- db/silkworm/db/chaindb.cpp
- db/silkworm/stagedsync/recovery/recovery_farm.cpp
- db/silkworm/stagedsync/stage_blockhashes.cpp
- db/silkworm/stagedsync/stage_hashstate.cpp
- db/silkworm/stagedsync/stage_history_index.cpp
- db/silkworm/stagedsync/stage_log_index.cpp
- db/silkworm/stagedsync/stage_tx_lookup.cpp
> !rc is now rc == MDB_SUCCESS

- db/silkworm/stagedsync/stage_blockhashes.cpp
- db/silkworm/stagedsync/stage_bodies.cpp
- db/silkworm/stagedsync/stage_headers.cpp
- db/silkworm/stagedsync/stagedsync.hpp
- db/silkworm/stagedsync/stages.cpp
> added void unwind function for stages with no unwindings (headers, blockhashes and bodies)

- CMakeLists.txt
- cmake/Hunter/config.cmake
- core/silkworm/chain/config.hpp
- core/silkworm/crypto/ecdsa.cpp
- core/silkworm/execution/precompiled.cpp
- core/silkworm/execution/processor.cpp
- core/silkworm/rlp/encode.cpp
- wasm/silkworm_wasm_api.cpp
Upgrade evmone to [0.8.0](https://github.com/ethereum/evmone/releases/tag/v0.8.0)
> Upgrade evmone to 0.8.0

- db/silkworm/db/access_layer.cpp
- db/silkworm/db/access_layer_test.cpp
- db/silkworm/db/util.cpp
- db/silkworm/db/util.hpp
Fixes AddressSanitizer issue triggered by unwind_execution_test
> Fix read_storage

- cmd/dbtool.cpp
MDBX stores pages count as uint32_t
> Amend dbtool wrong page count

- cmd/blockhashes.cpp
- cmd/check_blockhashes.cpp
- cmd/check_changes.cpp
- cmd/check_hashstate.cpp
- cmd/check_pow.cpp
- cmd/check_senders.cpp
- cmd/check_tx_lookup.cpp
- cmd/dbtool.cpp
- cmd/execute.cpp
- cmd/hashstate.cpp
- cmd/history_index.cpp
- cmd/initialize_with_genesis.cpp
- cmd/log_index.cpp
- cmd/scan_txs.cpp
- cmd/trie.cpp
- cmd/tx_lookup.cpp
- db/silkworm/db/mdbx.hpp
- tg_api/silkworm_tg_api.cpp
Collection of small fixes required after migration to MDBX
> Mdbx errors

- db/silkworm/db/access_layer_test.cpp
- db/silkworm/stagedsync/unwind_execution_test.cpp
Otherwise tests take took long under Address Sanitizer
> Set db_config.inmemory = true for all tests

- core/silkworm/chain/intrinsic_gas_test.cpp
- core/silkworm/chain/validity.cpp
- core/silkworm/chain/validity_test.cpp
- core/silkworm/execution/processor_test.cpp
- core/silkworm/trie/vector_root_test.cpp
- core/silkworm/types/block_test.cpp
- core/silkworm/types/receipt.cpp
- core/silkworm/types/receipt.hpp
- core/silkworm/types/transaction.cpp
- core/silkworm/types/transaction.hpp
- core/silkworm/types/transaction_test.cpp
- db/silkworm/db/access_layer_test.cpp
- db/silkworm/types/receipt_cbor.cpp
- db/silkworm/types/receipt_cbor_test.cpp
https://github.com/ethereum/eth1.0-specs/tree/master/lists/signature-types
> Make transaction type into enum

- db/silkworm/db/access_layer.cpp
- db/silkworm/db/access_layer_test.cpp
> Fix historical_account

- db/silkworm/db/buffer.cpp
- db/silkworm/db/buffer_test.cpp
- db/silkworm/stagedsync/stage_execution.cpp
> Fix storage cleaning

- cmd/check_blockhashes.cpp
- cmd/check_senders.cpp
- cmd/check_tx_lookup.cpp
- cmd/dbtool.cpp
- cmd/extract_headers.cpp
- db/silkworm/stagedsync/stage_execution.cpp
- db/silkworm/stagedsync/stage_history_index.cpp
Post #293 some leftovers still around.
> Leftovers from application of PR 293

- db/silkworm/db/mdbx.cpp
- db/silkworm/db/mdbx.hpp
- db/silkworm/db/mdbx_test.cpp
`data` was not updated when calling the `WalkFunc`
> Fix for_each & for_count

- core/silkworm/common/base.hpp
- db/silkworm/db/mdbx.cpp
> Add some literals for bytes sizes

- cmd/CMakeLists.txt
- cmd/history_index.cpp
- cmd/unwind_history_index.cpp
- cmd/unwind_log_index.cpp
- db/silkworm/db/stages.hpp
- db/silkworm/stagedsync/stage_history_index.cpp
- db/silkworm/stagedsync/stage_log_index.cpp
This Pull Request Adds the following unwinds:
* Account History Index
* Storage History Index
* Log Index
> Unwind histories

- db/silkworm/etl/collector.cpp
- db/silkworm/etl/collector.hpp
Make collector's paths as std::filesystem::path and delete directory only if owned
Fixes #342
> Make collector's paths as std::filesystem::path

- core/silkworm/state/intra_block_state.cpp
- core/silkworm/state/intra_block_state.hpp
> Improve const-correctness of IntraBlockState::get_object

- cmd/initialize_with_genesis.cpp
- core/silkworm/common/base.hpp
- node/silkworm/stagedsync/stage_hashstate.cpp
- node/silkworm/stagedsync/stage_tx_lookup.cpp
> Disable ByteView(const uint8_t*) constructor

- cmd/consensus.cpp
- core/silkworm/chain/blockchain.cpp
- core/silkworm/chain/blockchain.hpp
- core/silkworm/chain/genesis_test.cpp
- core/silkworm/chain/validity.cpp
- core/silkworm/chain/validity.hpp
- core/silkworm/execution/evm_test.cpp
- core/silkworm/execution/execution.cpp
- core/silkworm/execution/execution.hpp
- core/silkworm/execution/execution_test.cpp
- core/silkworm/execution/processor_test.cpp
- core/silkworm/state/in_memory_state.cpp
- core/silkworm/state/in_memory_state.hpp
- core/silkworm/state/intra_block_state.hpp
- core/silkworm/state/state.hpp
- node/silkworm/db/buffer.hpp
- node/silkworm/stagedsync/stage_blockhashes_test.cpp
- node/silkworm/stagedsync/stage_hashstate_test.cpp
- node/silkworm/stagedsync/stage_senders_test.cpp
- node/silkworm/stagedsync/unwind_execution_test.cpp
- wasm/silkworm_wasm_api.cpp
- wasm/silkworm_wasm_api.hpp
InMemoryState is not a buffer to something; it holds entire state in memory.
> StateBuffer -> State, MemoryBuffer -> InMemoryState

- core/silkworm/crypto/ecdsa.cpp
- core/silkworm/crypto/ecdsa.hpp
- core/silkworm/crypto/ecdsa_test.cpp
- core/silkworm/execution/precompiled.cpp
- core/silkworm/rlp/decode.hpp
- core/silkworm/types/block_test.cpp
- core/silkworm/types/transaction.cpp
- core/silkworm/types/transaction.hpp
- node/silkworm/db/access_layer_test.cpp
- node/silkworm/stagedsync/stage_senders_test.cpp
- node/silkworm/stagedsync/tx_lookup_test.cpp
[EIP-155](https://eips.ethereum.org/EIPS/eip-155) implies that v >= 35.
Kudos to Artem for spotting this issue.
> Prohibit signature v when v != 27 && v != 28 && v < 35

- node/silkworm/db/access_layer.cpp
- node/silkworm/db/buffer.cpp
- node/silkworm/db/util.cpp
- node/silkworm/db/util.hpp
- node/silkworm/etl/collector.cpp
- node/silkworm/etl/collector.hpp
- node/silkworm/etl/collector_test.cpp
- node/silkworm/stagedsync/stage_hashstate.cpp
- node/silkworm/stagedsync/stage_hashstate_test.cpp
- node/silkworm/stagedsync/stage_history_index.cpp
- node/silkworm/stagedsync/stage_log_index.cpp
Our code has to be different from Erigon code because we don't have its `AutoDupSortKeysConversion` feature.
> Fix stage_hashstate for storage

- cmd/execute.cpp
- node/silkworm/db/access_layer_test.cpp
- node/silkworm/db/buffer.cpp
- node/silkworm/db/buffer.hpp
- node/silkworm/db/buffer_test.cpp
- node/silkworm/stagedsync/history_index_test.cpp
- node/silkworm/stagedsync/prune_execution_test.cpp
- node/silkworm/stagedsync/stage_execution.cpp
- node/silkworm/stagedsync/stage_hashstate_test.cpp
- node/silkworm/stagedsync/unwind_execution_test.cpp
This optimize the execution stage when in pruning mode.
> Better execution pruning

- node/silkworm/stagedsync/recovery/recovery_farm.cpp
*Don't error if transaction.type == 0x1
> senders_recovery:

- cmd/check_pow.cpp
- cmd/execute.cpp
- cmd/hashstate.cpp
- cmd/history_index.cpp
- cmd/log_index.cpp
- cmd/toolbox.cpp
- cmd/tx_lookup.cpp
- node/silkworm/db/access_layer_test.cpp
- node/silkworm/db/stages.cpp
- node/silkworm/db/stages.hpp
- node/silkworm/downloader/internals/DbTx.hpp
- node/silkworm/stagedsync/history_index_test.cpp
- node/silkworm/stagedsync/prune_execution_test.cpp
- node/silkworm/stagedsync/recovery/recovery_farm.cpp
- node/silkworm/stagedsync/stage_blockhashes.cpp
- node/silkworm/stagedsync/stage_execution.cpp
- node/silkworm/stagedsync/stage_hashstate.cpp
- node/silkworm/stagedsync/stage_hashstate_test.cpp
- node/silkworm/stagedsync/stage_history_index.cpp
- node/silkworm/stagedsync/stage_log_index.cpp
- node/silkworm/stagedsync/stage_senders.cpp
- node/silkworm/stagedsync/stage_senders_test.cpp
- node/silkworm/stagedsync/stage_tx_lookup.cpp
- node/silkworm/stagedsync/unwind_execution_test.cpp
* rename base methods
* added methods for read/write prune and unwind progress
* tests
> Rename get/set progress -> read/write progress

- cmd/check_senders.cpp
- node/silkworm/stagedsync/recovery/recovery_farm.cpp
- node/silkworm/stagedsync/recovery/recovery_farm.hpp
- node/silkworm/stagedsync/stage_senders.cpp
- make unwind method static
- introduce tx type checks
- small fixes
> Sender's recovery

- node/silkworm/stagedsync/prune_execution_test.cpp
- node/silkworm/stagedsync/stage_blockhashes_test.cpp
- node/silkworm/stagedsync/stage_hashstate_test.cpp
- node/silkworm/stagedsync/tx_lookup_test.cpp
- use sections and reuse common part of test cases
> Reduce test code

- cmd/download_headers.cpp
- node/silkworm/downloader/header_downloader.cpp
- node/silkworm/downloader/header_downloader.hpp
- node/silkworm/downloader/internals/db_tx.hpp
- node/silkworm/downloader/internals/db_tx_test.cpp
- node/silkworm/downloader/internals/persisted_chain.cpp
- node/silkworm/downloader/internals/persisted_chain.hpp
- node/silkworm/downloader/internals/persisted_chain_test.cpp
- node/silkworm/downloader/internals/working_chain.cpp
- node/silkworm/downloader/internals/working_chain.hpp
- node/silkworm/downloader/messages/InboundBlockHeaders.cpp
- node/silkworm/downloader/messages/InboundGetBlockBodies.cpp
- node/silkworm/downloader/messages/InboundGetBlockHeaders.cpp
- node/silkworm/downloader/messages/InboundNewBlock.cpp
- node/silkworm/downloader/messages/InboundNewBlockHashes.cpp
- node/silkworm/downloader/messages/OutboundGetBlockHeaders.cpp
- node/silkworm/downloader/messages/OutboundGetBlockHeaders.hpp
- node/silkworm/downloader/messages/OutboundMessage.hpp
- node/silkworm/downloader/messages/OutboundNewBlockHashes.cpp
- node/silkworm/downloader/messages/OutboundNewBlockHashes.hpp
Complete the implementation of the downloader unwind method.
Test are still missing.
> Downloader unwind method

- core/silkworm/chain/difficulty.hpp
We forgot to remove them in PR #501.
> Clean up declarations of deleted difficulty functions

- .circleci/config.yml
See https://github.com/wasmerio/wasmer/issues/1651
> Quick fix for wasmer

- cmd/silkworm.cpp
- node/silkworm/common/settings.hpp
- node/silkworm/db/mdbx.cpp
- node/silkworm/db/mdbx.hpp
* increase chain db default size limit to 3TB as in [Erigon](https://github.com/ledgerwatch/erigon/pull/3057)
* prevent opening a db file where disk size exceed MAP_SIZE
> Dbsize hardcap

- .circleci/config.yml
- cmake/compiler_settings.cmake
- cmd/silkworm.cpp
- node/silkworm/common/settings.hpp
- node/silkworm/db/access_layer_test.cpp
- node/silkworm/db/storage.cpp
- node/silkworm/db/storage.hpp
* implements correct parsing and reciprocal exclusions of cli arguments
* implements read/write to db (yet convoluted - but keeps db compat)
* change node_settings
> Erigon's pruning mode

- cmd/silkworm.cpp
- node/silkworm/db/storage.cpp
* corrects invalid access to unset optional
* corrects error for null on BlockAmounts if no CLI params set
> Amend errors from #514

- cmd/consensus.cpp
With [release 10.2](https://github.com/ethereum/tests/releases/tag/v10.2) transaction tests now have intrinsic gas.
> Check intrinsic gas in transaction tests

- node/silkworm/stagedsync/stage_execution.cpp
> Amend execution unwind logic

- cmd/check_blockhashes.cpp
- cmd/check_tx_lookup.cpp
- cmd/toolbox.cpp
- node/silkworm/db/access_layer.cpp
- node/silkworm/db/stages.cpp
- node/silkworm/db/util.hpp
- node/silkworm/stagedsync/_test.cpp
- node/silkworm/stagedsync/recovery/recovery_farm.cpp
- node/silkworm/stagedsync/stage_blockhashes.cpp
- node/silkworm/stagedsync/stage_execution.cpp
- node/silkworm/stagedsync/stage_history_index.cpp
- node/silkworm/stagedsync/stage_log_index.cpp
- node/silkworm/stagedsync/stage_tx_lookup.cpp
`iov_base` looks like an implementation detail we shouldn't rely upon
> mdbx::slice::data() instead of iov_base

- cmd/toolbox.cpp
- node/silkworm/common/settings.hpp
- node/silkworm/db/access_layer_test.cpp
- node/silkworm/db/prune_mode.cpp
- node/silkworm/db/prune_mode.hpp
"prune mode" is more specific than "storage". Also the main class there is `PruneMode`.
> storage.hpp -> prune_mode.hpp

- core/silkworm/common/base_test.cpp
Nothing fancy, just a simple and basic unit test.
> Basic test of empty hashes

- node/silkworm/stagedsync/stage_execution.cpp
Just a small addition to get block hash in case of execution failure
> Emit block hash on execution failure

- core/silkworm/chain/config.cpp
- core/silkworm/chain/config.hpp
- core/silkworm/chain/config_test.cpp
Corresponds to TERMINAL_BLOCK_HASH & TERMINAL_BLOCK_NUMBER in [EIP-3675](https://eips.ethereum.org/EIPS/eip-3675).
> Added terminal block number and hash

- README.md
Amend tests and consensus paths
> Update readme with proper paths

- core/silkworm/common/base_test.cpp
Finally, after https://github.com/ethereum/yellowpaper/pull/852, I understand where the empty root hash comes from.
> Test kEmptyRoot

- .gitmodules
> New libmdbx source

- cmd/test/backend_kv_test.cpp
- node/silkworm/rpc/backend_calls.cpp
- node/silkworm/rpc/backend_kv_server_test.cpp
- node/silkworm/rpc/conversion.cpp
- node/silkworm/rpc/conversion.hpp
- node/silkworm/rpc/conversion_test.cpp
- node/silkworm/rpc/state_change_collection.cpp
- node/silkworm/rpc/state_change_collection.hpp
- node/silkworm/rpc/state_change_collection_test.cpp
- node/silkworm/rpc/util.hpp
- node/silkworm/rpc/util_test.cpp
Add collection of state changes
Add unit tests
Add common conversions for RPC types
TODOLIST:
- refactor `downloader` to use new conversion functions
- StateChanges RPC implementation
- integration with StagedSync loop
> Add state change collection for KV StateChanges API

- node/silkworm/backend/ethereum_backend.cpp
- node/silkworm/backend/ethereum_backend.hpp
- node/silkworm/backend/ethereum_backend_test.cpp
- node/silkworm/rpc/server/backend_kv_server_test.cpp
- node/silkworm/rpc/server/call.hpp
- node/silkworm/rpc/server/kv_calls.cpp
- node/silkworm/rpc/server/kv_calls.hpp
- node/silkworm/rpc/server/state_change_collection.cpp
- node/silkworm/rpc/server/state_change_collection.hpp
- node/silkworm/rpc/server/state_change_collection_test.cpp
Create unique state change collection point
Register StateChanges calls on collection point
Refactor server-streaming RPC close
Add unit tests
> StateChanges call-collection integration

- CMakeLists.txt
- cmake/Hunter/config.cmake
Update Hunter to [v0.24.3](https://github.com/cpp-pm/hunter/releases/tag/v0.24.3) and Microsoft.GSL to [v4.0.0](https://github.com/microsoft/GSL/releases/tag/v4.0.0).
> Update Hunter to v0.24.3

- .circleci/config.yml
- core/silkworm/chain/config.cpp
- core/silkworm/chain/config.hpp
- core/silkworm/trie/node.cpp
- core/silkworm/trie/node.hpp
- core/silkworm/types/account.cpp
- core/silkworm/types/account.hpp
- core/silkworm/types/block.cpp
- core/silkworm/types/block.hpp
- core/silkworm/types/transaction.cpp
- core/silkworm/types/transaction.hpp
- node/silkworm/db/prune_mode.hpp
- node/silkworm/db/util.hpp
Use C++20 [default comparisons](https://en.cppreference.com/w/cpp/language/default_comparisons).
> Default comparison operators

- cmd/sentry.cpp
- cmd/test/CMakeLists.txt
- sentry/sentry/enode_url.cpp
- sentry/sentry/enode_url.hpp
- sentry/sentry/enode_url_test.cpp
Note: the sentry_test target is not added to the CI scripts yet.
> sentry: --staticpeers option

- cmake/Hunter/config.cmake
- core/CMakeLists.txt
- node/CMakeLists.txt
Fixes https://github.com/torquem-ch/silkworm/issues/674 and https://github.com/torquem-ch/silkworm/issues/673 and https://github.com/torquem-ch/silkworm/issues/688
References:
https://github.com/protocolbuffers/protobuf/issues/8958
https://stackoverflow.com/questions/9894961/strange-warnings-from-the-linker-ld
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/CppRuntimeEnv/Articles/SymbolVisibility.html#//apple_ref/doc/uid/TP40001670-98807
> Fix link warnings on macOS

- node/silkworm/downloader/internals/chain_elements.hpp
Use C++20 [std::erase_if](https://en.cppreference.com/w/cpp/container/vector/erase2).
> std::erase_if instead of remove_if

- cmd/backend_kv_server.cpp
- cmd/common.cpp
- core/silkworm/chain/config.cpp
- core/silkworm/chain/config.hpp
- core/silkworm/chain/config_test.cpp
- node/silkworm/db/access_layer.cpp
- node/silkworm/db/access_layer.hpp
- node/silkworm/db/genesis.cpp
- node/silkworm/db/genesis_test.cpp
- node/silkworm/rpc/server/backend_kv_server_test.cpp
- node/silkworm/stagedsync/common.hpp
- wasm/silkworm_wasm_api.cpp
Should new forkblocks be added persisted config should be updated to hardcoded one.
Fixes #717
> Chain config consistency with hardcoded one

- README.md
> Specify execution client

- cmd/common.cpp
- node/silkworm/db/mdbx.cpp
- node/silkworm/db/mdbx.hpp
- node/silkworm/db/mdbx_test.cpp
> Configurable MDBX page size from CLI

- sentry/CMakeLists.txt
- sentry/silkworm/sentry/rlpx/auth/handshake.cpp
- sentry/silkworm/sentry/rlpx/auth/handshake.hpp
- sentry/silkworm/sentry/rlpx/auth/hello_message.cpp
- sentry/silkworm/sentry/rlpx/auth/hello_message.hpp
- sentry/silkworm/sentry/rlpx/framing/message_frame_codec.cpp
- sentry/silkworm/sentry/rlpx/framing/message_frame_codec.hpp
- sentry/silkworm/sentry/rlpx/framing/message_stream.cpp
- sentry/silkworm/sentry/rlpx/framing/message_stream.hpp
- sentry/silkworm/sentry/rlpx/peer.cpp
* snappy compression
* return remote stream from Handshake to Peer
* capability match
* handle connection reset and Disconnect message from Handshake
> sentry: post-handshake logic and improvements

- cmd/toolbox.cpp
> ER Patch - Restore functionality of Toolbox

- node/silkworm/stagedsync/_test.cpp
- node/silkworm/stagedsync/stage_senders.cpp
- node/silkworm/stagedsync/stage_senders/recovery_farm.cpp
- node/silkworm/stagedsync/stage_senders/recovery_farm.hpp
After #761 senders' recovery logging was blank.
This fixes it
> Amend senders' recovery logging

- CMakeLists.txt
> Fix build using default toolchain

- node/silkworm/common/memory_mapped_file.cpp
This PR fixes a build issue about mmap flags on macOS platform
> Fix mmap build issue on macOS

- node/silkworm/rpc/server/backend_calls.cpp
- node/silkworm/rpc/server/backend_calls.hpp
- node/silkworm/rpc/server/kv_calls.cpp
Refactor ETHBACKEND calls
Cleanup KV call registration
> Refactor ETHBACKEND calls

- core/silkworm/execution/processor.cpp
[EIP-3651](https://eips.ethereum.org/EIPS/eip-3651) is [included](https://github.com/ethereum/execution-specs/pull/633) into [Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md).
> EIP-3651: Warm COINBASE

- node/silkworm/downloader/internals/header_persistence.cpp
- node/silkworm/downloader/internals/header_persistence.hpp
Here we avoid fetching parent header always even when there is no forking point.
> Downloader small optimization

- node/silkworm/common/log_test.cpp
- node/silkworm/rpc/server/server_context_pool_test.cpp
- node/silkworm/rpc/util_test.cpp
- node/silkworm/snapshot/decompressor.cpp
- node/silkworm/snapshot/decompressor.hpp
- node/silkworm/snapshot/decompressor_test.cpp
- node/silkworm/test/log.hpp
This PR adds a decompressing decoder for Snapshot Sync files.
> Add snapshot decompressor

- .circleci/config.yml
- cmd/CMakeLists.txt
- cmd/README.md
- cmd/snapshots.cpp
- node/silkworm/common/memory_mapped_file.hpp
- node/silkworm/db/util.cpp
- node/silkworm/db/util.hpp
- node/silkworm/snapshot/decompressor.cpp
- node/silkworm/snapshot/decompressor_test.cpp
- node/silkworm/snapshot/repository.cpp
- node/silkworm/snapshot/repository.hpp
- node/silkworm/snapshot/repository_test.cpp
- node/silkworm/snapshot/snapshot.cpp
- node/silkworm/snapshot/snapshot.hpp
- node/silkworm/snapshot/snapshot_test.cpp
- node/silkworm/test/files.hpp
- node/silkworm/test/snapshot_files.hpp
This PR adds a new `snapshots` tool to the Silkworm toolbox
> Add snapshots tool

- node/silkworm/snapshot/decompressor.cpp
- node/silkworm/snapshot/repository_test.cpp
Tried compiling this project with Visual Studio 2022, fixed a couple of compile errors. There is also an intrinsic which was removed in one of the libraries, so it also requires this https://github.com/torquem-ch/libff/pull/1
> Fixes for compiling with Visual Studio 2022

- core/silkworm/rlp/decode.hpp
- core/silkworm/rlp/decode_test.cpp
- core/silkworm/types/block.cpp
- core/silkworm/types/transaction.cpp
- node/silkworm/db/util.cpp
- node/silkworm/downloader/packets/block_bodies_packet.hpp
- node/silkworm/downloader/packets/block_headers_packet.hpp
- node/silkworm/downloader/packets/get_block_bodies_packet.hpp
- node/silkworm/downloader/packets/new_block_hashes_packet.hpp
- node/silkworm/downloader/packets/rlp_decoding.cpp
Solves https://github.com/torquem-ch/silkworm/issues/493
> Remove rlp::decode_vector

- node/silkworm/downloader/internals/header_persistence.cpp
Stage Headers unwind method lacks the stage progress update
> Fix downloader unwind

- node/silkworm/recsplit/support/common.hpp
This PR restores Apple M1 build broken after merging #824
> Fix Apple M1 build

- cmd/toolbox.cpp
This PR adds `--keep-senders` flag to `reset-to-download` command in `toolbox` to avoid cleaning transaction sender addresses recovered by stage Senders.
> Add flag to keep recovered senders in toolbox reset-to-download command

- core/silkworm/common/base.hpp
- core/silkworm/consensus/clique/engine.cpp
- core/silkworm/consensus/clique/engine.hpp
- core/silkworm/consensus/clique/engine_test.cpp
- core/silkworm/consensus/engine.cpp
- core/silkworm/consensus/engine_test.cpp
- core/silkworm/types/block.cpp
- core/silkworm/types/block.hpp
- core/silkworm/types/block_test.cpp
This PR introduces the Clique consensus engine to correctly set the reward beneficiary for `trace/debug` APIs in Goerli network
> Add clique consensus

- sentry/silkworm/sentry/rpc/server_calls.hpp
- sentry/silkworm/sentry/sentry.cpp
- sentry/silkworm/sentry/status_manager.cpp
- sentry/silkworm/sentry/status_manager.hpp
erigon calls Handshake and SetStatus multiple times
> sentry: support multiple calls to SetStatus

- node/silkworm/common/environment_test.cpp
> Add Environment class tests

- node/silkworm/backend/backend_kv_server_test.cpp
- node/silkworm/backend/rpc/kv_calls.cpp
> node: fix wrong timer usage in max TTL handler for KV Tx RPC

- node/silkworm/common/log.cpp
- node/silkworm/common/log.hpp
- node/silkworm/common/log_test.cpp
- node/silkworm/snapshot/config.cpp
- node/silkworm/snapshot/config.hpp
- node/silkworm/snapshot/config_test.cpp
This PR implements the facilities needed to lookup the initial static configuration for snapshots.
> node: extend snapshot config

- cmd/snapshots.cpp
- node/silkworm/bittorrent/client.cpp
- node/silkworm/bittorrent/client.hpp
- node/silkworm/bittorrent/client_test.cpp
- node/silkworm/bittorrent/settings.hpp
- node/silkworm/snapshot/settings.hpp
This PR changes the BitTorrent client again moving the BitTorrent settings in a separate module to allow inclusion in snapshot settings.
> Refactor BitTorrent client

- cmd/common.cpp
- cmd/common.hpp
- cmd/silkworm.cpp
- cmd/snapshots.cpp
- node/silkworm/bittorrent/client.cpp
- node/silkworm/bittorrent/client.hpp
- node/silkworm/bittorrent/client_test.cpp
- node/silkworm/bittorrent/settings.hpp
- node/silkworm/common/settings.hpp
- node/silkworm/snapshot/index.hpp
- node/silkworm/snapshot/repository.cpp
- node/silkworm/snapshot/repository.hpp
- node/silkworm/snapshot/settings.hpp
- node/silkworm/snapshot/sync.cpp
- node/silkworm/snapshot/sync.hpp
- node/silkworm/snapshot/sync_test.cpp
This PR introduces the following changes in the snapshot sync functionality:
- add snapshot sync engine [WIP]
- add parallel build for missing indices
- add snapshot command-line options [WIP]
- add sync utility in snapshots tool
- refactor other utilities in snapshots tool
> Add snapshot sync facade

- silkworm/sentry/rlpx/common/disconnect_reason.hpp
- silkworm/sentry/rlpx/peer.cpp
* send outgoing Disconnect message on shutdown
* incoming Disconnect message handling
> sentry: RLPx Disconnect message logic

- .clang-format
- cmake/copyright.cmake
- cmake/format.cmake
- silkworm/node/backend/rpc/kv_calls.hpp
- silkworm/node/backend/rpc/sentry_client.hpp
- silkworm/node/common/environment.cpp
- silkworm/node/common/memory_mapped_file_benchmark.cpp
- silkworm/node/downloader/packets/rlp_encoding.cpp
- silkworm/node/stagedsync/stage_interhashes/_test.cpp
- silkworm/sentry/common/sleep.cpp
- silkworm/sentry/common/sleep.hpp
- silkworm/sentry/peer_manager.hpp
- silkworm/sentry/rlpx/auth/hello_message.cpp
- silkworm/sentry/rlpx/client.cpp
- silkworm/sentry/rlpx/client.hpp
- silkworm/sentry/rlpx/peer.cpp
- silkworm/sentry/rlpx/peer.hpp
- silkworm/sentry/rlpx/ping_message.cpp
- silkworm/sentry/sentry.cpp
Fix the scripts after the sources were moved to silkworm subfolder.
> fix make fmt lint

- cmd/test/consensus.cpp
[Tests update 12: Shanghai tests](https://github.com/ethereum/tests/releases/tag/v12)
> Update ethereum/tests to v12

- cmake/profiles/windows_msvc_17_debug
- cmake/profiles/windows_msvc_17_release
Add two Conan profiles for Windows using the MS Visual Studio 2022 compiler.
> Add Conan profiles for MSVC

- CMakeLists.txt
- third_party/CMakeLists.txt
Reduce the size of the main `CMakeLists.txt`
> build: extract third_party/CMakeLists.txt

- silkworm/silkrpc/API.md
- silkworm/silkrpc/commands/eth_api.cpp
- silkworm/silkrpc/commands/eth_api.hpp
- silkworm/silkrpc/commands/rpc_api_table.cpp
- silkworm/silkrpc/http/methods.hpp
- tests/integration/goerly/eth_maxPriorityFeePerGas/test_1.json
- tests/integration/run_tests.py
Implemenation for eth_maxPriorityFeePerGas API
> rpcdaemon: add eth_maxPriorityFeePerGas implementation

- cmd/silkworm.cpp
> silkworm: fix std::optional assignment

- cmd/silkworm.cpp
- silkworm/node/bittorrent/client.cpp
- silkworm/node/bittorrent/client.hpp
- silkworm/node/bittorrent/client_test.cpp
- silkworm/node/bittorrent/settings.hpp
- silkworm/node/snapshot/sync.cpp
> node: add BitTorrent client stats

- silkworm/silkrpc/common/util.cpp
- silkworm/silkrpc/common/util.hpp
- silkworm/silkrpc/common/util_test.cpp
- silkworm/silkrpc/types/dump_account.cpp
Replace pointer+size with ByteView
Remove unnecessary namespace qualification
> rpcdaemon: improve base64_encode utility

- cmd/silkworm.cpp
- silkworm/node/huffman/decompressor.cpp
- silkworm/node/huffman/decompressor.hpp
- silkworm/node/huffman/decompressor_test.cpp
- silkworm/node/snapshot/index.cpp
- silkworm/node/snapshot/index.hpp
- silkworm/node/snapshot/repository.cpp
- silkworm/node/snapshot/repository.hpp
- silkworm/node/snapshot/repository_test.cpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
- silkworm/node/snapshot/snapshot_test.cpp
- silkworm/node/snapshot/sync.cpp
node: add snapshot repository close
node: avoid static memory for decompressor pattern and position tables
cmd: add missing commit for snapshot sync txn
> node: build snapshot indexes in parallel

- silkworm/silkrpc/concurrency/context_pool.cpp
- silkworm/silkrpc/concurrency/context_pool.hpp
- silkworm/silkrpc/core/filter_storage.hpp
Modified representation for DEFAULT_FILTER_STORAGE_SIZE and DEFAULT_MAX_FILTER_AGE constants.
> rpcdaemon: change constants representation

- silkworm/silkrpc/API.md
- silkworm/silkrpc/commands/admin_api.cpp
- silkworm/silkrpc/commands/admin_api.hpp
- silkworm/silkrpc/commands/rpc_api.hpp
- silkworm/silkrpc/commands/rpc_api_table.cpp
- silkworm/silkrpc/commands/rpc_api_table.hpp
- silkworm/silkrpc/common/constants.hpp
- silkworm/silkrpc/http/methods.hpp
- silkworm/silkrpc/json/types.cpp
- silkworm/silkrpc/json/types.hpp
- tests/integration/goerly/admin_nodeInfo/test_1.json
- tests/integration/goerly/admin_peers/test_1.json
Added AdminRpcApi class for admin RPC calls: `admin_nodeInfo` and `admin_peers`
> rpcdaemon: admin_nodeInfo and admin_peers implementation

- cmd/silkworm.cpp
- silkworm/infra/concurrency/context_pool.hpp
- silkworm/infra/grpc/server/server_context_pool.cpp
- silkworm/node/backend/ethereum_backend.cpp
- silkworm/node/backend/ethereum_backend.hpp
> cmd: fix silkworm termination handling in case of any task exception

- silkworm/sentry/common/ecc_key_pair.cpp
- silkworm/sentry/common/ecc_public_key.cpp
- silkworm/sentry/common/timeout.hpp
- silkworm/sentry/message_receiver.cpp
- silkworm/sentry/node_key_config.cpp
- silkworm/sentry/peer_manager.cpp
- silkworm/sentry/peer_manager_api.cpp
- silkworm/sentry/rlpx/auth/auth_message.cpp
- silkworm/sentry/rlpx/auth/ecies_cipher.cpp
- silkworm/sentry/rlpx/auth/handshake.cpp
- silkworm/sentry/rlpx/auth/handshake.hpp
- silkworm/sentry/rlpx/client.cpp
- silkworm/sentry/rlpx/crypto/hmac.cpp
- silkworm/sentry/rlpx/framing/framing_cipher.cpp
- silkworm/sentry/rlpx/framing/message_stream.cpp
- silkworm/sentry/rlpx/peer.cpp
- silkworm/sentry/rlpx/peer.hpp
- silkworm/sentry/rlpx/protocol.hpp
- silkworm/sentry/rlpx/server.cpp
- silkworm/sentry/rpc/client/sentry_client.cpp
- silkworm/sentry/rpc/server/server.cpp
- silkworm/sentry/sentry.cpp
- silkworm/sentry/status_manager.cpp
* add "sentry" category/module
* ensure prefix with class/method name
* prefix runtime_error messages with class/method name
* adjust log levels
> sentry: update log messages

- cmd/silkworm.cpp
- silkworm/infra/common/memory_mapped_file.cpp
- silkworm/infra/common/memory_mapped_file.hpp
- silkworm/infra/common/memory_mapped_file_test.cpp
- silkworm/infra/common/os.cpp
- silkworm/infra/common/os.hpp
- silkworm/infra/common/os_test.cpp
- silkworm/node/backend/remote/backend_kv_server_test.cpp
infra: add memory-mapped input stream
node: increase KV Tx max TTL in unit test
> infra: cleanup and move OS utilities

- silkworm/node/bittorrent/client.cpp
- silkworm/node/bittorrent/client.hpp
- silkworm/node/bittorrent/client_test.cpp
- silkworm/node/bittorrent/settings.hpp
- silkworm/node/recsplit/encoding/elias_fano.hpp
- silkworm/node/recsplit/encoding/elias_fano_test.cpp
- silkworm/node/recsplit/encoding/golomb_rice.hpp
- silkworm/node/recsplit/rec_split.hpp
- silkworm/node/recsplit/rec_split_test.cpp
node: create Elias-Fano encoding from existing data
node: refactor Golomb-Rice encoding
Requires #1035
> node: recsplit index open

- silkworm/node/db/tables.hpp
- silkworm/node/huffman/decompressor.hpp
- silkworm/node/snapshot/path.cpp
- silkworm/node/snapshot/path.hpp
- silkworm/node/snapshot/repository.cpp
- silkworm/node/snapshot/repository.hpp
- silkworm/node/snapshot/settings.hpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
- silkworm/node/snapshot/snapshot_test.cpp
- silkworm/node/snapshot/sync.cpp
- silkworm/node/snapshot/sync.hpp
- silkworm/node/snapshot/sync_test.cpp
node: compute max snapshot index available
node: fix segment max block
node: remove verification (previously moved to BitTorrent client)
> node: add snapshot index reopening

- silkworm/silkrpc/API.md
- silkworm/silkrpc/commands/rpc_api_table.cpp
- silkworm/silkrpc/http/methods.hpp
Implemenation for eth_getTransactionReceiptsByBlock API
> rpcdaemon: add eth_getTransactionReceiptsByBlock API

- silkworm/silkrpc/CMakeLists.txt
- third_party/CMakeLists.txt
See [v0.10.0 release notes](https://github.com/ethereum/evmone/releases/tag/v0.10.0)
> third_party: upgrade evmone to 0.10.0

- silkworm/infra/grpc/client/client_context_pool.cpp
- silkworm/infra/grpc/client/client_context_pool.hpp
- silkworm/silkrpc/daemon.cpp
- silkworm/silkrpc/daemon.hpp
- silkworm/sync/sync.cpp
- silkworm/sync/sync.hpp
rpcdaemon: fix settings lifetime
infra: remove duplicated code
> sync: fix startup sequence

- .circleci/config.yml
- .gitmodules
- README.md
- silkworm/silkrpc/core/evm_trace_test.cpp
- silkworm/silkrpc/core/fee_history_oracle_test.cpp
- silkworm/silkrpc/http/request.hpp
- third_party/wasmer/install.sh
* update cpp-build-env to v20
* update clang 13 job to clang 16
* update gcc 11 conan job to gcc 13
* update magic_enum to v0.8.2 to compile on clang 16
* update libtorrent to RC_2_0 @ 272828e + custom fix https://github.com/arvidn/libtorrent/pull/7410 to compile on gcc 13
* fix cbor to compile on gcc 13 - https://github.com/torquem-ch/cbor-cpp/pull/2
* vendor wasmer.io install script to avoid CI error 400
> CI: update compilers

- .gitmodules
- cmake/profiles/experimental/linux_gcc_12_debug
- cmake/profiles/experimental/linux_gcc_12_release
- cmake/profiles/experimental/macos_arm_clang_14_debug
- cmake/profiles/experimental/macos_arm_clang_14_release
- cmake/profiles/experimental/macos_x64_clang_14_debug
- cmake/profiles/experimental/macos_x64_clang_14_release
- cmake/profiles/experimental/readme.txt
* conan: experimental profiles
* third_party: point libtorrent to the updated upstream
> build: experimental conan profiles and libtorrent update

- requirements.txt
- tests/integration/README.md
docs: improve requirements for integration tests
> test: add missing python modules for integration test runner

- silkworm/node/db/util.cpp
- silkworm/node/db/util.hpp
- silkworm/node/db/util_test.cpp
> node: withdrawals in BlockBodyForStorage::encode

- silkworm/silkrpc/API.md
- silkworm/silkrpc/commands/engine_api.cpp
- silkworm/silkrpc/commands/engine_api.hpp
- silkworm/silkrpc/commands/engine_api_test.cpp
- silkworm/silkrpc/commands/rpc_api_table.cpp
- silkworm/silkrpc/ethbackend/backend.hpp
- silkworm/silkrpc/ethbackend/remote_backend.cpp
- silkworm/silkrpc/ethbackend/remote_backend.hpp
- silkworm/silkrpc/ethbackend/remote_backend_test.cpp
- silkworm/silkrpc/http/methods.hpp
- silkworm/silkrpc/json/execution_payload.cpp
- silkworm/silkrpc/json/execution_payload.hpp
- silkworm/silkrpc/json/execution_payload_test.cpp
- silkworm/silkrpc/json/types.cpp
- silkworm/silkrpc/types/execution_payload.cpp
- silkworm/silkrpc/types/execution_payload.hpp
- silkworm/silkrpc/types/execution_payload_test.cpp
- silkworm/sync/engine_api_backend.cpp
- silkworm/sync/engine_api_backend.hpp
- silkworm/sync/sync_pos.cpp
- silkworm/sync/sync_pos.hpp
- tests/integration/goerly/engine_getPayloadV2/test_1.json
refactor engine_getPayloadV1 API
> rpcdaemon, sync: add engine_getPayloadV2 API

- .circleci/config.yml
- silkworm/silkrpc/commands/engine_api.cpp
- silkworm/silkrpc/commands/engine_api.hpp
- silkworm/silkrpc/commands/rpc_api_table.cpp
- silkworm/silkrpc/ethbackend/remote_backend.cpp
- silkworm/silkrpc/http/methods.hpp
- silkworm/silkrpc/protocol/errors.hpp
- silkworm/silkrpc/types/execution_payload.cpp
- silkworm/silkrpc/types/execution_payload.hpp
- silkworm/silkrpc/types/execution_payload_test.cpp
- tests/integration/goerly/engine_forkchoiceUpdatedV2/test_1.json
refactor engine_forkchoiceUpdatedV1 API
> rpcdaemon, sync: add engine_forkchoiceUpdatedV2 API

- silkworm/infra/grpc/common/conversion.cpp
- silkworm/infra/grpc/common/conversion.hpp
- silkworm/silkrpc/commands/engine_api.cpp
- silkworm/silkrpc/commands/engine_api.hpp
- silkworm/silkrpc/commands/engine_api_test.cpp
- silkworm/silkrpc/commands/rpc_api_table.cpp
- silkworm/silkrpc/ethbackend/backend.hpp
- silkworm/silkrpc/ethbackend/remote_backend.cpp
- silkworm/silkrpc/ethbackend/remote_backend.hpp
- silkworm/silkrpc/http/methods.hpp
- silkworm/silkrpc/json/execution_payload.cpp
- silkworm/silkrpc/json/execution_payload.hpp
- silkworm/silkrpc/json/execution_payload_test.cpp
- silkworm/silkrpc/types/execution_payload.cpp
- silkworm/silkrpc/types/execution_payload.hpp
- silkworm/silkrpc/types/execution_payload_test.cpp
- silkworm/sync/engine_api_backend.cpp
- silkworm/sync/engine_api_backend.hpp
- silkworm/sync/sync_pos.cpp
- silkworm/sync/sync_pos.hpp
- tests/integration/goerly/engine_getPayloadBodiesByHashV1/test_1.json
- tests/integration/goerly/engine_getPayloadBodiesByHashV1/test_2.json
infra: add conversion utility for repeated hash fields
> rpcdaemon, sync: add engine_getPayloadBodiesByHashV1 API

- .circleci/config.yml
- cmake/setup/compiler_install.sh
Separate workflows:
"light" workflow for PR branches builds:
- gcc latest release
- clang latest release
"integration" workflow for master (and branches named "ci/xxx") builds:
- gcc min release
- clang min release
- gcc with thread-sanitizer debug
- clang with address-sanitizer debug
- clang with coverage debug
- wasm
> CI: light + integration workflow

- silkworm/node/db/access_layer.cpp
To support memory overlays we need to create cursors from db transaction so that we access the PooledCursor instance through the correct interface specialisation.
> db: create cursors polymorphically

- .circleci/config.yml
Run the format checks once before the other PR jobs.
> CI: refactor lint job

- cmake/cmake_format.cmake
- third_party/CMakeLists.txt
see:
https://github.com/bitcoin-core/secp256k1/commit/1f233b3fa05eb29a744487e0682d925055fb0d4c
https://github.com/bitcoin-core/secp256k1/commit/79f1f7a4f123765cf07be92ae894d882c5845191
> cmake: secp256k1 - remove obsolete flags

- silkworm/node/db/memory_mutation_cursor.cpp
- silkworm/node/db/memory_mutation_cursor_test.cpp
node: use key_lowerbound instead of key_exact in MemoryMutationCursor::find internal searches
> node: fix search logic in memory mutation cursor find

- cmd/state-transition/state_transition.cpp
> cmd: add Access List in State Transition

- cmd/state-transition/state_transition.cpp
> cmd: add cleanup in State Transition

- silkworm/silkrpc/core/call_many.cpp
Added timeout parameter management in eth_callMany API
> rpcdaemon: handle timeout in eth_callMany

- silkworm/core/execution/evm.cpp
- silkworm/core/trie/node.cpp
- silkworm/core/trie/node_test.cpp
- silkworm/infra/common/binary_search_test.cpp
- silkworm/infra/common/memory_mapped_file_benchmark.cpp
- silkworm/node/db/bitmap_test.cpp
- silkworm/silkrpc/ethdb/cbor.cpp
> Use C++20 safe integral comparisons

- silkworm/silkrpc/core/blocks.cpp
- silkworm/silkrpc/core/blocks_test.cpp
- silkworm/silkrpc/json/types.hpp
- silkworm/silkrpc/json/types_test.cpp
remove duplicated function declaration
> rpcdaemon: improve block number lookup

- tests/integration/goerly/eth_callMany/test_01.json
- tests/integration/goerly/eth_callMany/test_02.json
- tests/integration/goerly/eth_callMany/test_03.json
- tests/integration/goerly/eth_callMany/test_04.json
- tests/integration/goerly/eth_callMany/test_05.json
- tests/integration/goerly/eth_callMany/test_06.json
- tests/integration/goerly/eth_callMany/test_07.json
Added timeout parameter to eth_callMany integration tests
> rpcdaemon: timeout parameter in eth_callMany integration tests

- .circleci/config.yml
- .github/workflows/macOS.yml
- .github/workflows/windows.yml
- CMakeLists.txt
- Makefile
- cmake/get_all_targets.cmake
- cmake/run_unit_tests.cmake
- cmake/run_unit_tests.sh
Build with:
--target all_unit_tests
Try:
make test
> CI: all unit tests meta target and scripts

- silkworm/core/types/transaction.cpp
- silkworm/core/types/transaction.hpp
- silkworm/core/types/transaction_test.cpp
- silkworm/node/db/access_layer.cpp
- silkworm/node/db/access_layer.hpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
- silkworm/node/snapshot/snapshot_test.cpp
node: add missing checks to avoid MPHF false positives
core: add hash method in Transaction
> node: add support for snapshots in db access layer [WIP]

- silkworm/core/types/hash.hpp
- silkworm/node/db/access_layer.cpp
- silkworm/node/db/access_layer.hpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
- silkworm/node/snapshot/sync.cpp
- silkworm/node/stagedsync/forks/main_chain.cpp
- silkworm/silkrpc/core/rawdb/chain.cpp
node: read sequence of txs from tx snapshot
node: remove unused access layer APIs
rpcdaemon: fix read block for missing system txs
> node: more support for snapshots in db access layer

- cmd/dev/snapshots.cpp
- silkworm/node/snapshot/index.cpp
- silkworm/node/snapshot/repository.cpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
- silkworm/node/snapshot/snapshot_test.cpp
- silkworm/node/test/snapshots.hpp
node: add invariant checks in header snapshot index
node: improve checks in snapshot repository
node: fix invariant check in header snapshot
node: add unit test for header snapshot
cmd: improve snapshots tool
> node: expose transaction RLP data from snapshots

- cmd/dev/snapshots.cpp
- silkworm/node/db/access_layer.cpp
- silkworm/node/db/access_layer.hpp
- silkworm/node/db/access_layer_test.cpp
- silkworm/node/node.cpp
- silkworm/node/snapshot/index.cpp
- silkworm/node/snapshot/repository.hpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
- silkworm/node/snapshot/sync.cpp
- silkworm/node/snapshot/sync.hpp
- silkworm/node/snapshot/sync_test.cpp
- silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
node: fix txn decoding in transaction snapshot
node: extract snapshot repository out of snapshot sync
node: set snapshot repository in node facade
> node: expose RLP-encoded transactions from data model

- silkworm/silkrpc/commands/debug_api.cpp
- silkworm/silkrpc/core/evm_debug.cpp
- silkworm/silkrpc/core/evm_debug.hpp
- silkworm/silkrpc/core/evm_debug_test.cpp
- silkworm/silkrpc/test/mock_block_cache.hpp
Review of DebugExecutor  to add trace_call_many method
> rpcdaemon: DebugExecutor refactoring

- silkworm/sentry/discovery/disc_v4/CMakeLists.txt
- silkworm/sentry/discovery/disc_v4/disc_v4_common/message_expiration.cpp
- silkworm/sentry/discovery/disc_v4/disc_v4_common/message_expiration.hpp
- silkworm/sentry/discovery/disc_v4/discovery.cpp
- silkworm/sentry/discovery/disc_v4/discovery.hpp
- silkworm/sentry/discovery/disc_v4/find/find_node_message.cpp
- silkworm/sentry/discovery/disc_v4/find/message_handler.hpp
- silkworm/sentry/discovery/disc_v4/find/message_sender.hpp
- silkworm/sentry/discovery/disc_v4/find/neighbors_message.cpp
- silkworm/sentry/discovery/disc_v4/find/neighbors_message.hpp
- silkworm/sentry/discovery/disc_v4/message_handler.hpp
- silkworm/sentry/discovery/disc_v4/message_sender.hpp
- silkworm/sentry/discovery/disc_v4/ping/message_handler.hpp
- silkworm/sentry/discovery/disc_v4/ping/message_sender.hpp
- silkworm/sentry/discovery/disc_v4/ping/ping_handler.cpp
- silkworm/sentry/discovery/disc_v4/ping/ping_handler.hpp
- silkworm/sentry/discovery/disc_v4/ping/ping_message.cpp
- silkworm/sentry/discovery/disc_v4/ping/pong_message.cpp
- silkworm/sentry/discovery/disc_v4/ping/pong_message.hpp
- silkworm/sentry/discovery/disc_v4/server.cpp
- silkworm/sentry/discovery/disc_v4/server.hpp
- silkworm/sentry/discovery/discovery.cpp
- silkworm/sentry/discovery/discovery.hpp
- silkworm/sentry/nat/stun_ip_resolver.cpp
- silkworm/sentry/sentry.cpp
- silkworm/sentry/settings.hpp
* UDP server
* message sender and handler interfaces
* pong reply
> sentry: disc v4 server

- silkworm/core/types/hash.hpp
- silkworm/core/types/hash_test.cpp
- silkworm/sync/packets/packet_coding_test.cpp
core: remove unused Hash-related functions
> core: fix Hash::from_hex

- silkworm/sync/block_exchange.cpp
- silkworm/sync/block_exchange.hpp
- silkworm/sync/sync_pos.cpp
sync: add logs in PoS sync Engine API implementation
> sync: move block when passing new target to block exchange

- silkworm/infra/common/memory_mapped_file.cpp
It is better not to specify a size in the CreateFileMapping, this avoids failures for ERROR_ACCESS_DENIED in the MapViewOfFile as stated here: https://stackoverflow.com/questions/16027268/why-does-mapviewoffile-fail-with-error-access-denied
> snapshot: fix MemoryMappedFile on Windows

- silkworm/infra/common/ensure.hpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot_test.cpp
node: demote DEBUG logs to TRACE level
> node: add range check in header snapshot access by number

- cmd/dev/snapshots.cpp
- silkworm/core/common/assert.cpp
cmd: refactor command-line parameters in snapshots tool
core: add missing newline in assertion print
> cmd: add open_index command to snapshots tool

- cmd/dev/snapshots.cpp
- silkworm/node/snapshot/index_test.cpp
- silkworm/node/snapshot/path.cpp
- silkworm/node/snapshot/repository.cpp
- silkworm/node/snapshot/repository.hpp
- silkworm/node/snapshot/repository_test.cpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
- silkworm/node/snapshot/snapshot_test.cpp
- silkworm/node/test/snapshots.hpp
snapshots: add block height check in body lookup
snapshots: add check on block format in snapshot file name
snapshots: improvements in snapshot repository
snapshots: improve unit tests
cmd: add lookup_body and lookup_transaction subcommands in snapshots tool + improvements
> node: add hash prefix check in lookup from snapshots

- cmd/README.md
- silkworm/infra/common/ensure.hpp
- silkworm/node/snapshot/index_test.cpp
- silkworm/silkrpc/commands/eth_api.cpp
- silkworm/silkrpc/daemon.cpp
- silkworm/silkrpc/daemon.hpp
- silkworm/sync/sync.cpp
rpcdaemon: fix lifetime issue in Backend service replacement
infra: add pre-/post-condition facilities
node: exclude unit test from Windows build
cmd: update README for snapshots tool
> rpcdaemon: make eth_getBlockByNumber and eth_call work with snapshots

- silkworm/node/db/access_layer.cpp
- silkworm/node/db/access_layer_test.cpp
- silkworm/node/stagedsync/execution_engine_test.cpp
- silkworm/node/stagedsync/stages/_test.cpp
- silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
node: add missing withdrawals in block body
> node: fix block body txn counters in access layer

- cmd/common/db_checklist.cpp
- cmd/silkworm.cpp
- silkworm/infra/concurrency/context_pool.hpp
- silkworm/infra/grpc/client/client_context_pool.cpp
- silkworm/infra/grpc/server/server.hpp
- silkworm/infra/grpc/server/server_context_pool.cpp
- silkworm/node/backend/remote/backend_kv_server.cpp
- silkworm/node/bittorrent/client.cpp
- silkworm/node/snapshot/repository.cpp
- silkworm/node/snapshot/sync.cpp
- silkworm/sentry/message_receiver.cpp
- silkworm/sentry/peer_manager_api.cpp
- silkworm/sync/block_exchange.cpp
* use level methods instead of a plain log::Message()
* demote context pool messages to TRACE
* demote spammy messages to TRACE
* demote developer-oriented messages to DEBUG
> logging: adjust log levels

- .circleci/config.yml
- cmake/compiler_settings.cmake
ci: remove position-independent code flag
> build: enable position-independent code for all builds

- silkworm/silkrpc/commands/erigon_api.cpp
- silkworm/silkrpc/commands/erigon_api.hpp
Added the following erigon empty API:
- erigon_getBalanceChangesInBlock
- erigon_getBalanceChangesInBlock
- erigon_cacheCheck
- erigon_getLatestLogs
> rpcdaemon: add 4 missing erigon API (empty implementation)

- cmd/api/CMakeLists.txt
- cmd/api/execute.cpp
- silkworm/api/silkworm_api.cpp
- silkworm/node/db/mdbx.hpp
- silkworm/node/huffman/decompressor.hpp
- silkworm/node/recsplit/rec_split.hpp
- silkworm/node/snapshot/snapshot.cpp
- silkworm/node/snapshot/snapshot.hpp
cmd: open collect and pass all snapshots in C API execute tool
api, node: move unmanaged ROTxn/RWTxn implementations to access layer
node: access memory-mapped file address and size in snapshot segment and index
> cmd: add command-line parameters in C API execute tool

- cmd/dev/toolbox.cpp
- silkworm/node/db/genesis.cpp
- silkworm/node/db/genesis.hpp
node: expose initialization function for genesis allocations
> cmd: reset PlainState in toolbox by clearing and reapplying genesis allocations

- silkworm/node/db/tables.hpp
- silkworm/node/stagedsync/stages/stage_senders.cpp
- silkworm/node/stagedsync/stages/stage_senders.hpp
node: avoid unnecessary hash copies in stage Senders
node: add extra check for processed blocks in stage Senders
> node: fix stage Senders after snapshot support (PR #1264)

- cmd/dev/toolbox.cpp
- silkworm/node/db/util.cpp
- silkworm/node/db/util.hpp
node: add utility to extract block_number from mdbx key
> cmd: add blocks and unwind commands in toolbox

- silkworm/sentry/nat/stun_ip_resolver.cpp
Happens when there's no network.
> sentry: improve STUN host not found error message

- silkworm/infra/common/asio_timer.hpp
- silkworm/infra/concurrency/parallel_group_test.cpp
- silkworm/infra/concurrency/task_group_test.cpp
- silkworm/infra/concurrency/timeout.cpp
- silkworm/infra/concurrency/timeout_test.cpp
- silkworm/infra/grpc/server/call.hpp
- silkworm/node/backend/remote/grpc/kv_calls.hpp
- silkworm/sentry/common/sleep.cpp
- silkworm/silkrpc/ethdb/kv/state_changes_stream.cpp
- silkworm/silkrpc/ethdb/kv/state_changes_stream.hpp
- silkworm/silkrpc/ethdb/kv/state_changes_stream_test.cpp
https://stackoverflow.com/questions/13263277/difference-between-stdsystem-clock-and-stdsteady-clock
> sentry, infra, silkrpc: use chrono-based timers

- cmd/dev/toolbox.cpp
cmd: changes in the `toolbox` command-line utility
- add `blocks` command (for both canonical and non-canonical)
- add full-pipeline `unwind` command (replacing stage-unwind)
- rename existing `blocks` command as `canonical_blocks`
> cmd: blocks and unwind commands in toolbox command-line utility

- .circleci/config.yml
CI jobs now run roughy 2x faster
> CI: bump resource class

- .gitignore
- docs/JSON-RPC-API.md
- silkworm/silkrpc/commands/erigon_api.cpp
- silkworm/silkrpc/commands/eth_api.cpp
- silkworm/silkrpc/commands/eth_api.hpp
- silkworm/silkrpc/core/logs_walker.cpp
- silkworm/silkrpc/core/logs_walker.hpp
- silkworm/silkrpc/json/filter.cpp
- silkworm/silkrpc/json/filter.hpp
- silkworm/silkrpc/json/filter_test.cpp
- silkworm/silkrpc/json/log.cpp
- silkworm/silkrpc/types/filter.cpp
- silkworm/silkrpc/types/filter.hpp
- silkworm/silkrpc/types/filter_test.cpp
- silkworm/silkrpc/types/log.hpp
- tests/integration/README.md
- tests/integration/goerly/erigon_getLatestLogs/test_01.json
- tests/integration/goerly/erigon_getLatestLogs/test_02.json
- tests/integration/goerly/erigon_getLatestLogs/test_03.json
- tests/integration/goerly/erigon_getLatestLogs/test_04.json
- tests/integration/goerly/erigon_getLatestLogs/test_05.json
- tests/integration/goerly/erigon_getLatestLogs/test_06.json
- tests/integration/goerly/erigon_getLatestLogs/test_07.json
- tests/integration/goerly/erigon_getLatestLogs/test_08.json
- tests/integration/goerly/erigon_getLatestLogs/test_09.json
- tests/integration/goerly/erigon_getLatestLogs/test_10.json
- tests/integration/goerly/erigon_getLatestLogs/test_11.json
- tests/integration/run_tests.py
Implementation for erigon_getLatestLogs
> rpcdaemon:  erigon_getLatestLogs

- silkworm/node/db/stages.hpp
- silkworm/node/db/tables.hpp
- silkworm/node/stagedsync/stages/stage_blockhashes.cpp
- silkworm/node/stagedsync/stages/stage_bodies.cpp
- silkworm/node/stagedsync/stages/stage_execution.cpp
- silkworm/node/stagedsync/stages/stage_finish.cpp
- silkworm/node/stagedsync/stages/stage_hashstate.cpp
- silkworm/node/stagedsync/stages/stage_headers.cpp
- silkworm/node/stagedsync/stages/stage_history_index.cpp
- silkworm/node/stagedsync/stages/stage_interhashes.cpp
- silkworm/node/stagedsync/stages/stage_senders.cpp
node: add sanity checks in HashState stage
node: decrease staged sync logging threshold
> node: improve staged sync logging

- cmd/test/ethereum.cpp
- silkworm/core/common/test_util.hpp
- silkworm/core/execution/evm.hpp
- silkworm/core/execution/processor.cpp
- silkworm/core/protocol/base_rule_set.cpp
- silkworm/core/protocol/blockchain.cpp
- silkworm/core/protocol/ethash_rule_set.cpp
- silkworm/core/protocol/ethash_rule_set.hpp
- silkworm/core/protocol/merge_rule_set.cpp
- silkworm/core/protocol/merge_rule_set.hpp
- silkworm/core/protocol/merge_rule_set_test.cpp
- silkworm/core/protocol/param.hpp
- silkworm/core/protocol/rule_set.hpp
- silkworm/core/protocol/validation.cpp
- silkworm/core/protocol/validation.hpp
- silkworm/core/types/block.cpp
- silkworm/core/types/block.hpp
- silkworm/core/types/block_test.cpp
- silkworm/core/types/transaction.cpp
- silkworm/core/types/transaction.hpp
- silkworm/silkrpc/core/fee_history_oracle.cpp
- silkworm/sync/internals/header_chain_plus_exec_test.cpp
Implement https://eips.ethereum.org/EIPS/eip-4788
> core: EIP-4788: Beacon block root in the EVM

- silkworm/node/db/mdbx.cpp
- silkworm/node/db/memory_mutation_cursor.cpp
- silkworm/node/db/memory_mutation_cursor_test.cpp
node: fix current value in memory mutation seek
> node: lower_bound and move implementation in memory mutation

- silkworm/silkrpc/http/request_handler.cpp
> rpcademon: fix startup crash when CORS domain option is not set

- silkworm/node/stagedsync/stages/stage_log_index.cpp
- silkworm/node/stagedsync/stages/stage_log_index.hpp
- silkworm/node/types/log_cbor.cpp
- silkworm/node/types/log_cbor.hpp
- silkworm/node/types/log_cbor_test.cpp
> node: skip non-address and non-topic data in LogIndex stage

- cmd/dev/CMakeLists.txt
- cmd/dev/README.md
- cmd/dev/check_log_indices.cpp
- cmd/dev/check_senders.cpp
- silkworm/node/db/bitmap.cpp
- silkworm/node/db/bitmap.hpp
- silkworm/node/db/util.cpp
- silkworm/node/db/util.hpp
> cmd: add tool check_log_indices

- silkworm/node/db/buffer_test.cpp
- silkworm/node/snapshot/repository.cpp
- silkworm/node/snapshot/repository.hpp
- silkworm/node/snapshot/repository_test.cpp
node: fix failing unit tests
node: add missing unit test for state changes
> node: fix snapshot max block after index building

- tests/integration/run_tests.py
tests: refactor integration test runner
> tests: add custom port in integration test runner

- silkworm/infra/concurrency/timeout.cpp
- silkworm/infra/concurrency/timeout.hpp
- silkworm/sentry/discovery/discovery.cpp
- silkworm/sentry/discovery/node_db/serial_node_db.hpp
https://github.com/erigontech/silkworm/issues/1530
> sentry: co_spawn_sw crash in SerialNodeDb (#1530) - workaround

- cmd/common/settings.hpp
- cmd/silkworm.cpp
cmd: change default value for setting forcing PoW sync
> cmd: add termination handler to silkworm executable

- cmd/dev/check_changes.cpp
- cmd/dev/toolbox.cpp
- silkworm/node/db/util.hpp
cmd: improve mismatch dump in check_changes
cmd: fix logging in toolbox
> cmd: add snapshots in check_changes tool

- silkworm/silkrpc/commands/parity_api.cpp
`third_party/execution-apis` updated to the latest version.
`parity_api.cpp` implements `eth_getBlockReceipts`, updated to match tests logic
> rpcdaemon: update execution api tests

- silkworm/api/silkworm_api.cpp
- silkworm/api/silkworm_api.h
- silkworm/infra/common/log.hpp
- silkworm/infra/common/log_test.cpp
api: add version log
infra: restore UTC as default timezone for logs
> api: add progress info to periodic execution log

- cmd/api/CMakeLists.txt
- cmd/api/execute.cpp
- silkworm/api/CMakeLists.txt
- silkworm/api/silkworm_api.cpp
- silkworm/api/silkworm_api.h
> api: add rpcdaemon start/stop C API with default options

- cmd/common/snapshot_options.cpp
- silkworm/node/bittorrent/client.cpp
- silkworm/node/bittorrent/client_test.cpp
- silkworm/node/bittorrent/settings.hpp
node: add BitTorrent client flag to emit warnings for error alerts
node: cleanup BitTorrent client settings
> cmd: fix BitTorrent command-line options

- silkworm/infra/grpc/common/conversion.cpp
Replaced new with unique_ptr and release to combat potential memory leakage as Issue suggested.
> Replace new with unique_ptr and release #1459

- silkworm/infra/common/environment.cpp
- silkworm/infra/common/environment.hpp
- silkworm/node/stagedsync/execution_pipeline.cpp
- silkworm/node/stagedsync/forks/main_chain.cpp
- silkworm/node/stagedsync/stages/stage_hashstate.cpp
- silkworm/node/stagedsync/stages/stage_interhashes.cpp
node: fix log traces in IntermediateHashes and HashState stages
> infra, node: add support for START_AT_STAGE env variable

- cmd/api/execute.cpp
api: refactor C-like path creation
> cmd: fix RPCDaemon start in execute tool

- cmd/dev/scan_txs.cpp
- silkworm/node/stagedsync/forks/fork.cpp
> fix: minor typos

- cmd/test/ethereum.cpp
Upgrade to [Tests update 13 Cancun tests](https://github.com/ethereum/tests/releases/tag/v13)
> third_party: upgrade ethereum/tests to v13

- cmd/api/execute.cpp
Avoid specifying the full path to the snapshot for which you want to build an index: the snapshot name is sufficient, provided that the snapshot must be in the repo specified by --datadir.
> cmd: simplify command line of execute tool to build indexes

- cmd/api/execute.cpp
This PR adapts the code of the execution cmd line tool to the changes recently introduced to the `silkworm_init()` method.
@battlmonstr I made the minimal changes but I found that the definition of data_dir_path inside SilkwormSettings forces us to write convoluted code and introduce a minimal path size for which I didn't find reasons in Silkworm, maybe they are in Erigon?
> cmd: fix init in block execution tool

- silkworm/silkrpc/http/request_handler.cpp
- silkworm/silkrpc/http/request_handler.hpp
Fix for unsolicited wrong response for API using JSON stream approach
> rpcdaemon: avoid unsolicited wrong HTTP reply in JSON streaming

- cmd/dev/CMakeLists.txt
- cmd/dev/db_toolbox.cpp
cmd: rename toolbox executable as db_toolbox
> cmd: add option to compare table in db toolbox

- silkworm/silkrpc/commands/admin_api.cpp
- silkworm/silkrpc/commands/debug_api.cpp
- silkworm/silkrpc/commands/engine_api.cpp
- silkworm/silkrpc/commands/erigon_api.cpp
- silkworm/silkrpc/commands/eth_api.cpp
- silkworm/silkrpc/commands/net_api.cpp
- silkworm/silkrpc/commands/ots_api.cpp
- silkworm/silkrpc/commands/parity_api.cpp
- silkworm/silkrpc/commands/trace_api.cpp
- silkworm/silkrpc/commands/txpool_api.cpp
- silkworm/silkrpc/commands/web3_api.cpp
- silkworm/silkrpc/http/request_handler.cpp
- silkworm/silkrpc/http/request_handler.hpp
- silkworm/silkrpc/json/block.cpp
- silkworm/silkrpc/json/block.hpp
- silkworm/silkrpc/json/call.cpp
- silkworm/silkrpc/json/call.hpp
- silkworm/silkrpc/json/glaze.cpp
- silkworm/silkrpc/json/glaze.hpp
- silkworm/silkrpc/json/log.cpp
- silkworm/silkrpc/json/log.hpp
- silkworm/silkrpc/json/types.cpp
- silkworm/silkrpc/json/types.hpp
- silkworm/silkrpc/json/types_test.cpp
RPC request ID management in compliance with the JSON RPC 2.0 specifications
> rpcdaemon: RPC request ID management

- silkworm/core/common/math.hpp
- silkworm/core/common/math_test.cpp
- silkworm/node/recsplit/rec_split.hpp
> rec_split: use constexpr int_ceil

- conanfile.py
We have to build boost from source, because we need to change asio_no_deprecated option. In this case we can disable building unused components. There was no gain in doing it previously, because disabling unused components lead to building from source the used ones.
> cmake: disable building unused boost components

- cmd/dev/db_toolbox.cpp
This PR modifies the `compare` command in `db_toolbox` to put the MDBX b-tree depth comparison under the `check_pages` flag, now renamed as `check_layout`.
This choice is more coherent with the default comparison behaviour in `compare`, because any difference in such metric is not directly related to the application-level data stored in the database (it is indeed influenced by *how* such data has been inserted/updated/deleted).
> cmd: put tree depth under check_layout flag in db_toolbox

- silkworm/core/common/util.cpp
- silkworm/rpc/core/evm_debug.cpp
- silkworm/rpc/core/evm_debug_test.cpp
- silkworm/rpc/http/request_handler.cpp
- silkworm/rpc/json/stream.cpp
- silkworm/rpc/json/stream.hpp
- silkworm/rpc/json/stream_test.cpp
- silkworm/rpc/types/writer.cpp
- silkworm/rpc/types/writer.hpp
- silkworm/rpc/types/writer_test.cpp
> rpcdaemon: async write using json stream

- third_party/evmone/CMakeLists.txt
see https://github.com/ethereum/evmone/releases/tag/v0.11.0
> third_party: upgrade evmone to v0.11.0

- silkworm/rpc/commands/erigon_api.cpp
See also https://github.com/ledgerwatch/erigon/pull/6664
> rpcdaemon: find min block after binary search in erigon_getBlockByTimestamp

- silkworm/rpc/http/json_rpc_validator.cpp
- silkworm/rpc/http/json_rpc_validator.hpp
rpcdaemon: some refactoring in JsonRpcValidator
> rpcdaemon: fix clang-tidy after PR 1739

- silkworm/rpc/json/stream.cpp
- silkworm/rpc/json/stream.hpp
Fix for wrong chunk sequence in streaming
> rpcdaemon: fix wrong chunk sequence in streaming

- silkworm/rpc/http/request_handler.cpp
- silkworm/rpc/json/stream.cpp
- silkworm/rpc/json/stream.hpp
- silkworm/rpc/json/stream_test.cpp
rpcdaemon: fix close in JSON streaming
> rpcdaemon: fix async loop in JSON streaming

- silkworm/rpc/commands/trace_api.cpp
- silkworm/rpc/core/evm_trace.cpp
- silkworm/rpc/core/evm_trace.hpp
In trace_filter stream pointer changed to stream reference
> rpcdaemon: trace_filter use stream reference

- silkworm/rpc/http/request_handler.cpp
Exception handling in requests using json stream
> rpcdaemon: json streamed request exception handling

- docs/CONTRIBUTING.md
docs: fixes in contribution guide
> docs: how to develop and test C API in contribution guide

- silkworm/capi/silkworm.cpp
- silkworm/infra/test_util/temporary_file.hpp
- silkworm/node/snapshots/index.cpp
- silkworm/node/snapshots/index_test.cpp
- silkworm/node/snapshots/repository.cpp
- silkworm/node/snapshots/seg/decompressor.cpp
- silkworm/node/snapshots/sync.cpp
This PR contains also the following changes:
- proper fix for one of the issues touched by #1793
- demote some logs to TRACE severity
> node: fix error handling in snapshot index build

- silkworm/rpc/core/call_many.cpp
Erigon compatibility flag management for eth_callMany API
> rpcdaemon: Erigon compatibility in eth_callMany API

- cmd/test/fuzzer_diagnostics.cpp
> ci: fix fuzzer diagnostics build after PR 1830

- silkworm/rpc/http/connection.cpp
- silkworm/rpc/http/connection.hpp
- silkworm/rpc/json_rpc/request_handler.cpp
> rpcdaemon: move HTTP body termination char to connection

- cmd/common/common.cpp
- cmd/dev/check_log_indices.cpp
- cmd/dev/snapshots.cpp
- silkworm/infra/common/memory_mapped_file.cpp
- silkworm/infra/concurrency/private_service.hpp
- silkworm/infra/concurrency/shared_service.hpp
- silkworm/node/db/memory_mutation_cursor.cpp
- silkworm/node/snapshots/repository.cpp
- silkworm/node/snapshots/seg/decompressor.cpp
- silkworm/node/snapshots/snapshot.cpp
- silkworm/node/snapshots/snapshot_decompressor_test.cpp
- silkworm/node/snapshots/snapshot_test.cpp
- silkworm/node/snapshots/sync.cpp
- silkworm/node/stagedsync/execution_engine.cpp
- silkworm/node/stagedsync/execution_engine_test.cpp
- silkworm/node/stagedsync/forks/main_chain.cpp
- silkworm/rpc/commands/engine_api.cpp
- silkworm/rpc/daemon.cpp
- silkworm/rpc/ethbackend/remote_backend.cpp
- silkworm/rpc/http/jwt.cpp
- silkworm/rpc/json/execution_payload.cpp
- silkworm/rpc/json/transaction.cpp
- silkworm/sync/internals/header_chain.cpp
> fmt: and/or/not -> &&/||/!

- silkworm/sentry/common/error.hpp
- silkworm/sentry/rlpx/auth/auth_ack_message.cpp
- silkworm/sentry/rlpx/auth/auth_message.cpp
- silkworm/sentry/rlpx/auth/auth_message_error.hpp
- silkworm/sentry/rlpx/auth/ecies_cipher.cpp
- silkworm/sentry/rlpx/auth/ecies_cipher_error.hpp
- silkworm/sentry/rlpx/peer.cpp
Demoted the error to DEBUG level with a more detailed message.
> sentry: invalid MAC error handling

- silkworm/node/snapshots/seg/decompressor.cpp
see https://github.com/ledgerwatch/erigon/pull/9530
> seg: avoid stackoverflow in PatternTable::build_condensed

- silkworm/rpc/core/evm_executor.cpp
- silkworm/rpc/core/evm_executor_test.cpp
- silkworm/rpc/core/evm_trace_test.cpp
Some fix on error messages for eth_callMany API
> rpcdaemon: error messages for eth_callMany API

- cmd/dev/snapshots.cpp
- silkworm/snapshots/rec_split/rec_split.hpp
cmd: fix ordinal lookup for transactions in open_index
This PR introduces initial support for `less false-positives` feature in RecSplit-based index: https://github.com/ledgerwatch/erigon/pull/9515
We do not use the associated existence filter yet (next PR): we just read the features flag from the index file and if less false-positives feature is enabled we also read and store the existence filter. This makes our RecSplit indices compatible with Erigon ones again.
> snapshots: read existence filter in recsplit index

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/debug_api.cpp
- silkworm/rpc/core/evm_executor.cpp
Fix in balance evaluation for debug_accountAt
> rpcdaemon: fix account state in debug_accountAt

- cmake/compiler_warnings.cmake
https://stackoverflow.com/questions/77164140/
```
ld: warning: ignoring duplicate libraries:
'-lc++'
'-lc++abi'
'/Users/x/.conan/data/abseil/.../lib/libabsl_bad_optional_access.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_bad_variant_access.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_base.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_city.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_civil_time.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_cord.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_cord_internal.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_cordz_functions.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_cordz_handle.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_cordz_info.a'
'/Users/x/.conan/data/abseil/.../lib/libabsl_debugging_internal.a' …
```
> cmake: no_warn_duplicate_libraries

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/core/evm_trace.cpp
Fixed error messages in TraceTracer for invalid opcode and jump destination
> rcpdaemon: error messages in TraceTracer

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/core/evm_trace.cpp
Fixed author value in reward action
> rpcdaemon: author value in trace_block reward action

- silkworm/rpc/ethdb/kv/state_changes_stream_test.cpp
> rpcdaemon: fix warning in StateChanges stream unit test

- silkworm/rpc/commands/trace_api.cpp
Add compatibility flag in trace_get API
> rpcdaemon: compatibility flag in trace_get API

- silkworm/rpc/core/evm_trace.cpp
> rpcdaemon: fix crash in trace_replay* API

- silkworm/rpc/core/evm_trace.cpp
- silkworm/rpc/core/evm_trace.hpp
- silkworm/rpc/core/evm_trace_test.cpp
Fix on undefined instruction error message for TraceTracer
> rpcdaemon: undefined instruction error message in TraceTracer 

- .github/workflows/rpc-integration-tests.yml
- silkworm/core/execution/evm.cpp
- silkworm/core/execution/evm.hpp
- silkworm/rpc/core/evm_trace.cpp
- silkworm/rpc/core/evm_trace.hpp
Fix on create failure trace
To be merged after [rpc-test PR](https://github.com/erigontech/rpc-tests/pull/163) merge and tag
> rpcdaemon: fix on create failure trace

- silkworm/sync/internals/header_retrieval.cpp
- silkworm/sync/internals/header_retrieval.hpp
- silkworm/sync/sentry_client.cpp
> sync: dump malformed received p2p messages in debug

- silkworm/rpc/common/util.cpp
- silkworm/rpc/common/util.hpp
- silkworm/rpc/common/util_test.cpp
- silkworm/rpc/core/evm_debug.cpp
- silkworm/rpc/core/evm_trace.cpp
- silkworm/rpc/core/evm_trace.hpp
- silkworm/rpc/core/evm_trace_test.cpp
Refactored get_opcode_name function used by trace_* and debug_* APIs
> rpcdaemon: get_opcode_name function refactoring

- silkworm/rpc/commands/ots_api.cpp
- silkworm/rpc/core/evm_executor.cpp
- silkworm/rpc/core/evm_executor.hpp
- silkworm/rpc/core/evm_executor_test.cpp
> rpcdaemon: fix ots_getContractCreator

- silkworm/rpc/commands/erigon_api.cpp
- silkworm/rpc/core/rawdb/chain.cpp
- silkworm/rpc/core/rawdb/chain.hpp
- silkworm/rpc/core/rawdb/chain_test.cpp
- silkworm/rpc/json/types_test.cpp
- silkworm/rpc/storage/chain_storage.hpp
- silkworm/rpc/storage/local_chain_storage.cpp
- silkworm/rpc/storage/local_chain_storage.hpp
- silkworm/rpc/storage/remote_chain_storage.cpp
- silkworm/rpc/storage/remote_chain_storage.hpp
- silkworm/rpc/storage/remote_chain_storage_test.cpp
- silkworm/rpc/types/chain_config.cpp
- silkworm/rpc/types/chain_config.hpp
- silkworm/rpc/types/chain_config_test.cpp
rpcdaemon: remove unused read_chain_id
> rpcdaemon: move read_chain_config to chain storage

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/core/evm_trace.cpp
- silkworm/rpc/core/evm_trace.hpp
Added SuicideAction to trace SELFDESTRUCT opcode
> rpcdaemon: SuicideAction implementation in trace API

- .clang-tidy
- silkworm/db/remote/kv/grpc/server/kv_calls.cpp
- silkworm/db/remote/kv/grpc/server/kv_server.cpp
- silkworm/node/execution/grpc/server/server.cpp
- silkworm/node/remote/ethbackend/grpc/server/backend_server.cpp
- silkworm/rpc/commands/erigon_api.cpp
- silkworm/rpc/core/estimate_gas_oracle_test.cpp
- silkworm/rpc/core/receipts_test.cpp
- silkworm/sync/sync_pos_test.cpp
it only gives false positives noise...
> tidy: disable cppcoreguidelines-avoid-capturing-lambda-coroutines

- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/commands/eth_api_test.cpp
- silkworm/rpc/common/util.cpp
- silkworm/rpc/common/util_test.cpp
> rpcademon: fix is_replay_protected and parse raw transaction

- cmd/dev/snapshots.cpp
- silkworm/db/bodies/body_snapshot.cpp
- silkworm/db/bodies/body_snapshot.hpp
- silkworm/db/headers/header_snapshot.cpp
- silkworm/db/headers/header_snapshot.hpp
- silkworm/db/snapshot_recompress.cpp
- silkworm/db/snapshot_recompress.hpp
- silkworm/db/snapshots/seg/compressor.hpp
- silkworm/db/snapshots/snapshot_word_serializer.hpp
- silkworm/db/snapshots/snapshot_writer.cpp
- silkworm/db/snapshots/snapshot_writer.hpp
- silkworm/db/transactions/txn_snapshot_word_serializer.cpp
- silkworm/db/transactions/txn_snapshot_word_serializer.hpp
Snapshot word serialization and writers for the E2 snapshot file formats.
cmd/dev/snapshots recompress command for testing.
> snapshots: SnapshotWriter

- .github/workflows/rpc-integration-tests.yml
Temporarily disable tests 6 and 7 due to #2150
> integration test: temporary disable debug_storageRangeAt test 6 and 7

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/core/evm_debug.cpp
- silkworm/rpc/core/evm_debug.hpp
Fix for gas cost in debug_trace API family
> rpcdaemon: fix debug/trace API family gas cost

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/core/storage_walker.cpp
> rpcdaemon: fix debug_storageRangeAt

- silkworm/rpc/core/evm_debug.cpp
- silkworm/rpc/core/evm_debug.hpp
Refactored data structure to fix call gas
> rpcdaemon: renamed fix call gas data structure

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/core/evm_debug.cpp
- silkworm/rpc/core/evm_trace.cpp
- silkworm/rpc/core/evm_trace.hpp
Fix for gas cost in trace API family
> rpcdaemon: fix trace_* API family gas cost

- silkworm/rpc/json_rpc/specification.json
Updated json specification and embedded content into cpp file.
> rpcdaemon: debug account range - updated spec

- cmd/dev/snapshots.cpp
- silkworm/db/freezer.cpp
- silkworm/db/freezer.hpp
- silkworm/db/snapshot_bundle_factory_impl.cpp
- silkworm/db/snapshot_bundle_factory_impl.hpp
- silkworm/db/snapshot_merger.cpp
- silkworm/db/snapshot_merger.hpp
- silkworm/db/snapshots/path.cpp
- silkworm/db/snapshots/path.hpp
- silkworm/db/snapshots/repository.cpp
- silkworm/db/snapshots/repository.hpp
- silkworm/db/snapshots/snapshot_bundle.cpp
- silkworm/db/snapshots/snapshot_bundle.hpp
- silkworm/db/snapshots/snapshot_bundle_factory.hpp
- silkworm/infra/common/filesystem.cpp
- silkworm/infra/common/filesystem.hpp
- silkworm/node/node.cpp
Merge 10 1K snapshots into 10K, then 10 10K into 100K.
> db: SnapshotMerger

- silkworm/core/common/base.hpp
- silkworm/db/blocks/bodies/body_snapshot_freezer.cpp
- silkworm/db/blocks/headers/header_snapshot_freezer.cpp
- silkworm/db/freezer.cpp
- silkworm/db/snapshot_bundle_factory_impl.cpp
- silkworm/db/snapshot_freezer.hpp
- silkworm/db/snapshot_merger.cpp
- silkworm/db/snapshots/snapshot_bundle.hpp
- silkworm/db/transactions/txn_snapshot_freezer.cpp
- silkworm/node/execution/grpc/client/endpoint/range.cpp
> base: BlockNumRange struct

- cmd/common/snapshot_options.cpp
- cmd/dev/db_toolbox.cpp
- cmd/silkworm.cpp
- silkworm/db/freezer.cpp
- silkworm/db/freezer.hpp
- silkworm/db/snapshots/settings.hpp
- silkworm/node/node.cpp
> Add snapshot setting to keep exported blocks in mdbx

- silkworm/capi/silkworm.cpp
- silkworm/db/snapshot_bundle_factory_impl.cpp
- silkworm/db/snapshot_merger.cpp
- silkworm/db/snapshot_merger.hpp
- silkworm/db/snapshot_sync_test.cpp
- silkworm/db/snapshots/snapshot_bundle.cpp
- silkworm/db/snapshots/snapshot_bundle.hpp
> db: snapshot merger cleanup

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/core/evm_debug.cpp
Fix in STOP op for gas_cost and memory
> rpcdaemon: fix gas_cost and memory of last STOP opcode in debug API

- silkworm/db/snapshot_sync.cpp
This PR adjusts the completed count during snapshot sync because the same snapshot file can be downloaded more than once if its content changes, hence it can be notified multiple times in the completed signal of `BitTorrentClient`.
> db: fix completed count when the same snapshot is downloaded twice

- silkworm/core/execution/evm.cpp
- silkworm/core/execution/evm.hpp
- silkworm/core/execution/processor.cpp
- silkworm/core/protocol/bor_rule_set.cpp
- silkworm/core/protocol/bor_rule_set.hpp
- silkworm/core/protocol/rule_set.hpp
- silkworm/rpc/core/evm_executor.cpp
See https://github.com/maticnetwork/bor/blob/v1.3.7/core/bor_fee_log.go & https://github.com/erigontech/erigon/pull/10810
> core: implement bor_transfer

- silkworm/db/snapshot_sync.cpp
See https://github.com/erigontech/silkworm/pull/2291#discussion_r1742112295
> db: make SnapshotSync::download_snapshots callable multiple times again

- cmd/common/snapshot_options.cpp
- silkworm/db/snapshot_sync.cpp
- silkworm/db/snapshots/snapshot_settings.hpp
Same as erigon's --snap.stop flag.
> snapshots: --snapshots.stop option

- .circleci/config.yml
- cmd/dev/snapshots.cpp
> tidy: upgrade to v18 (#2277)

- docs/CONTRIBUTING.md
- docs/code_style.md
Code style RFC amendments according to decisions made on the related workshop session.
> docs: code style RFC amendments

- silkworm/db/snapshots/seg/compressor/pattern_aggregator.cpp
Increase the max number of patterns to keep in reserve while building the sorted list incrementally in order_by_score_and_limit.
Having more than kMaxPatterns patterns in consideration produces 10% better compression ratio while still keeping RAM usage under control.
see https://github.com/erigontech/erigon/pull/11672
> seg: PatternAggregator kMaxPatternsSoftLimit

- .github/workflows/run_integration_tests.sh
Modify exception list after merge PR #2430, #2450
> integration_tests: modify exception list

- .github/workflows/run_integration_tests.sh
- silkworm/db/kv/txn_num.cpp
- silkworm/db/kv/txn_num_test.cpp
THIS PR fixes problem on ots_hasCode() and eth_estimateGas()
> rpcdaemon: fix canonical body for storage provider not found key

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
Moved to integration tests v1.7 skipping not working ones
> integration: update rpc-tests to v1.7.0

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
- silkworm/rpc/core/fee_history_oracle.cpp
This PR is linked to https://github.com/erigontech/rpc-tests/pull/284
> rpcdaemon: add blobGasUsedRatio in eth_feeHistory

- .github/workflows/rpc-integration-tests.yml
- docs/JSON-RPC-API.md
- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/commands/eth_api.hpp
- silkworm/rpc/commands/parity_api.cpp
- silkworm/rpc/commands/parity_api.hpp
- silkworm/rpc/commands/rpc_api_table.cpp
- silkworm/rpc/json_rpc/methods.hpp
linked to https://github.com/erigontech/rpc-tests/pull/281
> rpcdaemon: remove parity_getBlockReceipts

- .github/workflows/rpc-integration-tests.yml
- silkworm/db/chain/chain.cpp
- silkworm/db/chain/chain.hpp
- silkworm/db/chain/chain_test.cpp
- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/json/block.cpp
- silkworm/rpc/types/block.hpp
Linked to https://github.com/erigontech/rpc-tests/pull/282
> rpcdaemon: total_difficulty in eth_getBlockBy[Number|Hash] if present in db

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
This PR is connected to https://github.com/erigontech/rpc-tests/pull/289
> rpcdaemon: update test list (parity_listStorageKeys, ots_getTransactionBySenderAndNonce)

- silkworm/db/datastore/snapshots/common/snapshot_path.cpp
- silkworm/db/datastore/snapshots/common/snapshot_path.hpp
- silkworm/db/datastore/snapshots/common/snapshot_path_test.cpp
- silkworm/db/datastore/snapshots/kv_segment/kv_segment_test.cpp
- silkworm/db/datastore/snapshots/schema.cpp
- silkworm/db/datastore/snapshots/schema.hpp
- silkworm/db/datastore/snapshots/segment/segment_test.cpp
- silkworm/db/datastore/snapshots/snapshot_repository.cpp
- silkworm/db/snapshot_test.cpp
State snapshots have a different filename format,
and placed inside subdirectories of $datadir/snapshots
> snapshots: e3 path format

- .github/workflows/run_integration_tests.sh
- silkworm/rpc/core/block_reader.cpp
- silkworm/rpc/core/block_reader.hpp
this PR is connected to https://github.com/erigontech/rpc-tests/pull/294
> rpcdaemon: erigon_getBalanceChanges for e3

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
- silkworm/db/tables.hpp
- silkworm/rpc/commands/debug_api.cpp
- silkworm/rpc/core/storage_walker.cpp
- silkworm/rpc/core/storage_walker.hpp
- silkworm/rpc/core/storage_walker_test.cpp
On CI it is necessary that erigon is at commit cf3eddc63c5bf2fdd4b28e9a563f174c1d07d243
This PR is connected to https://github.com/erigontech/rpc-tests/pull/291
> rpcdaemon: debug_storageRangeAt for e3

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
- silkworm/rpc/core/fee_history_oracle.cpp
Fixes container-overflow [detected by CI fuzzer tests](https://github.com/erigontech/silkworm/actions/runs/11874385472/job/33090294752)
This PR is associated to https://github.com/erigontech/rpc-tests/pull/298
> rpcdaemon: fix container-overflow detected by fuzzer on eth_feeHistory

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
- silkworm/rpc/commands/ots_api.cpp
- silkworm/rpc/core/evm_trace.cpp
Moved ots_getContractCreator on new KV APIs
> rpcdaemon: ots_getContractCreator for e3

- cmd/capi/execute.cpp
- cmd/dev/db_toolbox.cpp
- silkworm/capi/fork_validator.cpp
- silkworm/capi/instance.hpp
- silkworm/capi/rpcdaemon.cpp
- silkworm/capi/silkworm.cpp
- silkworm/db/access_layer.cpp
- silkworm/db/access_layer.hpp
- silkworm/db/blocks/blocks_index_builders_factory.cpp
- silkworm/db/blocks/transactions/txn_queries.hpp
- silkworm/db/data_store.cpp
- silkworm/db/data_store.hpp
- silkworm/db/datastore/snapshots/schema.cpp
- silkworm/db/datastore/snapshots/schema.hpp
- silkworm/db/datastore/snapshots/snapshot_bundle.cpp
- silkworm/db/kv/api/local_transaction.cpp
- silkworm/db/snapshot_repository_test.cpp
- silkworm/db/snapshot_sync.cpp
- silkworm/db/snapshot_sync.hpp
- silkworm/db/snapshot_sync_test.cpp
- silkworm/db/state/local_state.hpp
- silkworm/db/test_util/temp_chain_data.hpp
- silkworm/db/test_util/test_database_context.hpp
- silkworm/sync/messages/inbound_get_block_headers.cpp
* always enable state_repository
* rename DataStoreRef.repository to blocks_repository
* add state_repository to DataStoreRef and SilkwormInstance
extras:
* rename EntityDef.entities() to files()
* rename TransactionBlockNumByTxnHashRepoQuery to MultiQuery
> snapshots: add state_repository to DataStoreRef

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
This PR is linked to https://github.com/erigontech/rpc-tests/pull/301
> rpcdaemon: update skip list on debug_traceCallMany

- docs/fuzzer.md
- silkworm/core/trie/nibbles.hpp
> chore: fix some typos in comment

- silkworm/db/kv/api/endpoint/paginated_sequence.hpp
- silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
Added RangePaginatedIterator template class
> db: add range stream in temporal KV

- silkworm/db/datastore/snapshots/segment/kv_segment_reader.cpp
- silkworm/db/datastore/snapshots/segment/seg/decompressor.cpp
- silkworm/db/datastore/snapshots/segment/seg/decompressor.hpp
- silkworm/db/datastore/snapshots/segment/segment_reader.cpp
- silkworm/db/snapshot_decompressor_test.cpp
skip -> skip_compressed
next -> next_compressed
> snapshots: rename Decompressor::Iterator::skip_auto to skip

- .github/workflows/rpc-integration-tests.yml
- silkworm/db/kv/txn_num.cpp
- silkworm/db/kv/txn_num.hpp
- silkworm/db/tables.hpp
- silkworm/db/util.cpp
- silkworm/db/util.hpp
- silkworm/rpc/commands/erigon_api.cpp
- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/core/logs_walker.cpp
- silkworm/rpc/core/logs_walker.hpp
Moved eth_getLogs on new KV APIs
> rpcdaemon: eth_getLogs for e3

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
- silkworm/db/kv/txn_num.cpp
- silkworm/db/kv/txn_num.hpp
- silkworm/rpc/core/logs_walker.cpp
eth_getLogs review for performances
> rpcdaemon: fix and improve perf in eth_getLogs

- silkworm/rpc/commands/ots_api.cpp
Code review for OtsRpcApi::collect_transactions_with_receipts
> rpcdaemon: refactor OtsRpcApi::collect_transactions_with_receipts

- silkworm/node/stagedsync/stages/stage_execution.cpp
Fixes #2598 
This is the output of the `staged_pipeline debug_unwind` command:
```
INFO [12-14|07:39:42.315 UTC] Debug unwind datadir: ~/silkworm
INFO [12-14|07:39:48.593 UTC] Reopen snapshot repository folder: ~/silkworm/snapshots
INFO [12-14|07:39:57.879 UTC] Total reopened bundles: 72 max block available: 20'474'999
INFO [12-14|07:39:57.879 UTC] Debug unwind: forward to=100'000 START
INFO [12-14|07:39:57.879 UTC] ExecutionPipeline                        Forward start
INFO [12-14|07:39:57.879 UTC] [5/13 Execution]                         op=kForward from=0 to=100000 span=100000 
INFO [12-14|07:39:58.923 UTC] Flushed state                            size=671.02 KB in=7.757ms 
INFO [12-14|07:39:58.937 UTC] [5/13 Execution] commit                  batch time=14.002ms 
INFO …
```
> node: handle code hash not found in Execution unwind

- .github/workflows/run_integration_tests.sh
enabled erigon_getLatestLogs tests
> rpcdaemon: enabled erigon_getLatestLogs tests

- silkworm/rpc/commands/erigon_api.cpp
- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/core/logs_walker.hpp
Fix ChainStorage temporary allocation in LogsWalker constructor
> rpcdaemon: fix use-after-free in erigon_getLatestLogs

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
- silkworm/rpc/core/evm_debug.cpp
- silkworm/rpc/core/evm_debug.hpp
- silkworm/rpc/core/evm_debug_test.cpp
This PR is connected to https://github.com/erigontech/rpc-tests/pull/309
> rpcdaemon: add NoRefunds flag in some debug API

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/debug_api.cpp
This PR is connected to https://github.com/erigontech/rpc-tests/pull/310
> rpcdaemon: fix in debug_getRawHeader/debug_getRawBlock in case of header/block not found

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/debug_api.cpp
> rpcdaemon: debug_traceBlockByNumber with block number in hex format

- silkworm/db/chain/remote_chain_storage.cpp
this PR is connected to https://github.com/erigontech/rpc-tests/pull/313
> rpcdaemon: read_rlp_transaction() on RemoteChainStorage class

- .github/workflows/rpc-integration-tests.yml
- docs/JSON-RPC-API.md
- silkworm/db/receipt_cbor.cpp
- silkworm/rpc/commands/debug_api.cpp
- silkworm/rpc/commands/debug_api.hpp
- silkworm/rpc/commands/rpc_api_table.cpp
- silkworm/rpc/core/evm_executor.cpp
- silkworm/rpc/core/receipts.cpp
- silkworm/rpc/core/receipts.hpp
- silkworm/rpc/ethdb/cbor_test.cpp
- silkworm/rpc/json/receipt.cpp
- silkworm/rpc/json/receipt_test.cpp
- silkworm/rpc/json_rpc/methods.hpp
- silkworm/rpc/types/receipt.cpp
- silkworm/rpc/types/receipt.hpp
- silkworm/rpc/types/receipt_test.cpp
This PR requires the following rpc-tests PRs to be merged:
- https://github.com/erigontech/rpc-tests/pull/314
- https://github.com/erigontech/rpc-tests/pull/313
> rpcdaemon: impl API debug_getRawReceipts

- silkworm/rpc/core/evm_trace.cpp
trace_filter performance for long range of not existent block numbers
> rpcdaemon: fix and improve perf in trace_filter

- .github/workflows/run_integration_tests.sh
- silkworm/rpc/core/evm_debug.cpp
- silkworm/rpc/core/evm_debug_test.cpp
> rpcdaemon: error field in response for debug_traceCall

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
This PR is connected to PR https://github.com/erigontech/rpc-tests/pull/324
> integration tests: update exception list for E3 beta1

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/eth_api.cpp
This PR is connected to following PR on rpc-test repo https://github.com/erigontech/rpc-tests/pull/327
> rpcdaemon: fix eth_getStorageAt index must have hash length

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/json/block.cpp
- silkworm/rpc/types/block.hpp
This PR is connected to https://github.com/erigontech/rpc-tests/pull/328
> rpcdaemon: remove totalDifficulty from eth_getBlockByNumber/eth_getBlockByHash

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/eth_api.cpp
This  PR is connected to :  https://github.com/erigontech/rpc-tests/pull/329
> rpcdaemon: eth_createAccessList optimise_gas set default as false

- silkworm/db/access_layer.cpp
- silkworm/db/access_layer.hpp
- silkworm/db/blocks/bodies/body_queries.hpp
- silkworm/db/kv/api/local_transaction.cpp
- silkworm/db/kv/api/local_transaction.hpp
> datastore: implement LocalTransaction::first_txn_num_in_block

- .github/workflows/rpc-integration-tests.yml
- silkworm/db/datastore/common/caching_view.hpp
- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/core/estimate_gas_oracle.cpp
- silkworm/rpc/core/estimate_gas_oracle.hpp
- silkworm/rpc/core/estimate_gas_oracle_test.cpp
- silkworm/rpc/core/override_state.cpp
- silkworm/rpc/core/override_state.hpp
- silkworm/rpc/json/call.cpp
- silkworm/rpc/test_util/mock_estimate_gas_oracle.hpp
- silkworm/rpc/types/call.hpp
This PR is linked to https://github.com/erigontech/rpc-tests/pull/330
> rpcdaemon: eth_estimateGas with state overrides

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/debug_api.cpp
THis PR is connected to https://github.com/erigontech/rpc-tests/pull/331
> rpcdaemon: debug_getRawTransaction fix for block not found 

- silkworm/db/access_layer.cpp
- silkworm/db/access_layer.hpp
- silkworm/db/blocks/bodies/body_queries.hpp
- silkworm/db/blocks/schema_config.cpp
- silkworm/db/datastore/snapshots/common/encoding/sequence.hpp
- silkworm/db/datastore/snapshots/snapshot_repository.cpp
- silkworm/db/datastore/snapshots/snapshot_repository.hpp
- silkworm/db/kv/api/local_transaction.cpp
- silkworm/db/kv/api/local_transaction.hpp
- silkworm/db/state/schema_config.cpp
> snapshots: improve SnapshotRepository logs

- .github/workflows/run_integration_tests.sh
- silkworm/rpc/core/evm_debug.cpp
Added EVM executor reset between transactions debug in block
> rpcdaemon: reset EVM executor running debug_traceBlockBy*

- silkworm/db/kv/api/local_transaction.cpp
- silkworm/db/kv/api/local_transaction.hpp
- silkworm/db/state/storage_codecs.hpp
- silkworm/db/state/storage_domain.hpp
- silkworm/rpc/commands/eth_api.cpp
Implement `LocalTransaction ::get_latest` (i.e. TKV GetLatest w/ latest=true) and `LocalTransaction ::get_as_of` (i.e. TKV GetLatest w/ latest=false)
> db: Data API domain queries in LocalTransaction

- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/core/evm_executor.cpp
- silkworm/rpc/core/evm_executor.hpp
This PR is linked to https://github.com/erigontech/rpc-tests/pull/334
> rpcdaemon: add state overrides on eth_call

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
- silkworm/rpc/core/evm_debug.cpp
Fix on gas_cost for revert op_code
> rpcdaemon: fix gas cost for REVERT opcode in debug API

- .github/workflows/rpc-integration-tests.yml
- .github/workflows/run_integration_tests.sh
Moved evmone commit and enabled tests
> rpcdaemon: update evmone fork to fix gas cost for failed check_requirements

- silkworm/db/datastore/common/ranges/lazy_view.hpp
- silkworm/db/datastore/inverted_index_range_by_key_query.hpp
- silkworm/db/datastore/kvdb/domain_range_latest_query.hpp
- silkworm/db/datastore/kvdb/history_range_by_keys_query.hpp
- silkworm/db/datastore/kvdb/history_range_in_period_query.hpp
- silkworm/db/datastore/kvdb/inverted_index_range_by_key_query.hpp
- silkworm/db/datastore/snapshots/domain_range_latest_query.hpp
- silkworm/db/datastore/snapshots/history_range_by_keys_query.hpp
- silkworm/db/datastore/snapshots/inverted_index_find_by_key_segment_query.hpp
- silkworm/db/datastore/snapshots/inverted_index_range_by_key_query.hpp
- silkworm/db/kv/api/local_transaction.cpp
* refactor ascending template with if_view
* refactor lazy begin pattern with LazyView
> datastore: refactor ascending and lazy begin views

- silkworm/db/datastore/snapshots/btree/btree.cpp
> db: more fix std::basic_string::compare result in snapshot BTree

- silkworm/db/datastore/common/timestamp.hpp
- silkworm/db/datastore/snapshots/elias_fano/elias_fano_list.hpp
- silkworm/db/datastore/snapshots/inverted_index_find_by_key_segment_query.hpp
* fix list usage after move
* optimize using seek and take_while
> datastore: fix and optimize timestamp_range_filter

- silkworm/rpc/commands/eth_api_test.cpp
- silkworm/rpc/core/block_reader.cpp
- silkworm/rpc/core/block_reader.hpp
- silkworm/rpc/core/fee_history_oracle.cpp
- silkworm/rpc/core/fee_history_oracle.hpp
Change eth_feeHistory algo to minimize DB accesses
> rpcdaemon: improve data access in eth_feeHistory

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/eth_api_test.cpp
- silkworm/rpc/core/fee_history_oracle.cpp
- silkworm/rpc/core/fee_history_oracle.hpp
Error in reply when provided block number is greater than the last one
To be merged after [PR 361](https://github.com/erigontech/rpc-tests/pull/361) on rpc-test
> rpcdaemon: eth_feeHistory error  

- .github/workflows/rpc-integration-tests.yml
- silkworm/rpc/commands/eth_api.cpp
- silkworm/rpc/core/estimate_gas_oracle.cpp
- silkworm/rpc/core/estimate_gas_oracle.hpp
- silkworm/rpc/core/estimate_gas_oracle_test.cpp
- silkworm/rpc/test_util/mock_estimate_gas_oracle.hpp
This PR is connected to https://github.com/erigontech/rpc-tests/pull/365
> rpcdaemon: first try with highest gas in eth_estimateGas
