erigontech/silkworm

silkworm/chain/config.hpp
silkworm/db/buffer.cpp
silkworm/db/buffer.hpp
silkworm/db/state_buffer.hpp
silkworm/execution/evm_test.cpp
silkworm/state/intra_block_state.hpp

This PR introduces the changes needed to call `ExecutionProcessor::execute_transaction` from [Silksnake](https://github.com/torquem-ch/silksnake).
Basically this means being able to replace `db::Buffer` in `IntraBlockState` constructor with a pure virtual base class, which then Silksnake implements in a `RemoteBuffer` class accessing the data through KV gRPC.
Moreover there's a couple of minor changes:
- add pass-by-ref in `db::Buffer::insert_header` method
- add Goerli chain configuration

Silksnake integration: extract StateBuffer interface from db::Buffer

---

CMakeLists.txt
cmd/check_changes.cpp
cmd/scan_txs.cpp
core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/execution.cpp
core/silkworm/execution/execution.hpp
core/silkworm/execution/state_pool.cpp
core/silkworm/execution/state_pool.hpp
tg_api/silkworm_tg_api.cpp

Avoid mutex in ExecutionStatePool for Wasm compatibility

---

.circleci/config.yml
CMakeLists.txt
cmd/CMakeLists.txt
core/silkworm/common/util.cpp
core/silkworm/common/util.hpp
core/silkworm/common/util_test.cpp
core/silkworm/execution/precompiled.cpp

Wasm compilation of core_test

---

cmd/blockhashes.cpp
cmd/check_blockhashes.cpp
cmd/check_senders.cpp
cmd/check_tx_lookup.cpp
cmd/execute.cpp
cmd/tx_lookup.cpp
db/silkworm/common/log.cpp
db/silkworm/common/log.hpp
db/silkworm/common/log_test.cpp
db/silkworm/common/tee.hpp
tg_api/silkworm_tg_api.cpp

Simplified by removing unused - and likely unneeded - functionality.  So just one logger, and easier to reset streams logged to.
Also wrapped logging in a mutex so that the logs of multiple threads interleave cleanly.

Logging, simplified

---

db/silkworm/common/log.cpp
db/silkworm/common/log.hpp

Placing log_ class in detail namespace badly confuses compiler when expanding macros in nested namespaces.  No amount of explicit qualification seems  to help.

make LOG macros work in subspaces

---

.circleci/config.yml
.gitmodules
appveyor.yml
core/silkworm/execution/evm_test.cpp

https://github.com/ethereum/pm/issues/263
Part of Issue #99

Per ACD meeting 107 EIP-2315 was removed from Berlin

---

cmd/check_senders.cpp

* Move the stage regression persistance at the end of unwind method (so unwind can be called as standalone method)
* Don't commit if user has CTRL+C

Small change in check_senders logic

---

core/silkworm/common/lru_cache.hpp

I've measured block execution time and using `absl::flat_hash_map` instead of `std::unordered_map` in `lru_cache` doesn't bring any performance gain, but is actually slightly slower.

Switch lru_cache back to std::unordered_map

---

.circleci/config.yml
README.md
cmd/check_senders.cpp
db/silkworm/common/magic_enum.hpp

Introduce [magic-enum header](https://github.com/Neargye/magic_enum) and upgrade GCC to 9.x due to [header's limitations](https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md).
Magic enum provides a useful static reflection over enums.

Magic enum

---

.circleci/config.yml
CMakeLists.txt
README.md
appveyor.yml

This reverts commit b46f5c3c0796674ff28ce43cccd18fc1e046da7a.
This feature useful when somebody else updates submodules and you then pick up their changes automatically, but on the other hand it's super annoying or confusing when you change a submodule locally prior to commit and then your change is silently reverted by build.
See also https://stackoverflow.com/questions/4611512/is-there-a-way-to-make-git-pull-automatically-update-submodules

Revert "Git submodule automation on build (#155)"

---

.circleci/config.yml

This is to alleviate slow consensus tests in CI

Switch linux-gcc-9 to Release and no_output_timeout in linux-clang-coverage

---

cmd/consensus.cpp
core/silkworm/chain/blockchain.cpp
core/silkworm/chain/blockchain.hpp

With this optimization `cmd/consensus` takes 30 instead of 35 sec on my MacBook.

Optimization: use ExecutionStatePool in consensus tests

---

cmd/consensus.cpp

Use evmc_load_and_configure() instead of evmc_load_and_create().
This allows passing additional EVMC options to VM along with the path,
e.g. --evm=./libevmone.so,O=0.
Documentation: https://evmc.ethereum.org/group__loader.html#gabd3a005d5ac0ca5230e71df1b1940f9c

cmd/consensus: Allow passing EVMC options to VM

---

.gitignore
core/silkworm/execution/evm.cpp
core/silkworm/state/intra_block_state.cpp

This updates evmone to upstream version implementing EIP-2929. So far this is needed for evmone consensus testing (cyclic dependency).

EIP-2929 evmone implementation update

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp

This change is needed by Silkrpc that is using Silkworm EVM to implement `eth_call`

Return data in CallResult from EVM execution

---

.gitmodules
cmd/consensus.cpp
core/silkworm/execution/evm.cpp

Implement [EIP-3198](https://eips.ethereum.org/EIPS/eip-3198) (Issue #232)

EIP-3198: BASEFEE opcode

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp
core/silkworm/execution/processor.cpp

Evm test fail if txn.from is empty

EVM::execute Precondition: txn.from must be recovered

---

cmd/check_hashstate.cpp
cmd/check_senders.cpp
cmd/hashstate.cpp

`MDB_val mdb_key{db::to_mdb_val(Bytes(8, '\0'))};`
contains a bug. `Bytes(8, '\0')` creates a temporary object, which is destroyed after the line. And later we try to access an already deallocated memory via the view. (`MDB_val` is a view, essentially the same as `std::string_view`)

Fix access to already deallocated memory in cmd/hashstate

---

CMakeLists.txt
CMakeSettings.json
cmake/compiler_settings.cmake
cmd/CMakeLists.txt
ethash/CMakeLists.txt

* create compiler_settings.cmake : store (roughly) all settings for compilers in one place so we can more easily manage different compilers
* add parallel builds for MSVC
* add LTCG for MSVC
* silence a good amount of warnings on MSVC
* add proper value for `__cplusplus` definition on MSVC (in preparation of MDBX)
* add `Release` build for Visual Studio users

Reorganize CMAKE

---

core/silkworm/trie/hash_builder.cpp
db/silkworm/trie/db_trie.hpp
db/silkworm/trie/db_trie_test.cpp

Previously hash & tree masks in `HashBuilder`, necessary for populating account (and storage) tries in the DB, were handled incorrectly around extension nodes.
Part of Issue #179.

Fix account trie around extension nodes

---

db/silkworm/types/receipt_cbor.cpp
db/silkworm/types/receipt_cbor.hpp
db/silkworm/types/receipt_cbor_test.cpp

CBOR encoding of receipts now includes [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) transactions types; see https://github.com/ledgerwatch/erigon/pull/2221

Include type into receipt CBOR

---

db/silkworm/common/temp_dir.hpp
db/silkworm/db/access_layer_test.cpp

`TEST_CASE("Db Opening")` was crashing or triggering Address Sanitizer for me.

Fix double deletion of a TemporaryDirectory

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp

An `evmc_message` contains only two addresses (sender and "destination").
However, in case of `DELEGATECALL` we need 3 addresses (sender, recipient, and code), so we recover the missing 3rd address from the `address_stack_`.
See Section 8 "Message Call" of the Yellow Paper.
`destination` in `evmc_message` can mean either code or recipient, depending on the context.

Clarify the difference between code and recipient

---

codecov.yml
db/silkworm/db/access_layer.cpp
db/silkworm/db/access_layer_test.cpp

```
auto key{to_slice(block_key(0))};
```
is problematic.
`block_key(0)` returns a temporary `Bytes` instance, which is then destroyed at the end of the line, so we end up with a view of a destroyed (byte)string.

Fix AddressSanitizer: stack-use-after-scope in read_chain_config

---

db/silkworm/stagedsync/stage_hashstate.cpp
db/silkworm/stagedsync/unwind_execution_test.cpp
db/silkworm/stagedsync/util.cpp
db/silkworm/stagedsync/util.hpp
db/silkworm/stagedsync/util_test.cpp

I believe this version make unwind hashstate a bit more readable and removes branch checks on every record.
Also 
* removed double allocation of Bytes
* make use of seek on cursor when no need to retrive data
* ensure all cases of eums are covered properly (switch)
* removed leftover of unused table
Please check a run before merge

Hashstate unwind clarification

---

db/silkworm/stagedsync/stage_execution.cpp

There was a bug related to the `execute` function `stage_execution.cpp`. It set `block_num` to the last executed block number when the buffer was full, but to `max_block + 1` when `max_block` was reached. Thus in the later case the subsequent `set_stage_progress` was called with `max_block + 1`  instead of `max_block`.
Also, I've made some improvements to the function:
1. Put the function into an anonymous namespace
2. Rename to `execute_batch_of_blocks` for clarity
3. Move `block_num` (an input-output) after all purely input args as per [Google's code style](https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs)
4. Make `block_num` a reference
5. Mark as `noexcept`

Fix inconsistent block_num set in stagesync execute

---

cmd/execute.cpp
db/silkworm/stagedsync/stage_execution.cpp
db/silkworm/stagedsync/stagedsync.hpp
db/silkworm/stagedsync/stages.cpp

Stage uniformity is useful for future work (something similar to `erigon/eth/stagedsync/default_stages.go`).

Restore stage uniformity

---

db/silkworm/common/log.cpp
db/silkworm/common/log_test.cpp

Before:
```
INFO [07-23|16:26:18.391]  Blocks <= 3994982 committed
```
After:
```
INFO [07-23|16:26:18.391] Blocks <= 3994982 committed
```

SILKWORM_LOG printed an extra space

---

cmake/Hunter/config.cmake

Update abseil to [20210324.2](https://github.com/abseil/abseil-cpp/releases/tag/20210324.2) to fix build with GCC 11 (see https://github.com/abseil/abseil-cpp/pull/974#discussion_r653574443). Kudos to Artem for reporting.

Update abseil to 20210324.2

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp
core/silkworm/execution/execution.cpp

This is a performance optimization. For one-off execution (such as deployment code) evmone baseline interpreter is generally faster. In my tests this change decreased the total execution time of all mainnet blocks by 3%.

Execute deployment code with baseline rather than advanced interpreter

---

CMakeLists.txt

[Version 0.8.1](https://github.com/ethereum/evmone/releases/tag/v0.8.1) fixes Issue #305.

Update evmone to 0.8.1

---

core/silkworm/crypto/sha-256.c

The version that uses [ARMv8 SHA2 extensions](https://developer.arm.com/documentation/ddi0500/e/CJHDEBAF) is 7 times faster on my Apple M1.
Continuation of PR #311.

ARMv8 SHA256 intrinsics

---

.clang-format
cmd/history_index.cpp
cmd/log_index.cpp
cmd/unwind_history_index.cpp
cmd/unwind_log_index.cpp
core/silkworm/crypto/sha-256.c
core/silkworm/crypto/sha-256.h
db/silkworm/common/stopwatch.hpp
db/silkworm/db/bitmap.cpp
db/silkworm/db/bitmap.hpp
db/silkworm/db/bitmap_test.cpp
db/silkworm/db/stages.hpp
db/silkworm/etl/collector.hpp
db/silkworm/etl/file_provider.cpp
db/silkworm/stagedsync/listener_log_index.hpp
db/silkworm/stagedsync/recovery/recovery_worker.cpp
db/silkworm/stagedsync/stage_blockhashes.cpp
db/silkworm/stagedsync/stage_blockhashes_test.cpp
db/silkworm/stagedsync/stage_bodies.cpp
db/silkworm/stagedsync/stage_headers.cpp
db/silkworm/stagedsync/stage_history_index.cpp
db/silkworm/stagedsync/stage_interhashes.cpp
db/silkworm/stagedsync/stage_log_index.cpp
db/silkworm/stagedsync/stage_senders.cpp
db/silkworm/stagedsync/stagedsync.hpp
db/silkworm/stagedsync/stages.cpp
db/silkworm/stagedsync/util.hpp

Add
```
DerivePointerAlignment: false
PointerAlignment: Left
```
to `.clang-format` and reformat the code.
Most of our code already uses left pointer (and reference) alignment.

Format: consistently use left pointer (and ref) alignment

---

node/silkworm/etl/collector.cpp

- use references in comparison function to avoid copies/memory allocations.
- move values for same reason as above

possible speedups for issue #195

---

node/silkworm/etl/collector.cpp
node/silkworm/etl/collector.hpp
node/silkworm/etl/collector_test.cpp
node/silkworm/stagedsync/recovery/recovery_farm.cpp
node/silkworm/stagedsync/stage_blockhashes.cpp
node/silkworm/stagedsync/stage_history_index.cpp
node/silkworm/stagedsync/stage_log_index.cpp
node/silkworm/trie/intermediate_hashes.cpp

I haven't tested it besides running core_test and node_test, but it is simple enough that it should work and avoid unnecessary etl::Entry copies.
Each etl::Entry copy will cause two `malloc()` when allocating the new std::basic_string, two data copies,  and two `free()` when the original is destructed. Doing a move avoids all this.

issue #195 - speedup etl by avoiding unnecessary copies

---

cmd/check_senders.cpp
cmd/download_headers.cpp
node/silkworm/concurrency/active_component.hpp
node/silkworm/concurrency/containers.hpp
node/silkworm/concurrency/thread_safe_queue.hpp
node/silkworm/concurrency/worker.cpp
node/silkworm/concurrency/worker.hpp
node/silkworm/downloader/SentryClient.cpp
node/silkworm/downloader/SentryClient.hpp
node/silkworm/downloader/gRPCAsyncClient.hpp
node/silkworm/downloader/stage1.cpp
node/silkworm/downloader/stage1.hpp
node/silkworm/stagedsync/recovery/recovery_worker.cpp
node/silkworm/stagedsync/recovery/recovery_worker.hpp

Move `ActiveComponent`, `ThreadSafeQueue`, and `Worker` into silkworm/concurrency. More consistent function names between `ActiveComponent` and `Worker`.

Gather concurrency things in silkworm/concurrency

---

core/silkworm/chain/validity.cpp

This is a small improvement when `get_parent` is called for 0th block: immediately return `std::nullopt` instead of looking up for block number UINT64_MAX in the state.

Avoid potential numeric underflow in get_parent

---

cmd/consensus.cpp
core/silkworm/chain/config.cpp
core/silkworm/chain/config.hpp
core/silkworm/chain/config_test.cpp
core/silkworm/common/test_util.cpp
core/silkworm/common/test_util.hpp
core/silkworm/execution/execution_test.cpp
core/silkworm/execution/processor_test.cpp
node/silkworm/stagedsync/prune_execution_test.cpp
node/silkworm/stagedsync/stage_senders_test.cpp
node/silkworm/stagedsync/tx_lookup_test.cpp
node/silkworm/stagedsync/unwind_execution_test.cpp

`kLondonTestConfig` is used only in tests, so moving it into `test_util.hpp`

Move kLondonTestConfig into test_util

---

node/silkworm/db/util.cpp
node/silkworm/db/util.hpp
node/silkworm/stagedsync/stage_execution.cpp
node/silkworm/stagedsync/stage_hashstate.cpp
node/silkworm/stagedsync/stage_history_index.cpp
node/silkworm/stagedsync/util.cpp
node/silkworm/stagedsync/util.hpp

`convert_to_db_format` was a bad name because it converts from one DB format (AccountChangeSet or StorageChangeSet) into another DB format (PlainState).

convert_to_db_format -> change_set_to_plain_state_format

---

node/silkworm/common/signal_handler.cpp
node/silkworm/common/signal_handler.hpp

The inline initialization of static members causes warnings like 
```
LINK : warning C4744: 'static struct std::atomic<bool> silkworm::SignalHandler::signalled_' has different type in 'd:\github\silkworm\node\silkworm\stagedsync\stage_senders.cpp' and 'd:\github\silkworm\cmd\toolbox.cpp': '__declspec(align(1)) struct (1 bytes)' and 'struct (1 bytes)' [C:\Users\Andrea\CMakeBuilds\silkworm\Debug\cmd\toolbox.vcxproj]
```
Revert to initialization in own compile unit

Signals - Don't inline initialization of static memeber

---

node/silkworm/common/signal_handler.cpp

It's not possible to handle SIGSTOP & SIGKILL manually. From [macOS man](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/signal.3.html): "ERRORS: ... An attempt is made to ignore or supply a handler for SIGKILL or SIGSTOP.". And per [Linux man](https://man7.org/linux/man-pages/man2/signal.2.html): "The signals SIGKILL and SIGSTOP cannot be caught or ignored."

SIGSTOP & SIGKILL cannot be caught

---

cmd/consensus.cpp
core/silkworm/common/endian.cpp
core/silkworm/common/endian.hpp
core/silkworm/common/endian_test.cpp
core/silkworm/rlp/decode.cpp
core/silkworm/types/account.cpp
node/silkworm/stagedsync/stage_tx_lookup.cpp

As a prerequisite, `from_big_compact_u64` & `from_big_compact_u256` are unified into template `from_big_compact`.

Remove code duplication between rlp::decode(uint64_t) & decode(uint256)

---

README.md

Remove the badges from README because [lgtm.com](https://lgtm.com/projects/g/torquem-ch/silkworm) displays 0 lines of code for Silkworm for some reason (and it's a rather low priority to sort out). Also, as discussed, I've disabled the automatic PR code reviews.

Remove LGTM badges

---

cmd/consensus.cpp
core/silkworm/common/test_util.hpp
core/silkworm/consensus/engine.cpp
core/silkworm/consensus/validation.hpp
core/silkworm/execution/evm.cpp

Update consensus tests to [v10.2](https://github.com/ethereum/tests/releases/tag/v10.2). Difficulty tests were refactored in that release.
Implement [EIP-2681](https://eips.ethereum.org/EIPS/eip-2681): Limit account nonce to 2^64-1.

Update tests to 10.2. EIP-2681

---

interfaces/sentry.pb.cc
interfaces/sentry.pb.h
interfaces/sentry.proto
node/silkworm/downloader/internals/chain_elements.hpp
node/silkworm/downloader/internals/chain_integration_test.cpp
node/silkworm/downloader/internals/priority_queue_test.cpp
node/silkworm/downloader/internals/types.hpp
node/silkworm/downloader/internals/working_chain_test.cpp
node/silkworm/downloader/messages/InboundBlockHeaders.cpp
node/silkworm/downloader/messages/InboundGetBlockBodies.cpp
node/silkworm/downloader/messages/InboundGetBlockBodies.hpp
node/silkworm/downloader/messages/InboundGetBlockHeaders.cpp
node/silkworm/downloader/messages/InboundGetBlockHeaders.hpp
node/silkworm/downloader/messages/InboundNewBlock.cpp
node/silkworm/downloader/messages/InboundNewBlock.hpp
node/silkworm/downloader/messages/InboundNewBlockHashes.cpp
node/silkworm/downloader/messages/InboundNewBlockHashes.hpp
node/silkworm/downloader/rpc/PeerMinBlock.cpp
node/silkworm/downloader/rpc/PeerMinBlock.hpp
node/silkworm/downloader/rpc/PenalizePeer.cpp
node/silkworm/downloader/rpc/PenalizePeer.hpp
node/silkworm/downloader/rpc/SendMessageById.cpp
node/silkworm/downloader/rpc/SendMessageById.hpp

Reverts torquem-ch/silkworm#509 to align Silkworm to the stable version of Erigon's Sentry.
Erigon stable still uses H512 for peer_id.

Revert "Change sentry peer_id from H512 pubkey to H256 keccak256(pubkey)"

---

cmd/CMakeLists.txt

cmd/consensus depends on node now and can't be built if SILKWORM_CORE_ONLY

---

cmd/CMakeLists.txt
core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp

This PR adds the tracing capability (necessary for `debug_*` and `trace_*` API in Silkrpc) to `silkworm::EVM`, wrapping the same functionality available from `evmone::VM`.
These are the key decisions I've taken in the detail design of tracing as an optional functionality:
- do not break encapsulation exposing `evmone::VM` from `silkworm::EVM` header
- as a consequence, define a separate `silkworm::EvmTracer` delegating to `evmone::Tracer` for implementation
- and use forward declaration for other `evmone` types, leaving to the client code using tracing to include `evmone`
I've added `emvone` as a new dependency for core unit tests.

Add EVM tracer support

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp

Add `IntraBlockState` in the `EvmTracer` interface callbacks to access storage values
The `IntraBlockState` parameter is needed also in `on_execution_end` function in order to access intra-block state after the last opcode

Add intra-block state to EVM tracer

---

cmd/toolbox.cpp

Fixes #541 
```size_t pagesCount = *(static_cast<uint32_t*>(data.value.iov_base));```
is not the same as
```
size_t pagesCount;
std::memcpy(&pagesCount, data.value.data(), sizeof(size_t));
```

Correction to PR 538

---

core/silkworm/execution/processor.cpp
core/silkworm/execution/processor.hpp
core/silkworm/execution/processor_test.cpp
core/silkworm/state/intra_block_state.cpp
core/silkworm/state/intra_block_state.hpp

This is a small opimization reducing memory allocation in `ExecutionProcessor::execute_transaction`. The idea is use logs (which might have some capacity already) from the provided out parameter `receipt` in `IntraBlockState`. The total time of executing 14M main net blocks is reduced from 33.8h to 33.4h.

[Optimization] Reduce memory allocation in execute_transaction

---

core/silkworm/common/endian.cpp
core/silkworm/common/endian.hpp
core/silkworm/rlp/encode.cpp
core/silkworm/types/account.cpp

This is trying to avoid creating a std::string in `to_big_compact()`, which is destroyed immediately after. The issue is that, with this change,   `to_big_compact()`  returns a `ByteView` which points to the static buffer of inside the function. As the result is usually used immediately after the call, I don't think it it a significant issue, but you guys might disagree of course :-).

Fix unnecessary std::string creation/destruction

---

core/silkworm/common/endian.cpp
core/silkworm/rlp/decode.hpp
core/silkworm/types/account.cpp
core/silkworm/types/account.hpp
core/silkworm/types/account_test.cpp
node/silkworm/db/access_layer.cpp
node/silkworm/stagedsync/stage_execution.cpp
node/silkworm/stagedsync/stage_hashstate.cpp
node/silkworm/stagedsync/stage_hashstate_test.cpp
node/silkworm/trie/intermediate_hashes.cpp

- fix decode account from encoded rlp : 1) Check payload is either empty or > 1 (otherwise first `encoded_payload[pos++]` gives undefined behavior); 2) remove duplicate checks and reduce to a loop; 
- fix decode incarnation from encoded rlp : implementation did not include all checks of the previous
- move `decode_account_from_storage` to `Account::from_encoded_storage`
- move `extract_incarnation` to `Account::incarnation_from_encoded_storage`
- addedd missing tests for wrong payloads

Fix account decoding

---

node/silkworm/db/access_layer.cpp

With this optimization main net execution time goes down from 33h:26m to 28h:56m.

[Optimization] Reuse cursors to reduce memory reallocation

---

cmd/download_headers.cpp
node/silkworm/common/log.cpp
node/silkworm/common/log.hpp

Debugging the downloader requires the analysis of hundreds of thousands of lines of code. Also numbers with many digits, for example block numbers, are difficult to understand at first glance.
Having thousands separator when logging big numbers improves log lines readability a lot.
This PR add a parameter in the log settings to specify a thousands separator.
For example in the downloader, this log line:
`INFO [02-14|20:18:32.143 UTC] [140737348180608] [1/16 Headers] Wrote block headers number=14206352 (+142789), 1890 headers/secs, 1 wait.msgs, 19742 links, 32 anchors [headers: req=16000262 rec=16001437 (100%) -> acc=14206696`
become
`INFO [02-14|20:18:32.143 UTC] [140'737'348'180'608] [1/16 Headers] Wrote block headers number=14'206'352 (+142'789), 1'890  headers/secs, 1 wait.msgs, 19'742 …

Optional thousands separator in log lines

---

node/silkworm/common/directories_test.cpp

It's dangerous to tamper with the default data directory (e.g. ~/Library/Silkworm), which could contain your real instance, while running unit tests.

Don't use default data directory in tests

---

node/silkworm/db/prune_mode.cpp
node/silkworm/db/prune_mode.hpp

Fixes Silkworm part of #575 
Rationale: `BlockAmount` is cheap to copy, so we can pass by value and avoid memory leak detected by LeakSanitizer

Avoid memory leaks detected by LeakSanitizer

---

core/silkworm/common/endian.hpp

This reverts a small part of PR #582 which somehow causes `core_test` to [hang](https://ci.appveyor.com/project/torquem/silkworm/builds/42721668) in Windows CI.

Fix core_test on Windows

---

.circleci/config.yml
.gitignore
CMakeLists.txt
cmake/compiler_settings.cmake

This PR adds:
- instrumentation for running AddressSanitizer (ASAN) and ThreadSanitizer (TSAN) on Clang/GCC builds
- CI jobs with ASAN/TSAN enabled
See #295

Add instrumentation and CI jobs for sanitized builds

---

node/silkworm/rpc/backend_server.cpp

This PR closes a data race occurring in gRPC server initialization: gRPC async model requres the server to start in advance _request registered calls_ (gRPC naming) for every supported RPC in order to be able to respond to client incoming requests. Such registered calls were erroneously scheduled on `asio::io_context` schedulers, making their initialization escape the critical section containing the call to `request_calls` method
Fixes #593

Start server requests synchronously within critical section

---

cmd/download_headers.cpp
node/silkworm/downloader/header_downloader.cpp
node/silkworm/downloader/header_downloader.hpp
node/silkworm/downloader/internals/persisted_chain.cpp
node/silkworm/downloader/internals/persisted_chain.hpp
node/silkworm/downloader/internals/working_chain.cpp
node/silkworm/downloader/internals/working_chain.hpp
node/silkworm/downloader/messages/InboundBlockHeaders.cpp
node/silkworm/downloader/messages/OutboundGetBlockHeaders.cpp
node/silkworm/downloader/messages/OutboundGetBlockHeaders.hpp

This PR removes some unneeded limitations so the header request rate is improved a lot. 
Notes:
1. this PR uses dense pre-verified hashes, not the sparse one of the main branch. Initial performance tests have shown that this branch behaves like Erigon. Another branch and PR will be created to compare performances with and without dense pre-verified hashes.
2. the tests of this PR were done with a different version of the db::access_layer, an old version NOT using mdbx_cursor_bind. In a tests spanning three days no errors was raised by mdbx. Differently using the main branch db::access_layer tests breaks frequently with a MDBX_ERROR. I defer to another PR to understand if there is a problem in the downloader, if there is a problem in db::access_layer or in the mdbx implementation.

Improving downloader performances

---

node/silkworm/rpc/completion_runner.cpp

Not sure why the sanitizers in CI didn't catch it, but it was causing bad access when running `node_test` on my MacBook.

Fix bad access to ok in CompletionRunner::run

---

cmd/CMakeLists.txt
cmd/backend_kv_server.cpp
cmd/test/backend_kv_test.cpp
node/silkworm/rpc/backend_server.cpp
node/silkworm/rpc/backend_server.hpp
node/silkworm/rpc/backend_server_test.cpp
node/silkworm/rpc/call.hpp
node/silkworm/rpc/server_config.cpp
node/silkworm/rpc/server_config.hpp
node/silkworm/rpc/server_config_test.cpp
node/silkworm/rpc/server_test.cpp
node/silkworm/rpc/service.hpp
node/silkworm/rpc/service_test.cpp

Add server-streaming RPC support
Complete test client for for BackEnd RPCs

Complete structure for BackEnd RPC services

---

.circleci/config.yml
cmd/test/consensus.cpp

Previously they were killed probably due to out of memory, so I reduced the number of threads to 4 ([xlarge](https://circleci.com/docs/2.0/configuration-reference/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-maxConv-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQiAmpyRBhC-ARIsABs2EAocMlkHTx5LIFPhLdyjLiHjVG1JdcweZ3tBqKRYj0ZSa2zaxV8B0xYaAshSEALw_wcB#machine-executor-linux) resource_class in CircleCI has 8 CPUs).

Enable consensus tests under thread sanitizer

---

cmd/common.cpp
node/silkworm/db/mdbx.cpp
node/silkworm/db/mdbx.hpp
node/silkworm/db/mdbx_test.cpp
node/silkworm/db/stages.cpp

- Upgrade libmdbx to latest master so we include changes solving issue from reuse of cursors bound to RO transactions
- Added more cursor pool tests
- make db::Cursor constructible/bindable from RWTxn too

Reuse cursors - 2

---

cmake/Hunter/config.cmake
core/silkworm/common/endian.hpp
core/silkworm/common/endian_test.cpp
core/silkworm/common/util.hpp
core/silkworm/crypto/snark.cpp
core/silkworm/execution/precompiled.cpp
node/silkworm/db/buffer_test.cpp

Switch to the new endian facilities introduced in release [0.8.0](https://github.com/chfast/intx/releases/tag/v0.8.0) of intx.

Switch to intx 0.8.0 endian facilities

---

.gitmodules
cmd/check_changes.cpp
cmd/scan_txs.cpp
core/silkworm/chain/config.cpp
core/silkworm/chain/config.hpp
core/silkworm/chain/config_test.cpp
core/silkworm/common/base.hpp
core/silkworm/execution/analysis_cache.cpp
core/silkworm/execution/analysis_cache.hpp
core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp
node/silkworm/stagedsync/stage_execution.cpp
node/silkworm/stagedsync/stage_execution.hpp

Switching execution from advanced to baseline evmone interpreter results in performance saving of about 1h (out of circa 1day) of the execution time. One contributing factor, I think,  is that baseline `CodeAnalysis` is more compact than `AdavancedCodeAnalysis`, so the cache is significantly smaller and thus more RAM is available for MDBX page caching by the OS.
| master@[01158d73](https://github.com/torquem-ch/silkworm/commit/01158d7375adbb366d826ece1ba407c4f9c28671) | baseline@[a972151c](https://github.com/torquem-ch/silkworm/commit/a972151c2d5c561561d971963bc26855f6e4ed11) |
| --- | --- | 
| Execution         done=22h 9m 42s | Execution         done=21h 13m 35s | 
|![master](https://user-images.githubusercontent.com/34320705/159516825-edac0599-ac6e-42dd-b786-416b2aafab8a.png)|![baseline …

Switch execution to evmone baseline interpreter

---

core/silkworm/common/test_util.hpp
core/silkworm/execution/evm_test.cpp

Implement [EIP-3855](https://eips.ethereum.org/EIPS/eip-3855): PUSH0 instruction, which is scheduled for [Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md).

EIP-3855: PUSH0 instruction

---

core/silkworm/execution/evm.cpp

Because after [EIP-161](https://eips.ethereum.org/EIPS/eip-161) it's impossible within EVM to differentiate between empty and non-existent accounts, the early exit in `EVM::call` is unnecessary. Its purpose was to cater for this rule of EIP-161: "No account may change state from non-existent to existent-but-_empty_. If an operation would do this, the account SHALL instead remain non-existent."
Without the early exit some empty accounts might be created, but then they will be deleted at transaction's end as empty touched accounts.

Remove unnecessary early exit in EVM::call

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp

Adding stack_height and stack_top to get the stack values, since evmone::ExecutionState doesn't have the evmone::Stack inside itself anymore.

Adapting EvmTracer to evmone::Tracer

---

cmd/backend_kv_server.cpp
node/silkworm/backend/ethereum_backend.cpp
node/silkworm/backend/ethereum_backend.hpp
node/silkworm/rpc/backend_calls.cpp
node/silkworm/rpc/backend_calls.hpp
node/silkworm/rpc/backend_kv_server.cpp
node/silkworm/rpc/backend_kv_server_test.cpp
node/silkworm/rpc/call.hpp
node/silkworm/rpc/call_factory.hpp
node/silkworm/rpc/call_factory_test.cpp
node/silkworm/rpc/call_test.cpp
node/silkworm/rpc/client/call.hpp
node/silkworm/rpc/client/sentry_client.cpp
node/silkworm/rpc/client/sentry_client.hpp
node/silkworm/rpc/completion_end_point.cpp
node/silkworm/rpc/kv_calls.cpp
node/silkworm/rpc/kv_calls.hpp
node/silkworm/rpc/kv_calls_test.cpp

This PR introduces the initial implementation of KV Tx bidirectional RPC. Key points:
- every new Tx incoming RPC creates a new MDBX read-only transaction
- one unsolicited message containing the txn ID is notified to the client
- cursor open/close and tracking by pairing `db::Cursor` with table name to support reopening
- one max txn TTL timer protects against long-lived txn by aborting/reopening the txn on behalf of the client, opened cursors are saved/restored transparently
- another idle timer protects against clients which don't send any (more) requests and eventually terminates the RPC
TODOLIST:
- check errors when limits are reached (max number of txns, max number of cursors per txn), if applicable

Add initial KV Tx RPC implementation

---

node/silkworm/rpc/call.hpp
node/silkworm/rpc/kv_calls.cpp

This PR removes the `BidirectionalStreamingRpc::send_response` method overload using forward reference because this is the one change causing repeated failures on TSAN CI job, namely [here](https://app.circleci.com/pipelines/github/torquem-ch/silkworm/4416/workflows/dd9c130c-6660-4cc6-aaeb-1d5f30ebca21/jobs/14083) and [here](https://app.circleci.com/pipelines/github/torquem-ch/silkworm/4414/workflows/8398bbec-2264-404c-a844-95c6b3dbfb80/jobs/14073).

Remove forward reference overload in KV RPC

---

.circleci/config.yml
cmake/compiler_settings.cmake
node/silkworm/rpc/backend_kv_server_test.cpp

This PR skips one specific test in TSAN build because such test triggers some data race within the gRPC library in a very specific scenario.
The "BackEndKvServer E2E: trigger server-side write error" test is purposely written to cause write-errors on Tx RPC server-side implementation by using the bidirectional-streaming API in an unorthodox way, i.e. not reading responses after sending requests and making the Tx call end abruptly on client-side by `grpc::ClientContext` destruction.
Repeating this pattern many times triggers write-errors on Tx RPC server-side implementation and allows to check that server-side lifecycle management for Tx calls is OK but seems to result also in a frequent data race detection during sanitizer builds.

Skip test causing gRPC data race in sanitizer build

---

cmd/backend_kv_server.cpp
node/silkworm/rpc/backend_calls.hpp
node/silkworm/rpc/backend_kv_server_test.cpp
node/silkworm/rpc/kv_calls.cpp
node/silkworm/rpc/kv_calls.hpp
node/silkworm/rpc/kv_calls_test.cpp
node/silkworm/rpc/server_config_test.cpp

This PR introduces a sanity check on max number of opened cursors per txn in KV Tx RPC.

Add max cursors per txn check in KV Tx RPC

---

node/silkworm/rpc/backend_kv_server_test.cpp
node/silkworm/rpc/completion_end_point_test.cpp
node/silkworm/rpc/server.hpp
node/silkworm/rpc/server_context_pool_test.cpp
node/silkworm/rpc/server_test.cpp

This PR excludes the gRPC server tests from the sanitizer builds.

Exclude gRPC server tests from sanitizer builds

---

CMakeLists.txt
cmake/Hunter/config.cmake
cmd/backend_kv_server.cpp
cmd/check_blockhashes.cpp
cmd/check_changes.cpp
cmd/check_hashstate.cpp
cmd/check_pow.cpp
cmd/check_tx_lookup.cpp
cmd/common.cpp
cmd/download_headers.cpp
cmd/genesistool.cpp
cmd/history_index.cpp
cmd/log_index.cpp
cmd/scan_txs.cpp
cmd/test/backend_kv_test.cpp
cmd/test/consensus.cpp
cmd/toolbox.cpp
cmd/trie.cpp
cmd/tx_lookup.cpp
cmd/unwind_history_index.cpp
cmd/unwind_log_index.cpp
cmd/unwind_tx_lookup.cpp

OpenSSL, intx, benchmark were updated in Hunter [v0.24.1](https://github.com/cpp-pm/hunter/releases/tag/v0.24.1), so no need to override them.
To update CLI11 I had to make quite a few code changes because
`.add_option(..., true)`
should be replaced by
`.add_option(...)->capture_default_str()`

Update Hunter to v0.24.1 and CLI11 to v2.2.0

---

cmd/backend_kv_server.cpp
cmd/test/backend_kv_test.cpp
node/silkworm/backend/ethereum_backend.cpp
node/silkworm/backend/ethereum_backend.hpp
node/silkworm/backend/ethereum_backend_test.cpp
node/silkworm/rpc/client/call_test.cpp
node/silkworm/rpc/server/backend_kv_server_test.cpp
node/silkworm/rpc/server/state_change_collection.cpp
node/silkworm/rpc/server/state_change_collection.hpp

This PR makes the state-change collection point thread-safe. This is required because:
- the staged loop thread will act as state-change source, creating new state-change batches and notifying them to registered consumers
- the threaded schedulers running the RPC server-side calls will concurrently register state-change consumers

State changes safe consumers

---

node/silkworm/backend/state_change_collection_test.cpp
node/silkworm/rpc/completion_end_point.cpp
node/silkworm/rpc/completion_end_point.hpp
node/silkworm/rpc/completion_end_point_test.cpp

This PR includes support in RPC `CompletionEndPoint` for posting completion handlers to `asio::io_context` scheduler (as part of the changes to add wait policies to `ServerContext` execution loop)

Add asio::io_context integration in gRPC completion end point

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp

This PR improves the `EvmTracer` hooks needed by Silkrpc for `trace_*` API implementation. In particular:
- add new `EvmTracer::on_precompiled_run` and `EvmTracer::on_reward_granted` methods used in Silkworm `EVM::call` and in Silkrpc respectively
- use `CallResult` as the `result` parameter type in `EvmTracer` hooks
The proposed changes maintain and exposes the registered tracers also in `EVM` because:
- the new hooks (`on_precompiled_run`/`on_reward_granted`) are dispatched within Silkworm/Silkrpc, hence accessing the list of registered tracers is necessary;
- obviously `evmone` already maintains the tracers, but they are accessible only inside `evmone` itself. `evmone::VM` has `get_tracer` method exposing the first tracer, but `evmone::Tracer` does not support `next_tracer` method or …

Extend evm tracer

---

core/silkworm/execution/evm_test.cpp
node/silkworm/rpc/client/call_test.cpp
node/silkworm/rpc/completion_end_point_test.cpp
node/silkworm/rpc/server/backend_kv_server_test.cpp
node/silkworm/rpc/server/server_config_test.cpp
node/silkworm/rpc/server/server_context_pool_test.cpp
node/silkworm/rpc/server/server_test.cpp
node/silkworm/rpc/util_test.cpp

This PR excludes gRPC tests from ASAN/TSAN builds because even simple test cases containing only gRPC code trigger errors [like this one](https://app.circleci.com/pipelines/github/torquem-ch/silkworm/4562/workflows/2a0687a4-89f4-4ee6-b423-137146d62a96/jobs/15065)

Exclude more gRPC tests from sanitizer builds

---

cmd/test/consensus.cpp
core/silkworm/common/decoding_result.hpp
core/silkworm/consensus/base/engine.cpp
core/silkworm/trie/prefix_set.cpp
core/silkworm/trie/vector_root_test.cpp
core/silkworm/types/transaction.cpp
core/silkworm/types/transaction.hpp
core/silkworm/types/transaction_test.cpp
node/silkworm/stagedsync/stage_senders/recovery_farm.cpp

Update consensus tests to [v10.4](https://github.com/ethereum/tests/releases/tag/v10.4).
Also support decoding of typed transactions not wrapped into an RLP string.

Update consensus tests to 10.4

---

core/silkworm/consensus/base/engine.cpp
core/silkworm/consensus/base/engine.hpp

The body downloader needs to compute the transaction root and the hash of ommers.
This PR extracts the relevant code from pre_validate_block() and puts it in common.

Extract transaction_root & ommers_hash algorithms

---

cmd/backend_kv_server.cpp
node/silkworm/rpc/completion_end_point.cpp
node/silkworm/rpc/completion_end_point.hpp
node/silkworm/rpc/completion_end_point_test.cpp
node/silkworm/rpc/server/server.hpp
node/silkworm/rpc/server/server_config.cpp
node/silkworm/rpc/server/server_config.hpp
node/silkworm/rpc/server/server_context_pool.cpp
node/silkworm/rpc/server/server_context_pool.hpp
node/silkworm/rpc/server/server_context_pool_test.cpp
node/silkworm/rpc/server/wait_strategy.cpp
node/silkworm/rpc/server/wait_strategy.hpp
node/silkworm/rpc/server/wait_strategy_test.cpp

This PR plugs different wait strategies to handle idle cycles in the RPC server execution loop.
Also changes the BackEnd & KV standalone server to avoid logs when printing usage.

Wait strategies for RPC server

---

core/silkworm/consensus/base/engine.cpp
core/silkworm/consensus/base/engine.hpp
core/silkworm/consensus/engine.hpp
core/silkworm/consensus/merge/engine.cpp
core/silkworm/consensus/merge/engine.hpp
node/silkworm/downloader/internals/body_persistence.cpp
node/silkworm/downloader/internals/body_persistence_test.cpp
node/silkworm/downloader/internals/chain_integration_test.cpp

Body downloader only need to validate ommers. 
This PR 
- refactors _consensus::EngineBase_ `pre_validate_block()` introducing a `validate_ommers()` method
- in the body downloader replaces the call to `pre_validate_block()` with with `validate_ommers()`
Note that:
- ommers hash is computed elsewere
- for extensibility downloader calls `consensus::engine_factory()` to get a suitable consensus engine
- `consensus::engine_factory() `returns an object derived from _IEngine_ interface
so we had to add `validate_ommers() `to the _IEngine_ interface.
Reviewers knowing the details of the different consensus engine are asked to give a guidance here: is `validate_ommers()` meaningful in all consensus engine? do we need a more branched hierarchy to better state the differences between different …

Reduce body downloader validation expense

---

CMakeLists.txt

IMHO the good old [semantic versioning](https://semver.org/) is better than calendar-based versioning for our projects. For example, with the calendar versions in Erigon there's a discrepancy between the "Erigon 2" moniker and the actual versions.

Add PROJECT_VERSION

---

node/silkworm/downloader/block_exchange.cpp
node/silkworm/downloader/block_exchange.hpp
node/silkworm/downloader/internals/body_persistence.cpp
node/silkworm/downloader/internals/body_persistence.hpp
node/silkworm/downloader/internals/header_chain.cpp
node/silkworm/downloader/internals/header_chain.hpp
node/silkworm/downloader/internals/header_chain_test.cpp
node/silkworm/downloader/internals/preverified_hashes.cpp
node/silkworm/downloader/internals/preverified_hashes.hpp
node/silkworm/downloader/stage_bodies.cpp

This PR modifies the downloader so that it skips validation of ommers of bodies whose height is below the pre-verified hashes maximum height.
The downloader only check that ommers hash and transaction root hash of each body are the same of the correspondent header (really it is the contrary: a body is accepted if and only if the two hashes matches the hashes in the header).

A body downloader that exploits the pre-verified hashes

---

CMakeLists.txt
cmd/CMakeLists.txt
cmd/backend_kv_server.cpp
cmd/common.cpp
cmd/common.hpp
cmd/sentry.cpp
node/silkworm/rpc/server/server.hpp
sentry/CMakeLists.txt
sentry/sentry/options.cpp
sentry/sentry/options.hpp
sentry/sentry/server.cpp
sentry/sentry/server.hpp
sentry/sentry/service.cpp
sentry/sentry/service.hpp

* a separate folder/target for sentry builds a silkworm_sentry library (similar to silkworm_node)
* a new sentry.cpp command links with silkworm_sentry
* sentry GRPC Server is based on the silkworm::rpc::Server (similar to KV server) and a blank stub for the Service
* refactorings in common.cpp to be able to use some common CLI args setup logic

Sentry command with an empty GRPC service

---

node/silkworm/downloader/block_exchange.cpp
node/silkworm/downloader/block_exchange.hpp
node/silkworm/downloader/internals/body_sequence.cpp
node/silkworm/downloader/internals/body_sequence_test.cpp
node/silkworm/downloader/messages/inbound_block_bodies.cpp

On some test runs the downloader received many malformed messages. 
Tests seems to show that in such circumstances the downloader has a significative performance penalty.
The body downloader should penalize the corresponding peer so that Sentry will remove the buggy peer.

A body downloader that penalizes peers on malformed messages

---

interfaces/CMakeLists.txt
interfaces/p2psentry/sentry.grpc.pb.cc
interfaces/p2psentry/sentry.grpc.pb.h
interfaces/p2psentry/sentry.pb.cc
interfaces/p2psentry/sentry.pb.h
interfaces/remote/ethbackend.grpc.pb.cc
interfaces/remote/ethbackend.grpc.pb.h
interfaces/remote/ethbackend.pb.cc
interfaces/remote/ethbackend.pb.h
interfaces/types/types.pb.cc
interfaces/types/types.pb.h
node/silkworm/downloader/rpc/receive_peer_stats.cpp
node/silkworm/downloader/rpc/receive_peer_stats.hpp
node/silkworm/downloader/sentry_client.cpp

silkworm was referencing a "stable" interfaces branch.
I believe it should reference master as the purpose of "stable" is to cater the erigon stable (aka erigon1) needs.
It doesn't mean that we should always be on master, but while in development we should try to be as close as possible.
If silkworm is released to production for long-term support, it could have its own notion of stable interfaces (separate from erigon1, perhaps a custom branch).
Note: I need this for sentry to get the latest sentry.proto. Unfortunately I can't update only sentry.proto in isolation.

Update GRPC interfaces to master

---

.circleci/config.yml
core/silkworm/chain/genesis.cpp
core/silkworm/common/util.cpp
core/silkworm/common/util.hpp
core/silkworm/common/util_test.cpp
node/silkworm/common/directories.cpp
node/silkworm/db/util.hpp

Previously Silkworm build was [failing](https://app.circleci.com/pipelines/github/ethereum/evmone/2892/workflows/a7918891-4993-4817-b426-5eaabfc4d255/jobs/24408) with GCC 12, as reported by @chfast.

Fix GCC 12 build

---

cmd/sentry.cpp
sentry/sentry/nat_option.cpp
sentry/sentry/nat_option.hpp

Note: I've tried to use [this example](https://github.com/CLIUtils/CLI11/blob/main/examples/custom_parse.cpp) to parse my custom type. It says:
> the lexical cast operator should be in the same namespace as the type
but this didn't work (it tried using a builtin CLI::detail::lexical_cast instead, and didn't find mine).
So instead I had to manually call this function as [described here](https://github.com/CLIUtils/CLI11/blob/main/book/chapters/advanced-topics.md#custom-option-callbacks).
I wonder if this is because we are not using the latest CLI11 version? (How to find out which version is used?)

sentry: --nat and --port options

---

core/silkworm/common/base.hpp

[consteval](https://en.cppreference.com/w/cpp/language/consteval) is more restrictive than `constexpr`: it enforces compile-time execution. That's more accurate for user-defined literals since we don't want them to be executed at runtime.

consteval operator""

---

core/silkworm/common/base.hpp
core/silkworm/common/endian.hpp
core/silkworm/rlp/decode.cpp
core/silkworm/rlp/decode.hpp
core/silkworm/rlp/encode.cpp
core/silkworm/rlp/encode.hpp
core/silkworm/types/transaction.cpp

Introduce `UnsignedIntegral` concept equal to [std::unsigned_integral](https://en.cppreference.com/w/cpp/concepts/unsigned_integral) + [intx::uint](https://github.com/chfast/intx) types.

UnsignedIntegral concept

---

core/silkworm/common/base.hpp

Reverts torquem-ch/silkworm#704
After this PR MSVC does not build anymore due to :
```
error C7595: 'silkworm::operator ""_Tebi': call to immediate function is not a constant expression (compiling source file
```
Reverting

Revert "consteval operator"""

---

core/silkworm/common/base.hpp
core/silkworm/common/endian.cpp
core/silkworm/common/util.cpp

`human_size()` was not thread-safe because of the `static` buffer.
Also, Xcode 14 treats [sprintf](https://en.cppreference.com/w/cpp/io/c/fprintf) as deprecated.

Safer human_size

---

AUTHORS
core/silkworm/execution/evm.cpp
interfaces/CMakeLists.txt
node/silkworm/backend/state_change_collection.cpp
node/silkworm/etl/collector_test.cpp
node/silkworm/etl/file_provider.cpp
node/silkworm/rpc/server/server_context_pool.cpp
node/silkworm/stagedsync/stage_log_index.cpp
node/silkworm/stagedsync/stage_logindex/listener_log_index.cpp
node/silkworm/stagedsync/stage_logindex/listener_log_index.hpp
node/silkworm/stagedsync/stage_senders/recovery_farm.cpp
node/silkworm/stagedsync/stage_senders/recovery_farm.hpp
node/silkworm/types/log_cbor.cpp

Prior to this change `cmake -G Xcode ..` was failing with
```
CMake Error in interfaces/CMakeLists.txt:
The custom command generating
/Users/andrew/silkworm/interfaces/types/types.pb.cc
is attached to multiple targets:
generate_sentry_grpc
generate_kv_grpc
generate_ethbackend_grpc
but none of these is a common dependency of the other(s).  This is not
allowed by the Xcode "new build system".
```
When that was fixed, Xcode 14 complained about some conversions.

Fix Xcode 14 build

---

CMakeSettings.json
cmake/Hunter/config.cmake
cmake/compiler_settings.cmake
core/silkworm/common/base.hpp
node/silkworm/concurrency/coroutine.hpp
sentry/silkworm/sentry/common/random.cpp
sentry/silkworm/sentry/common/random.hpp
sentry/silkworm/sentry/rlpx/server.cpp
sentry/silkworm/sentry/rlpx/server.hpp

Small set of changes needed to restore Windows buildability.
Note for Clion users: as of latest Clion release up to 2022.08.05 [there are issues with Intellisense decting `awaitable` class template from Boost](https://youtrack.jetbrains.com/issue/CPP-28338). Nevertheless CLion can build using MSVC toolchain and tests ok.
Visual Studio 2019 have other issues : IDE properly detects `awaitable` class template but other intellisense errors appear
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0135	namespace "std" has no member "coroutine_handle"	silkworm_sentry.lib (sentry\Release\silkworm_sentry.lib) - x64-Release	C:\.hunter\_Base\10738b5\8e1c0b3\c8087bd\Install\include\boost\asio\awaitable.hpp	37	
Error (active)	E0135	namespace "std" has no member …
```

Re-enable Windows buildability

---

CMakeLists.txt

Update evmone to the final [v0.9.0](https://github.com/ethereum/evmone/releases/tag/v0.9.0).

Update evmone to v0.9.0

---

node/silkworm/downloader/internals/chain_integration_test.cpp
node/silkworm/downloader/internals/db_utils.cpp
node/silkworm/downloader/internals/header_persistence.cpp
node/silkworm/downloader/internals/header_persistence.hpp
node/silkworm/downloader/internals/header_persistence_test.cpp
node/silkworm/downloader/stage_headers.cpp

Now HeaderPersistence class gives different names to two different conditions.
The state "repaired" occurs when the previous "forward" run inserted new headers in the database but was unable to update the canonical chain due to an unwind condition detection. A subsequent "unwind" method execution reverted the canonical chain to the forking point. But the inserted headers are still there so the canonical chain has to be updated. HeaderPersistence detects this condition in the following forward execution and updates the canonical chain.

Downloader - Give different names to two different states

---

node/silkworm/downloader/sentry_client.cpp

This PR tries to solve issue #734

Downloader - Set gRPC max (incoming) message size to server default

---

cmd/common.cpp

Can't `get<uint64_t>()` on json members which are not numbers

ER Patch - Chain config MUST confront numbers with numbers

---

core/silkworm/common/util.hpp
node/silkworm/downloader/block_exchange.cpp
node/silkworm/downloader/internals/body_sequence_test.cpp
node/silkworm/downloader/internals/chain_elements_test.cpp
node/silkworm/downloader/internals/chain_integration_test.cpp
node/silkworm/downloader/internals/header_chain_test.cpp
node/silkworm/downloader/internals/priority_queue_test.cpp
node/silkworm/downloader/internals/sentry_type_casts.cpp
node/silkworm/downloader/internals/sentry_type_casts.hpp
node/silkworm/downloader/internals/sentry_type_casts_test.cpp
node/silkworm/downloader/internals/types.hpp
node/silkworm/downloader/messages/inbound_block_bodies.cpp
node/silkworm/downloader/messages/inbound_block_headers.cpp
node/silkworm/downloader/messages/inbound_get_block_bodies.cpp
node/silkworm/downloader/messages/inbound_get_block_bodies.hpp
node/silkworm/downloader/messages/inbound_get_block_headers.cpp
node/silkworm/downloader/messages/inbound_get_block_headers.hpp
node/silkworm/downloader/messages/inbound_new_block.cpp
node/silkworm/downloader/messages/inbound_new_block.hpp
node/silkworm/downloader/messages/inbound_new_block_hashes.cpp
node/silkworm/downloader/messages/inbound_new_block_hashes.hpp
node/silkworm/downloader/rpc/peer_min_block.cpp
node/silkworm/downloader/rpc/peer_min_block.hpp
node/silkworm/downloader/rpc/penalize_peer.cpp
node/silkworm/downloader/rpc/penalize_peer.hpp
node/silkworm/downloader/rpc/send_message_by_id.cpp
node/silkworm/downloader/rpc/send_message_by_id.hpp
node/silkworm/downloader/sentry_client.cpp

Erigon Sentry now uses pubkey as peer-id but pubkey has not printable characters.
This PR use Bytes in place of string to represent peer-id and use hex encoding to print peer-id.

Downloader printable peer-id

---

.circleci/config.yml

To fix spurious CI build failures after PR #756 (e.g. https://app.circleci.com/pipelines/github/torquem-ch/silkworm/5153/workflows/8617cf27-37ea-4ae0-b3b1-fd9cad37ed71/jobs/18345).

yacc is occasionally missing from CI machines

---

cmd/toolbox.cpp
core/silkworm/common/cast.hpp
node/silkworm/db/access_layer_test.cpp
node/silkworm/db/bitmap.cpp
node/silkworm/db/mdbx.cpp
node/silkworm/db/mdbx.hpp
node/silkworm/db/mdbx_test.cpp
node/silkworm/downloader/internals/db_utils.cpp
node/silkworm/stagedsync/_test.cpp
node/silkworm/stagedsync/stage_execution.cpp
node/silkworm/stagedsync/stage_history_index_test.cpp
node/silkworm/stagedsync/stage_interhashes/_test.cpp

Change
```
using WalkFunc = std::function<bool(::mdbx::cursor& cursor, ::mdbx::cursor::move_result& data)>
```
to
```
using WalkFuncRef = absl::FunctionRef<void(ByteView key, ByteView value)>
```
Rationale:
1. The early termination feature was unused, so no longer `bool` return.
2. The new function signature is simpler.
3. `absl::FunctionRef` is preferable to `const std::function&`: see C++26 proposal [P0792](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0792r10.html) for motivation.

Simplify signature of WalkFunc

---

cmd/toolbox.cpp

Voids all work done in stages occurring **after** download phase (i.e. Headers + Bodies) **and** Sender's recovery.
Useful to retest cycle execution.
`.\toolbox --datadir <path-to-data> --exclusive reset-to-download`
Note ! After this operation db is left with tons of freepages and on-disk file size is not shrinked.
For multiple tests is still better to keep a copy of downloaded data only.

New tool in toolbox : Reset to download

---

node/silkworm/common/log.cpp
node/silkworm/common/log.hpp
node/silkworm/common/log_test.cpp
node/silkworm/rpc/completion_end_point_test.cpp
node/silkworm/rpc/server/backend_kv_server_test.cpp
node/silkworm/rpc/server/server_context_pool_test.cpp
node/silkworm/rpc/server/server_test.cpp
node/silkworm/rpc/util_test.cpp
node/silkworm/test/log.hpp

This PR fixes a couple of failures in `node_test` when executed within CLion IDE that shuffles the execution order of tests.
The problem shows in `LogBuffer stores content for verbosity lower than or equal to default` test but it is indeed caused by other tests which change the default log verbosity _without_ restoring the default value at the end of the test.

Fix flaky log tests

---

cmd/silkworm.cpp
node/silkworm/downloader/internals/grpc_sync_client.hpp
node/silkworm/downloader/rpc/hand_shake.hpp
node/silkworm/downloader/sentry_client.cpp
node/silkworm/downloader/sentry_client.hpp

This PR fixes three conditions preventing Silkworm to execute a graceful termination:
- the sync-loop `Worker` sometimes remains stuck into the main loop because of a race condition in Worker thread termination that can leave it in the `Stopping` state instead of the expected `Stopped` state. Given that such loop is currently used only in `main`, adding an additional check temporarily solves the issue (#777 opened to track the problem)
- sync Sentry client remains stuck waiting for a connection in case the Sentry component is not reachable, thus preventing a clean shutdown
- sync Sentry client may remain stuck executing the `handshake` with the Sentry component, thus preventing a clean shutdown

Fix stop sequence for Silkworm executable

---

cmd/silkworm.cpp
node/silkworm/concurrency/_test.cpp
node/silkworm/concurrency/worker.cpp

This PR hopefully fixes a race condition in `Worker` termination state occurring between:
- the worker thread itself updating the state to `Stopped` before terminating
- any external thread calling `Worker::stop` method to stop the worker updating the state to `Stopping`
Fixes #777

Fix race condition in Worker termination state

---

node/silkworm/downloader/rpc/peer_count.hpp
node/silkworm/downloader/sentry_client.cpp
node/silkworm/downloader/sentry_client.hpp

This PR fixes an hang in sync Sentry client during the shutdown sequence of Silkworm. The issue is reproducible with 30% frequency in the following scenario:
- start Silkworm w/ Sentry down
- start Sentry and let Silkworm connect to it
- stop Sentry
- try to stop Silkworm sending Ctrl-C signal
The problem can be tracked down to the blocking `PeerCount` call.

Fix Sentry client shutdown hang in PeerCount RPC

---

cmd/backend_kv_server.cpp
cmd/common.cpp
cmd/common.hpp
cmd/downloader.cpp
cmd/silkworm.cpp
node/silkworm/rpc/server/call.hpp
node/silkworm/rpc/server/kv_calls.cpp

This PR integrates the BackEnd & KV gRPC server into Silkworm core component, also refactoring how some common options are handled. In particular:
- introduce some functions to add a single command-line option (e.g. `add_option_private_api_address `)
- support both tag and number values for enumerated options (e.g. `--log.verbosity 4` or `--log.verbosity info`)
- move function to build the node name in common place
- add BackEndKvServer startup to Silkworm main
- refactor command-line parsing in standalone Downloader executable

Integrate BackEndKV server in Silkworm core component

---

core/silkworm/execution/evm.cpp
core/silkworm/execution/evm.hpp
core/silkworm/execution/evm_test.cpp

This PR introduces a new `on_creation_completed` hook in EVM tracer.
Such hook is necessary because in `EVM::create` we modify the `evmc_result` returned by `evmone::execute` and thus we need to give the registered tracers a chance to see such changes.

Add creation completed hook to EVM tracer

---

.circleci/config.yml

This PR add a new job to our CI to prevent any error using the base build procedure as described in our README.
Requires #789

Add default build job to CI

---

CMakeLists.txt
cmake/Hunter/config.cmake
cmd/CMakeLists.txt
cmd/benchmark/CMakeLists.txt
cmd/benchmark/benchmark_test.cpp
node/silkworm/common/memory_mapped_file.cpp
node/silkworm/common/memory_mapped_file.hpp
node/silkworm/common/memory_mapped_file_benchmark.cpp
node/silkworm/common/memory_mapped_file_test.cpp

This PR adds a thin memory-mapped file implementation, based on [Aeron's one](https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/cpp/util/MemoryMappedFile.h), as part of the Snapshot Sync functionality. The motivation for introducing this memory-mapped file lies on the performance numbers captured in [its benchmark file](https://github.com/torquem-ch/silkworm/blob/105735fe7512ffc5fa8ffca9eb1358e2458e54ea/node/silkworm/common/memory_mapped_file_benchmark.cpp).
Exactly for the purpose of adding performance benchmarks, this PR includes also the following changes:
- add Google Benchmark as project dependency
- add new `benchmark_test` target built collecting all the benchmark files (i.e. any source code file matching *_benchmark.cpp)
Minor customization in Hunter …

Add memory-mapped file implementation

---

CMakeLists.txt

This PR moves the `CableBuildInfo` inclusion in CMake script to avoid this build warning:
```
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/GNUInstallDirs.cmake:239 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.
Call Stack (most recent call first):
third_party/evmone/cmake/cable/CableBuildInfo.cmake:16 (include)
CMakeLists.txt:28 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Avoid CMake warning w/o breaking default build

---

cmd/test/backend_kv_test.cpp
node/silkworm/rpc/server/backend_kv_server_test.cpp
node/silkworm/rpc/server/kv_calls.cpp
node/silkworm/rpc/server/kv_calls.hpp
node/silkworm/rpc/server/server_context_pool.cpp

This PR restores the max idle timeout handling in Tx RPC calls.
Moreover, it also introduces some related changes:
- switch back to `boost::asio` timers in Tx RPC calls
- use `boost::asio::dispatch` instead of `boost::asio::post` in StateChanges RPC notification handler
- avoid stopping `asio-grpc` server context on shutdown to make all handlers complete (this can slow down the shutdown in case of heavy load; ideally we could parameterise `rpc::Server::shutdown` and use `GrpcContext::stop` to have immediate shutdown, but let's keep it simple for now)
- restore temporarily disabled BackEndKV unit tests
- avoid completion queue drain in test client

Add max idle timeout in Tx RPC calls

---

node/silkworm/backend/backend_kv_server_test.cpp
node/silkworm/backend/rpc/kv_calls.cpp

This PR fixes a test failing intermittently due to too low timer granularity

Fix Tx RPC flaky test

---

cmd/test/backend_kv_test.cpp

`backend_kv_test` executable debug asserts with a vector subscript out of bounds because `channels` is empty. This happens if `--channels` is not specified to be > 0 so require that it is set using the CLI library

Require a number for --channels in backend_kv_test

---

cmd/CMakeLists.txt
cmd/check_senders.cpp

This PR adds a new tool called Check Sender to the `toolbox` that allows to check correctness of data stored into the `TxSender` table.

Add Check Senders tool

---

cmd/test/backend_kv_test.cpp

This PR change the default value for the `channels` parameter of the BackEnd&KV test client because at least one channel is necessary.

Change --channels parameter default value

---

core/silkworm/execution/address_test.cpp

Noticed there was only a `create` test.

Add create2 test

---

.circleci/config.yml
README.md
node/silkworm/downloader/sentry_client.cpp
node/silkworm/downloader/sentry_client.hpp

Sentry client has 2 threads: when the first is blocked waiting for connection to the sentry the second one spins. This PR avoid this.
Note that this PR uses std::atomic::wait, introduced in c++20,  that is not supported on gcc-10 so we removed the gcc-10 CI job.

Avoid sentry client consume cpu trying to connect to sentry

---

node/silkworm/downloader/internals/sentry_type_casts.cpp
node/silkworm/downloader/internals/types.hpp
node/silkworm/rpc/interfaces/types.cpp
node/silkworm/rpc/interfaces/types.hpp
node/silkworm/types/hash.hpp
sentry/silkworm/sentry/rpc/service.cpp

Sentry is using parts of downloader's sentry_type_casts.hpp which implements interfaces' types.proto helpers.
Those could be useful for other RPCs too.

sentry: refactor common RPC type conversions

---

.github/workflows/ci.yml

This PR shrinks the GitHub Actions workflow by
- disabling Linux jobs (already covered by CircleCI)
- removing Debug builds for Windows and macOS

Reduce Actions workflow jobs

---

cmd/test/consensus.cpp
core/silkworm/chain/config.cpp
core/silkworm/chain/config.hpp
core/silkworm/chain/config_test.cpp
core/silkworm/chain/difficulty.cpp
core/silkworm/chain/genesis.cpp
core/silkworm/common/test_util.hpp
core/silkworm/consensus/base/engine.cpp
core/silkworm/consensus/engine.cpp
core/silkworm/consensus/engine.hpp
core/silkworm/consensus/engine_test.cpp
core/silkworm/execution/evm.cpp
core/silkworm/execution/evm_test.cpp
core/silkworm/execution/processor.cpp
node/silkworm/stagedsync/stage_senders.cpp
wasm/silkworm_wasm_api.cpp
wasm/silkworm_wasm_api.hpp

Starting from [Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md), forks are triggered by block time rather than number. The old generic `evmc_fork_blocks` logic wasn't a good fit anymore, so I reverted to more hand-crafted code.

Shanghai fork is based on time rather than block number

---

core/silkworm/types/transaction.cpp
core/silkworm/types/transaction.hpp
node/silkworm/common/memory_mapped_file.cpp
node/silkworm/recsplit/rec_split.hpp
node/silkworm/recsplit/rec_split_test.cpp
node/silkworm/snapshot/decompressor.hpp
node/silkworm/snapshot/index.cpp
node/silkworm/snapshot/index.hpp
node/silkworm/snapshot/index_test.cpp
node/silkworm/snapshot/repository.cpp
node/silkworm/snapshot/repository.hpp
node/silkworm/snapshot/repository_test.cpp
node/silkworm/snapshot/snapshot.cpp
node/silkworm/snapshot/snapshot.hpp
node/silkworm/test/files.hpp
node/silkworm/test/snapshot_files.hpp

This PR adds the generation of Transaction indexes for the Snapshot Sync feature:
- tx hash -> offset index
- tx hash -> block number index

Add indexes generation for Transaction snapshot

---

sentry/silkworm/sentry/message_receiver.cpp

Do not co_await during subscriptions_ iteration.
When GRPC client disconnects, subscription is removed and messages_channel is closed. If this happens during messages_channel->send, receive_messages handles it and keeps going.

sentry: fix exception in MessageReceiver::receive_messages when GRPC disconnects

---

.github/workflows/ci.yml

This PR changes the GitHub Actions workflow to cancel the running execution on new commits on the same PR or branch.
This is obtained by using the same concurrency group for the current workflow on the same PR number or commit.
The same can be obtained in CircleCI by changing the `Auto-cancel redundant workflows` setting in `Advanced` section of `Project Settings` (just done, it should have immediate effect).

Cancel GA execution on new commits

---

node/CMakeLists.txt

This PR should fix the issues w/ TOML generated files during build by:
- listing all input/output files in TOML embedding
- fixing dependencies in `embed_toml` command and `generate_toml` target

Fix TOML embedding

---

.github/workflows/ci.yml
node/silkworm/recsplit/rec_split.hpp
sentry/silkworm/sentry/common/random.hpp

- There's a ccache step here on Windows, but it's not actually used, also it's experimental and only available in the bash shell which isn't used here so have removed it.
- Found a handy `Add-Content` to add to the path and other environment variables, allows it to be used in all subsequent steps too in the pscp shell
- `random_list_items` had a build issue with assignment operator `operator=` which is actually deleted because of the reference `container_` member variable. Didn't investigate the uses of it, just changed the member to a pointer.
- `M_PI` was not defined, apparently `_USE_MATH_DEFINES` is meant to work but doesn't seem to anymore. Now checking if using MSVC compiler and if `M_PI` is not defined then import `corecrt_math_defines.h`
- The recsplit test is failing on Windows, …

Fix github actions on Windows

---

cmd/snapshots.cpp
node/silkworm/bittorrent/bittorrent_client.cpp
node/silkworm/bittorrent/bittorrent_client.hpp
node/silkworm/bittorrent/bittorrent_client_test.cpp

This PR changes both the BitTorrent client API and the implementation, specifically:
- it is now possible to add a torrent file using just its info hash, relying on a fixed list of trackers
- the execution loop stop condition is properly handled using a condition variable
- the execution loop automatically completes if seeding is disabled and all added torrents have been downloaded (i.e. they are in seeding state)

node: refactor Bittorrent client

---

cmd/snapshots.cpp
node/silkworm/bittorrent/bittorrent_client.cpp
node/silkworm/bittorrent/bittorrent_client.hpp
node/silkworm/bittorrent/bittorrent_client_test.cpp
node/silkworm/db/access_layer.cpp
node/silkworm/db/access_layer.hpp
node/silkworm/db/access_layer_test.cpp
node/silkworm/db/util.hpp

This PR add support for snapshots in database access layer by adding:
- `read_snapshots` and `write_snapshots` functions to read/write the snapshot file list to/from the DatabaseInfo table
- `reset_map_sequence` to reset the bucket sequence number associated to any map

node: add snapshot support in access layer

---

cmd/snapshots.cpp
core/silkworm/common/base.hpp
node/silkworm/bittorrent/bittorrent_client.cpp
node/silkworm/bittorrent/bittorrent_client.hpp
node/silkworm/bittorrent/bittorrent_client_test.cpp
node/silkworm/db/access_layer.cpp
node/silkworm/db/access_layer.hpp
node/silkworm/db/access_layer_test.cpp
node/silkworm/db/util.hpp
node/silkworm/snapshot/decompressor_test.cpp
node/silkworm/snapshot/index.cpp
node/silkworm/snapshot/index_test.cpp
node/silkworm/snapshot/path.cpp
node/silkworm/snapshot/path.hpp
node/silkworm/snapshot/path_test.cpp
node/silkworm/snapshot/repository.cpp
node/silkworm/snapshot/repository.hpp
node/silkworm/snapshot/repository_test.cpp
node/silkworm/snapshot/settings.hpp
node/silkworm/snapshot/snapshot_test.cpp
node/silkworm/test/snapshots.hpp

This PR does some maintenance in snapshot package:
- refactor snapshot repository
- refactor snapshot test support and unit tests
- rename `SnapshotFileList` as `SnapshotPathList`
- rename `silkworm/test/snapshot_files.hpp` as `silkworm/test/snapshots.hpp`

node: refactor snapshot repository

---

node/silkworm/backend/backend_kv_server_test.cpp
node/silkworm/backend/rpc/kv_calls.cpp
node/silkworm/backend/rpc/kv_calls.hpp
node/silkworm/db/mdbx.cpp
node/silkworm/db/mdbx.hpp

Fixes #862 
Details:
- refactor Tx call to use awaitable operators correctly
- change deadline time-points to reschedule Asio timers
- fix unit test for max simultaneous Tx calls
- fix non-positioned cursors in max TTL save/restore
- add utility methods in db::Cursor

node: fix Tx RPC unit tests

---

node/silkworm/backend/backend_kv_server_test.cpp
node/silkworm/test/os.hpp

This PR makes test "BackEndKvServer E2E: Tx max simultaneous readers exceeded" fail *explicitly* if process max file descriptors are lower than 1024 on the underlying system.
As a matter of fact, such unit test needs to reach the max limit of simultaneous MDBX readers in order to start one more Tx and check that the error condition is handled nicely on server-side. In order to do so, the test opens up a lot of Tx calls and may or may not hit the default max open files limit, within the gRPC C++ library, depending on the underlying system settings. Unfortunately, when such limit is reached the gRPC C++ library crashes abruptly, so checking this condition in advance is necessary to avoid a segmentation fault.
When we will upgrade to Catch2 version 3.3.0, we can use `SKIP` macro to simply …

node: make test fail if max per-process descriptors are insufficient

---

silkworm/sentry/common/sleep.cpp
silkworm/sentry/common/sleep.hpp
silkworm/sentry/peer_manager.cpp
silkworm/sentry/peer_manager.hpp
silkworm/sentry/rlpx/peer.cpp
silkworm/sentry/rlpx/peer.hpp
silkworm/sentry/rlpx/ping_message.cpp
silkworm/sentry/rlpx/ping_message.hpp

* ping-pong logic
* fix: if Peer::handle quits without an exception Peer::start must quit too - use ||
* fix: PeerManager::on_peer_added/removed must not move multiple times in the loop
* fix: awaitable Peer::start/PeerManager::start_peer need to accept shared_ptr by value to make sure that it outlives the coroutine

sentry: RLPx Ping-Pong

---

silkworm/node/rpc/server/call_test.cpp

This PR just skips one flaky unit test counting server-side RPC call instances.

Skip server RPC test counting instances

---

silkworm/node/backend/backend_kv_server_test.cpp
silkworm/node/backend/rpc/kv_calls.cpp
silkworm/node/rpc/server/call_test.cpp

This PR amends the SEEK_EXACT operation in Tx RPC to return also the current value pointed after seek

Set current value in Tx RPC seek_exact operation

---

silkworm/core/CMakeLists.txt
silkworm/node/CMakeLists.txt
silkworm/sentry/CMakeLists.txt
silkworm/sync/CMakeLists.txt

This PR fixes build when Silkworm is used as submodule (e.g. in Silkrpc)

build: fix CMake variable for build as submodule

---

cmd/check_senders.cpp
silkworm/node/backend/rpc/kv_calls.cpp
silkworm/node/backend/rpc/kv_calls.hpp
silkworm/node/db/buffer_test.cpp
silkworm/node/db/mdbx.cpp
silkworm/node/db/mdbx.hpp
silkworm/node/db/memory_mutation.cpp
silkworm/node/db/memory_mutation.hpp
silkworm/node/db/memory_mutation_cursor.cpp
silkworm/node/db/memory_mutation_cursor.hpp
silkworm/node/db/memory_mutation_test.cpp

This PR substitutes each creation of `db::PooledCursor` with a call to one of the factory methods:
- `ROTxn::ro_cursor`
- `ROTxn::ro_cursor_dup_sort`
- `RWTxn::rw_cursor`
- `RWTxn::rw_cursor_dup_sort`
and adjusts the code accordingly. Other related changes include:
- move assignment operators for `ROTxn` and `RWTxn`
- switch from `RWTxn` to `ROTxn` for `MemoryMutation` external transaction

node: refactor database cursor creations to use factory methods

---

silkworm/node/db/memory_mutation.cpp
silkworm/node/db/memory_mutation.hpp
silkworm/node/db/memory_mutation_cursor.cpp
silkworm/node/db/memory_mutation_cursor.hpp
silkworm/node/db/memory_mutation_cursor_test.cpp
silkworm/node/db/memory_mutation_test.cpp

This PR introduces the following changes to the memory mutation abstraction:
- `to_first` API implementation
- creation of schema tables
- priority resolution for db and memory cursor

node: add to_first API implementation in memory mutation

---

CMakeLists.txt
cmd/rpcdaemon/CMakeLists.txt
cmd/rpcdaemon/ethbackend_coroutines.cpp
cmd/rpcdaemon/kv_seek_async_callback.cpp
cmd/rpcdaemon/kv_seek_async_coroutines.cpp
cmd/rpcdaemon/silkrpc_toolbox.cpp
examples/CMakeLists.txt
examples/get_latest_block.cpp
silkworm/silkrpc/API.md
silkworm/silkrpc/commands/ots_api.cpp
silkworm/silkrpc/commands/ots_api.hpp
silkworm/silkrpc/json/types.cpp

This PR continues the `SilkRpc` project integration. The main changes are:
- add the `examples` for usage of RpcDaemon as library
- add doc tracking JSON RPC API status progress
Moreover, this PR also removes warning suppression for RpcDaemon targets and fixes related errors

rpcdaemon: add examples folder and API doc

---

silkworm/node/db/memory_mutation_cursor.cpp
silkworm/node/db/memory_mutation_cursor.hpp
silkworm/node/db/memory_mutation_cursor_test.cpp

This PR introduces the following changes to memory mutation abstraction:
- add `to_current_next_multi` API implementation
- add `to_next_first_multi` API implementation
- refactor unit tests to reduce execution time

node: add to_current_next_multi + to_next_first_multi API in memory mutation

---

.gitmodules
CMakeLists.txt
silkworm/silkrpc/CMakeLists.txt

This PR add a new submodule for [glaze](https://github.com/stephenberry/glaze), a fast JSON library which is showing promising performance figures in `eth_getLogs` tests.

rpcdaemon: add glaze submodule

---

cmd/sentry.cpp
cmd/test/CMakeLists.txt
cmd/test/sentry_client_test.cpp
silkworm/node/backend/rpc/sentry_client.cpp
silkworm/node/rpc/client/call.cpp
silkworm/node/rpc/client/call.hpp
silkworm/sentry/CMakeLists.txt
silkworm/sentry/rlpx/client.cpp
silkworm/sentry/rpc/client/sentry_client.cpp
silkworm/sentry/rpc/client/sentry_client.hpp

* add sentry_client_test cmd to test the client API
* refactor unary_rpc to return replies
* wrap unary_rpc/streaming_rpc with reconnect/retry logic

sentry: reconnecting GRPC client with retries

---

cmake/profiles/windows_msvc_17_debug
cmake/profiles/windows_msvc_17_release
third_party/CMakeLists.txt

build: fix Windows MSVC build

---

silkworm/sync/sentry_client.cpp

This PR fixes the receiving stats loop in synchronous Sentry client, which hangs at termination if not connected to the Sentry component

sync: fix stats loop termination for Sentry client when disconnected

---

cmd/silkworm.cpp
silkworm/infra/concurrency/signal_handler.cpp

It is incorrect to explicitly close mdbx::env_managed if one R/W transaction is still open because it will cause a runtime error in mdbx_lck_destroy (the R/W transaction is in ExecutionEngine instance).
Let mdbx::env_managed and ExecutionEngine destructors do the cleanup in correct order:
- mdbx::env_managed constructor (create MDBX environment)
- ExecutionEngine constructor (create read/write mdbx::txn)
...
- ExecutionEngine destructor (delete read/write mdbx::txn)
- mdbx::env_managed destructor (delete MDBX environment)

node: avoid explicit MDBX close when the RW transaction is still open

---

silkworm/infra/common/directories.hpp
silkworm/node/snapshot/path.hpp
silkworm/node/snapshot/settings.hpp
silkworm/node/snapshot/sync.cpp

This PR applies the following changes:
- add snapshots subfolder in data directory structure (e.g. chain data/etl-temp/nodes/snapshots)
- change default value for snapshot data directory
- improve logging to include tag and snapshot data directory

node: add snapshots subfolder in data directory structure

---

silkworm/node/bittorrent/client.cpp
silkworm/node/snapshot/sync.cpp

This PR changes the initial snapshot sync introducing a proper way to wait for snapshot download completion using BitTorrent client signals

node: wait for snapshot download completion

---

silkworm/node/db/memory_mutation.cpp
silkworm/node/db/memory_mutation.hpp
silkworm/node/db/memory_mutation_cursor_test.cpp
silkworm/node/db/memory_mutation_test.cpp

This PR refactors `MemoryOverlay` into two classes: `MemoryDatabase` and `MemoryOverlay` to better encapsulate the overlay abstraction, that now contains both the in-memory database **and** the external r/o transaction to the overlayed database

node: refactor memory overlay

---

cmd/silkworm.cpp
silkworm/node/huffman/decompressor.cpp
silkworm/node/huffman/decompressor.hpp
silkworm/node/snapshot/path.hpp
silkworm/node/snapshot/repository.cpp
silkworm/node/snapshot/sync.cpp
silkworm/node/snapshot/sync.hpp

This PR introduces the following changes:
- increase max table patterns in snapshot decompressor
- add missing folder reopening in snapshot sync
- refactor raise max file descriptors in silkworm
- temporarily disable parallel index building
- demote log traces

node: snapshot full download

---

silkworm/infra/common/memory_mapped_file.cpp
silkworm/infra/common/memory_mapped_file.hpp
silkworm/node/snapshot/index.hpp
silkworm/node/snapshot/repository.cpp
silkworm/node/snapshot/repository.hpp
silkworm/node/snapshot/sync.cpp
silkworm/node/snapshot/sync.hpp

This PR introduces the following changes:
- make snapshot downloading and index building stoppable at boundaries
- split responsibilities between finding missing indexes and building them
- move snapshot index building from repository to sync

node: make snapshot downloading and index building stoppable at boundaries

---

.circleci/config.yml
cmake/compiler_settings.cmake
silkworm/core/crypto/sha256.c
silkworm/core/execution/precompile.cpp
silkworm/core/trie/node.cpp
silkworm/interfaces/CMakeLists.txt
silkworm/sync/messages/internal_message_test.cpp

[Undefined Behavior Sanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) can catch things like out-of-bounds array access.
Also fix/supress Clang 15 warnings.

build: run undefined alongside address sanitizer

---

silkworm/infra/grpc/common/conversion.cpp
silkworm/infra/grpc/common/conversion.hpp
silkworm/infra/grpc/common/conversion_test.cpp
silkworm/silkrpc/commands/engine_api_test.cpp
silkworm/silkrpc/ethbackend/backend.hpp
silkworm/silkrpc/ethbackend/remote_backend.cpp
silkworm/silkrpc/ethbackend/remote_backend.hpp
silkworm/silkrpc/ethbackend/remote_backend_test.cpp
silkworm/silkrpc/txpool/transaction_pool.cpp
silkworm/silkrpc/txpool/transaction_pool.hpp
silkworm/silkrpc/types/peer_info.hpp

This PR introduces the following changes:
- add ETHBACKEND Peers RPC client-side implementation
- move gRPC type conversion utilities into infra
- remove duplicated gRPC type conversion utilities

rpcdaemon: improve ETHBACKEND gRPC client implementation

---

cmd/common/common.cpp
silkworm/infra/concurrency/context_pool.cpp
silkworm/infra/concurrency/context_pool.hpp
silkworm/infra/concurrency/context_pool_settings.hpp
silkworm/infra/concurrency/context_pool_test.cpp
silkworm/infra/concurrency/idle_strategy.cpp
silkworm/infra/concurrency/idle_strategy.hpp
silkworm/infra/concurrency/idle_strategy_test.cpp
silkworm/infra/grpc/server/server_context_pool.cpp
silkworm/infra/grpc/server/server_context_pool.hpp
silkworm/infra/grpc/server/server_context_pool_test.cpp

This PR is a first step to separate responsibilites in our server-side execution context pool:
- a new class `concurrency::ContextPool` implements a pool of execution contexts based on `asio::io_context`
- the existing class `rpc::ServerContextPool` has been changed to wrap around `concurrency::ContextPool` the gRPC support for handling server-side gRPC communication
Please note that there is still another execution context pool in `rpcdaemon` called `silkworm::rpc::ContextPool` that:
- again implements a pool of execution contexts based on `asio::io_context`
- handles client-side `::grpc::CompletionQueue` instances for gRPC communication
- maintains both private and shared state in each execution context and in context pool
This class [to be renamed `silkworm::rpc::ClientContextPool`] is …

infra: separation between concurrency::ContextPool and rpc::ServerContextPool

---

cmd/common/sentry_options.cpp
cmd/sentry.cpp

cmd: move logging options out of common sentry options

---

silkworm/infra/concurrency/awaitable_future.hpp
silkworm/infra/concurrency/awaitable_future_test.cpp

Add to Infra package a couple of classes that 
- mimic the interface and the structure of standard future/promise
- work well with asio, supporting different patterns of usage (coroutine/future/etc.)
Their implementation is copied from the existing Sentry's AwaitablePromise but unlike it they break the class into two halves as standard classes do by dividing the interface that the producer uses from the interface that the consumer uses. This makes it possible to decouple the two better and pass the future to a consumer in another component.

infra: future/promise compatible w/ different Asio completion tokens

---

cmd/test/ethereum.cpp

[v12](https://github.com/ethereum/tests/releases/tag/v12) -> [v12.2](https://github.com/ethereum/tests/releases/tag/v12.2)

third_party: upgrade ethereum EL tests to v12.2

---

silkworm/core/common/lru_cache.hpp
silkworm/core/execution/evm.cpp

In case of multi-thread access the `lru_cache::get` method must not be used because returns address of internal map: I have inserted an assertion to avoid this misuse and made some changes to protect `lru_cache::get_as_copy`, which is now thread-safe

core: fix multi-thread access in lru_cache

---

silkworm/infra/concurrency/sync_wait.hpp
silkworm/infra/concurrency/sync_wait_test.cpp

**Doing an asynchronous wait of a coroutine is easy**:
`auto result = co_await task();`
**Doing a synchronous wait of a coroutine is more verbose**:
`auto result = asio::co_spawn(io_context, task(), asio::use_future).get();`
also, this exposes implementation details.
**Using the simple sync_wait() function of this PR, the call becomes**:
`auto result = sync_wait(io_context, task());`
so at the call site, the intent of the code becomes clearer.
A simple getter enables us to simplify the code further when the io_context is not available in the scope and we need to get it from get_executor() method:
`auto result = sync_wait(in(this), task());`

infra: sync_wait

---

silkworm/infra/concurrency/base_service.hpp
silkworm/infra/concurrency/context_pool.hpp
silkworm/infra/concurrency/private_service.hpp
silkworm/infra/concurrency/private_service_test.cpp
silkworm/infra/concurrency/shared_service.hpp
silkworm/infra/concurrency/shared_service_test.cpp
silkworm/infra/grpc/client/client_context_pool.cpp
silkworm/infra/grpc/client/client_context_pool.hpp
silkworm/infra/grpc/client/client_context_pool_test.cpp

This PR introduces:
- refactoring and extraction of gRPC context pool running `rpcdaemon` (i.e. `silkrpc`) into a cleaner `ClientContextPool` based on `concurrency::ContextPool` and unaware of `rpcdaemon` (i.e. `silkrpc`) internal state
- add private and shared service abstractions based on service registry available in `boost::asio::io_context`, which will be used in following PR to attach the `rpcdaemon` (i.e. `silkrpc`) internal state to `ClientContextPool`
This is just the first PR in a row aimed at refactoring some modules out of `rpcdaemon` (i.e. `silkrpc`) to move Engine JSON API service into `sync`.

infra: add gRPC client context pool and services

---

cmd/backend_kv_server.cpp

Bug fixes:
- avoid multiple calls to `rpc::BackEndKvServer::build_and_start`
- refactor state changes simulator as async task
Bonus:
- use RAII for cleanup
- replace `rpc::ServerContextPool` w/ `rpc::ClientContextPool` (no more dummy `::grpc::ServerCompletionQueue`)
Fixes #1054

fix: avoid startup crash in backend_kv_server

---

silkworm/node/backend/remote/backend_kv_server_test.cpp
silkworm/sentry/api/api_common/node_info.hpp
silkworm/sentry/api/api_common/peer_info.hpp
silkworm/sentry/grpc/interfaces/node_info.cpp
silkworm/sentry/grpc/interfaces/peer_id.cpp
silkworm/sentry/grpc/interfaces/peer_id.hpp
silkworm/sentry/grpc/interfaces/peer_info.cpp
silkworm/sentry/peer_manager_api.cpp
silkworm/sentry/sentry.cpp

Problem:
PeerInfo/NodeInfo that erigon sentry returns contains a `string id` field
that is a hex representation of a 32 byte Keccak256Hash of a real H512 64 byte peer ID.
When silkworm sentry client tries to decode it as a peer ID, it fails.
Solution:
Do not use this GRPC value on the client.
Note: if needed, it can be obtained on the client side from the `url` field by using:
string id = to_hex(keccak256(peer_info.url.public_key().serialized()));
but hopefully we shouldn't use for anything as it just gets confusing for no reason.
Note 2: in the past erigon and sentry.proto was using H256 hash for the peer_id-s too, but it was converted to full H512. But PeerInfo.id/NodeInfo.id was not converted for some reason. Omission?

sentry: fix PeerInfo node ID compatilibity

---

silkworm/infra/concurrency/task.hpp

This PR is intentionally tiny: it just introduces an asynchronous task type definition named `silkworm::Task`, usable in place of `boost::asio::awaitable`, which currently is used pretty everywhere.
Benefits:
- improve code readability and terseness (short-term)
- put in one place some required header inclusions
- open up the possibility for our own coroutine `awaitable` implementation (long-term, not sure about this: I still hope the C++ standard will fill this hole)
I would like to receive feedback about this (e.g. naming and location) before applying the changes to the code: it will be a huge PR, that I will probably do on Sunday 😃

infra: add awaitable task definition

---

cmd/CMakeLists.txt
cmd/rpcdaemon/CMakeLists.txt
third_party/CMakeLists.txt

The change is required to fix an issue with `mimalloc` static library on Apple Silicon that causes `silkrpcdaemon` to crash with code `EXC_BAD_ACCESS` in blocking gRPC calls during interface protocol negotiations when gRPC server is down.
Apparently, switching back to shared library fixes the issue.

build: link `mimalloc` as shared library

---

silkworm/silkrpc/commands/engine_api.cpp
silkworm/silkrpc/commands/engine_api_test.cpp
silkworm/silkrpc/ethbackend/backend.hpp
silkworm/silkrpc/ethbackend/remote_backend.cpp
silkworm/silkrpc/ethbackend/remote_backend.hpp
silkworm/silkrpc/ethbackend/remote_backend_test.cpp
silkworm/silkrpc/json/execution_payload.cpp
silkworm/silkrpc/json/execution_payload.hpp
silkworm/silkrpc/json/execution_payload_test.cpp
silkworm/silkrpc/json/fork_choice.cpp
silkworm/silkrpc/json/fork_choice.hpp
silkworm/silkrpc/json/fork_choice_test.cpp
silkworm/silkrpc/json/payload_attributes.cpp
silkworm/silkrpc/json/payload_attributes.hpp
silkworm/silkrpc/json/payload_attributes_test.cpp
silkworm/silkrpc/json/transition_configuration.cpp
silkworm/silkrpc/json/transition_configuration.hpp
silkworm/silkrpc/json/transition_configuration_test.cpp
silkworm/silkrpc/json/types.cpp
silkworm/silkrpc/json/types.hpp
silkworm/silkrpc/json/types_test.cpp
silkworm/silkrpc/types/execution_payload.cpp
silkworm/silkrpc/types/execution_payload.hpp
silkworm/silkrpc/types/execution_payload_test.cpp
silkworm/sync/engine_api_backend.cpp
silkworm/sync/engine_api_backend.hpp
silkworm/sync/sync_pos.cpp
silkworm/sync/sync_pos.hpp

This PR restores previous version-unaware naming for internal classes and functions dealing with Engine API because it seems better to handle different versions using simply a field, as it is done in internal gRPC `ethbackend`.
So for example in `ExecutionPayload` struct:
```
struct ExecutionPayload {
uint32_t version{1};
// ... omissis ...
std::optional<std::vector<Withdrawal>> withdrawals{std::nullopt};  // present iff version=2
};
```
we use a dedicated field to track the version [this will be an enum in next PR] and optional fields for version-specific stuff (e.g. withdrawals).

rpcdaemon, sync: Engine API versioning

---

silkworm/core/crypto/rmd160.c
silkworm/core/crypto/rmd160.h
silkworm/core/execution/precompile.cpp

The type of `len` in `rmd160_finish` is `uint32_t`, so it should be the same in `silkworm_rmd160`.

core: correct type of len in silkworm_rmd160

---

silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/stages/stage_finish.cpp

Pipeline state must be computed even when we stop due to stop_at_block environment var

node: fix pipeline state using stop_at_block env var

---

.circleci/config.yml
conanfile.txt

This uses a prebuilt version from conancenter.
apt-get update to fix "Install llvm" failure:
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/g/gcc-11/libobjc-11-dev_11.3.0-1ubuntu1%7e22.04_amd64.deb 404 Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

build: update GRPC to 1.48.0 + fix llvm installation in CI

---

.circleci/config.yml
cmd/CMakeLists.txt

This PR moves the format check from integration CI to light CI in order to avoid detecting format errors just after merging on master, as happened for #1172.

CI: move format check from integration to light

---

.circleci/config.yml

Saves 50-60 sec, mostly on the submodule git clone.

CI: disable ethereum EL tests on light PR workflow

---

silkworm/infra/concurrency/awaitable_future.hpp
silkworm/infra/concurrency/awaitable_future_test.cpp

This PR improves the cancellation handling in `AwaitablePromise` and `AwaitableFuture` classes:
- make them compatible the cancellation mechanism used by Asio async operations by remapping `channel_cancelled` error code in `operation_canceled` to abstract away implementation details (i.e. usage of `asio::basic_concurrent_channel`)
- close the underlying `asio::basic_concurrent_channel` in case of cancellation in order to make such condition detectable at the sender side (no runtime exception in this case because it is not a programming error)

infra: handle cancellation in awaitable promise and future

---

silkworm/sentry/rlpx/peer.cpp

Check to avoid setting the handshake promise more than once in `Peer::handle`.

sentry: set value in Peer handshake promise only once

---

silkworm/core/crypto/sha256.c

Move `w[16]` buffer outside of the outer loop. Otherwise, `w` goes out of scope in every outer loop iteration and uninitialized memory is used. This bug has become visible by building with GCC 13 in Release.
I restored the correct location of `w[16]` as in the original implementation at
https://github.com/amosnier/sha-2/blob/5beabbcc0d872e15a16d51539922dbfabb806316/sha-256.c#L40-L53. The code was introduced already with the bug in
https://github.com/torquem-ch/silkworm/pull/113.
Fixes https://github.com/torquem-ch/silkworm/issues/1191.

core: fix uninitialized memory in SHA256

---

.gitmodules
CMakeLists.txt
cmd/dev/CMakeLists.txt
conanfile.txt
silkworm/node/CMakeLists.txt
third_party/CMakeLists.txt

This partially reverts PR #1199 because apparently the version of libtorrent from Conan is causing a failure in [linux-clang-address-sanitizer](https://app.circleci.com/pipelines/github/torquem-ch/silkworm/7660/workflows/e8cbfd41-c549-4efc-9a04-f4ad0f8ad195/jobs/33993).

build: move libtorrent back to third_party

---

silkworm/silkrpc/core/remote_state.cpp
silkworm/silkrpc/core/remote_state_test.cpp
silkworm/silkrpc/daemon.cpp
silkworm/silkrpc/daemon.hpp
silkworm/silkrpc/ethdb/file/local_cursor.cpp
silkworm/sync/sync.cpp
silkworm/sync/sync.hpp

rpcdaemon: throw in unimplemented methods

rpcdaemon: use shared chaindata MDBX env in embedded execution

---

silkworm/sync/sentry_client.cpp
silkworm/sync/sentry_client.hpp

The count can go out of sync for various reasons.
Update it on each peer event instead.
Remove unused peer_infos_ map.
see: https://github.com/ledgerwatch/interfaces/issues/168

sync: refactor receive_peer_events to not rely on incremental active_peers updates

---

silkworm/node/recsplit/rec_split_test.cpp

This is a way to overcome issue #1248

node: exclude RecSplit tests from Windows build due to access issues

---

cmd/test/unit_test.cpp
silkworm/node/backend/remote/backend_kv_server_test.cpp

backend_kv_server_test.cpp(898): FAILED:
explicitly with message:
insufficient number of process file descriptors, increase to 1024 at least

windows: raise tests file descriptors limit

---

cmd/state-transition/state_transition.cpp
silkworm/core/execution/processor.cpp
silkworm/core/execution/processor.hpp
silkworm/core/execution/processor_test.cpp
silkworm/core/protocol/validation.cpp
silkworm/core/protocol/validation.hpp
silkworm/core/protocol/validation_test.cpp

Logically `validate_transaction` should sit next to `pre_validate_transactions`

core: move validate_transaction to protocol/validation

---

cmd/state-transition/state_transition.cpp
silkworm/core/common/test_util.cpp
silkworm/core/execution/execution_test.cpp
silkworm/core/protocol/intrinsic_gas_test.cpp
silkworm/core/protocol/validation.cpp
silkworm/core/protocol/validation_test.cpp
silkworm/core/types/block_test.cpp
silkworm/core/types/transaction.cpp
silkworm/core/types/transaction.hpp
silkworm/core/types/transaction_test.cpp
silkworm/node/db/access_layer_test.cpp
silkworm/silkrpc/common/util_test.cpp
silkworm/silkrpc/json/types.cpp
silkworm/silkrpc/json/types_test.cpp
silkworm/silkrpc/types/transaction_test.cpp

Use the same names as Erigon does. For example, "DynamicFee" is arguably prettier/more explanatory than "eip1559".

core: erigon names for tx types

---

silkworm/infra/grpc/common/util_test.cpp

"gpr_silkworm_log" test was setting the log level to DEBUG, and causing the version_test.cpp to output a lot of GRPC logs such as:
D0613 22:01:14.032745000 4493108736 lb_policy_registry.cc:48 registering LB policy factory for ...
see:
https://github.com/torquem-ch/silkworm/actions/runs/5260251264/jobs/9506908032

infra: fix infra_test spamming the test log

---

silkworm/silkrpc/core/evm_trace.cpp

rpcdaemon: rework worker thread for: 
- handle_ots_trace_transaction
-  handle_ots_get_transaction_error
- handle_ots_get_contract_creator
-  trace_cal
-  trace_transaction

rpcdaemon: move state creation to worker thread in TraceCallExecutor

---

silkworm/node/huffman/decompressor.cpp
silkworm/node/huffman/decompressor.hpp
silkworm/node/snapshot/snapshot.cpp

We should improve handling of `invalid zero word length` case

node: fix overflow in snapshot decompressor

---

silkworm/infra/test_util/dummy.cpp

Quick fix to restore build on macOS platform with Apple clang version 14.0.3 (clang-1403.0.22.14.1) by adding dummy empty compilation unit:
```
[ 48%] Linking CXX static library libsilkworm_infra_test_util.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
ar -m [-TLsv] archive file ...
ar -m [-abiTLsv] position archive file ...
ar -p [-TLsv] archive [file ...]
ar -q [-cTLsv] archive file ...
```
This is not ideal because of the dummy source file and the following warning:
```
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: libsilkworm_infra_test_util.a the table of contents is empty (no object file members in the library define global symbols)
```

infra: fix silkworm_infra_test_util build on macOS

---

silkworm/silkrpc/core/evm_debug.hpp
silkworm/silkrpc/core/evm_debug_test.cpp

First step to refine DebugExecutor and its test: execute method set as protected

rpcdaemon: refactoring DebugExecutor unit test step 1

---

silkworm/node/db/mdbx.cpp
silkworm/node/db/mdbx.hpp

Fixes also Windows build broken after merging #1327

node: more ROTxn/RWTxn refactoring

---

silkworm/silkrpc/commands/eth_api.cpp
tests/integration/goerly/eth_getBlockByNumber/test_12.json

This PR contains: 
- getBlockByHash modified to support snapshot
- modified code of getBlockByNumber to manage case of  block number not found as expected case

rpcdaemon: get block by hash with snapshot

---

.circleci/config.yml
README.md

m4 texinfo bison are not required anymore, because GMP comes prebuilt from Conan.

CI: remove extra apt packages

---

silkworm/node/snapshot/index_test.cpp
silkworm/node/snapshot/repository_test.cpp
silkworm/node/snapshot/snapshot_test.cpp
silkworm/node/test/files.hpp

Fix TemporaryFile on Win specifying binary mode; 
re-enable snapshots tests

snapshots: fix TemporaryFile for unit tests on Windows

---

silkworm/silkrpc/commands/eth_api.cpp

Adapts followings API to snapshot:
- eth_getTransactionByBlockHashAndIndex
- eth_getRawTransactionByBlockHashAndIndex
- eth_getTransactionByBlockNumberAndIndex
- eth_getRawTransactionByBlockNumberAndIndex

rpcdaemon: adapt eth_getRawTransactionByBlock... and eth_getTransactionByBlock to snapshots

---

cmd/dev/snapshots.cpp
silkworm/api/silkworm_api.cpp
silkworm/node/snapshot/index.cpp
silkworm/node/snapshot/path.cpp
silkworm/node/snapshot/path_test.cpp
silkworm/node/snapshot/repository.cpp
silkworm/node/snapshot/snapshot.cpp
silkworm/node/snapshot/snapshot.hpp
silkworm/node/snapshot/snapshot_test.cpp
silkworm/node/test/snapshots.hpp

This PR contains:
- some refactoring to use less parameters in `Snapshot` constructors
- stricter checks in `SnapshotPath` when built from file system path

cmd, api, node: snapshot refactoring

---

silkworm/sync/sync.cpp

engine_rpc_server_ is null, because Sync::force_pow() is called and resets it

sync: fix crash in Sync::start_chain_sync

---

silkworm/node/db/access_layer.cpp
silkworm/sync/sync.cpp

repository_ is null if started with --snapshots.enabled=false

snapshots: fix crash in DataModel::for_last_n_headers

---

silkworm/node/db/access_layer.cpp
silkworm/node/db/access_layer.hpp
silkworm/node/db/access_layer_test.cpp
silkworm/silkrpc/commands/rpc_api_test.cpp

node: add roundtrip unit test for block body w/ withdrawals
rpcdaemon: refactor RPC IO unit test

node: reduce number of parameters and refactor write_tx_lookup

---

silkworm/silkrpc/commands/rpc_api_test.cpp

Exclude RPC IO tests from being compiled and run in CI sanitiser builds because of ASAN/TSAN errors inside gRPC library.
This happens in some other unit tests of ours and probably could be avoided by rebuilding gRPC library w/ sanitiser support in our CI sanitiser builds, but this requires time to be done and above all would result in longer build times for our integration CI. As a consequence, we decided to simply skip the offending tests just in CI sanitiser builds.

rpcdaemon: exclude RPC IO tests from ASAN/TSAN builds

---

silkworm/infra/grpc/common/version.hpp
silkworm/infra/grpc/common/version_test.cpp

rpcdaemon: modify ethbackend version from 3.2 to 3.3

---

silkworm/sync/internals/header_chain.cpp
silkworm/sync/internals/header_only_state.cpp
silkworm/sync/internals/header_only_state.hpp

Currently there are two issues in `sync` module related to block header difficulty:
- missing implementation of `State::total_difficulty` in header chain state subclass
- wrong check on header difficulty when PoS is activated
This PR does *not* solve such issues, but introduces two workarounds that at least do the job for Ethereum mainnet when using snapshots with max block greater or equal to 16'000'000.

sync: workarounds for difficulty and total difficulty in header chain

---

silkworm/infra/concurrency/task_group.cpp
silkworm/infra/concurrency/task_group.hpp
silkworm/infra/concurrency/task_group_test.cpp

Before this if a task didn't have a top level try/catch, it would lead to the io_context exiting.
Now the semantics is similar to awaitable_wait_for_all &&: if one of the tasks throws,
we cancel the other tasks and rethrow the exception to the `wait()` suspension point.

infra: rethrow unhandled exceptions from TaskGroup::wait

---

silkworm/node/snapshot/snapshot.cpp
silkworm/node/snapshot/snapshot.hpp
silkworm/node/snapshot/snapshot_test.cpp

This contains also:
- some refactoring to avoid unnecessary code duplication
- more unit tests

node: fix payload offset for non-legacy transaction in TransactionSnapshot

---

silkworm/silkrpc/core/evm_trace.cpp
tests/integration/run_tests.py

Bugfix implemented, resolving the program freezing glitch during calls to ots_getInternalOperations API using remote database.

rpcdaemon: move state creation to worker thread in TraceCallExecutor::trace_operations

---

silkworm/api/silkworm_api.cpp
silkworm/api/silkworm_api.h

Add `write_change_sets` and `write_call_traces` flags in `silkworm_execute_blocks` definition *just* at the interface level.
Current implementation simply returns `SILKWORM_NOT_IMPLEMENTED_ERROR` if such flags are enabled at call site.

api: add write flags for state changes and call traces in block execution [WIP]

---

silkworm/silkrpc/commands/erigon_api.cpp

Accept incoming block in `Erigon_getHeaderByNumber` both as string and as integer: this is needed because Otterscan web application sends a plain integer value

rpcdaemon: accept both string and integer as block in erigon_getHeaderByNumber

---

third_party/cmake-conan/conan.cmake

On some configurations/platforms cmake doesn't find conan when installed locally.
It is possible to specify directories to search in addition to the default locations using PATHS in find_program.
So this PR proposes to change:
`find_program(CONAN_CMD conan)`
in
`find_program(CONAN_CMD conan PATHS ~/.local/bin)`
as proposed [here](https://github.com/conan-io/cmake-conan/pull/359)

conan: improve searching of conan executable

---

silkworm/node/db/bitmap.cpp
silkworm/node/db/bitmap.hpp
silkworm/node/stagedsync/stages/stage_log_index.cpp

For binary compatibility with Erigon 2 database

node: use uint32 roaring bitmaps in LogIndex stage

---

silkworm/core/execution/evm.cpp

Post-fix to PR #1472. Some execution-spec tests use timestamps > INT64_MAX.

Fix tests under debug (remove failing assert)

---

silkworm/core/protocol/clique_rule_set.hpp
silkworm/silkrpc/core/evm_trace_test.cpp

Modify clique base class from ethash to BaseRuleSet, So in case of Clique the compute_reward() is defined in BaseRuleSet class(return empty value) and not ethash compute_reward() that returns a real reward

rpcdaemon: modify base class of clique consensus

---

silkworm/silkrpc/json/fork_choice.cpp
silkworm/silkrpc/json/fork_choice_test.cpp
silkworm/silkrpc/json/types.cpp
silkworm/silkrpc/json/types.hpp
silkworm/silkrpc/json/types_test.cpp

See [spec](https://ethereum.github.io/execution-apis/api-documentation/)

rpcdaemon: fix payloadId serialization in ForkChoiceUpdateReply

---

silkworm/node/common/settings.hpp
silkworm/node/stagedsync/execution_engine.cpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/execution_pipeline.hpp
silkworm/node/stagedsync/forks/main_chain.cpp
silkworm/node/stagedsync/forks/main_chain.hpp
silkworm/node/stagedsync/forks/main_chain_test.cpp
silkworm/node/stagedsync/local_client.cpp
silkworm/node/stagedsync/server.cpp
silkworm/node/stagedsync/stages/stage.hpp
silkworm/node/stagedsync/stages/stage_execution.cpp

node: handle already existing canonical block in main chain verification
node: avoid committing changes for invalid block in Execution stage

node: revalidate canonical chain with one forward cycle at startup

---

CMakeLists.txt
cmd/api/CMakeLists.txt
cmd/dev/CMakeLists.txt
cmd/state-transition/CMakeLists.txt
silkworm/infra/CMakeLists.txt
silkworm/infra/test_util/CMakeLists.txt
silkworm/node/CMakeLists.txt
silkworm/sentry/CMakeLists.txt
silkworm/sentry/common/CMakeLists.txt
silkworm/sentry/discovery/disc_v4/CMakeLists.txt
silkworm/sentry/discovery/node_db/CMakeLists.txt
silkworm/silkrpc/CMakeLists.txt

Previously some files referred to Boost::thread by mistake.

cmake: use Boost::headers for asio

---

silkworm/core/state/in_memory_state.cpp
silkworm/core/state/in_memory_state.hpp
silkworm/core/state/state.hpp
silkworm/core/types/call_traces.hpp
silkworm/node/db/buffer.cpp
silkworm/node/db/buffer.hpp
silkworm/silkrpc/core/local_state.hpp
silkworm/silkrpc/core/override_state.hpp
silkworm/silkrpc/core/remote_state.hpp

core: do not use Abseil containers in call traces

node: insert call traces in state buffer

---

silkworm/core/execution/evm.cpp
silkworm/core/execution/evm.hpp
silkworm/core/state/delta.cpp
silkworm/core/state/delta.hpp
silkworm/core/state/intra_block_state.cpp
silkworm/core/state/intra_block_state.hpp

This implements the EIP-1153: "Transient storage opcodes"
https://eips.ethereum.org/EIPS/eip-1153.
- The `IntraBlockState` is extended with transient storage
map account => (map key => value).
- The state journal is able to track transient storage changes with
new class `TransientStorageChangeDelta`.
- evmone/EVMC are upgraded.
This has been tested with EIP-4788 disabled on:
- https://github.com/ethereum/tests/tree/develop/EIPTests/BlockchainTests/bcEIP1153-transientStorage
- https://github.com/ethereum/tests/tree/develop/EIPTests/BlockchainTests/StateTests/stEIP1153-transientStorage

Implement transient storage (EIP-1153)

---

silkworm/node/snapshot/index.hpp

Bucket size in snapshot indexes needs to be slightly larger than 2000 bytes.
Setting this size to 2000 bytes is not a bug but may cause a performance penalty

snapshot: increase index bucket size

---

silkworm/core/execution/evm_test.cpp
silkworm/core/state/intra_block_state.cpp

We came across a bug that you probably did not see but could happen to you too if you're unlucky.
We run a version of your repo, but we reuse the IntraBlockState for several blocks to reduce DB access, and at a certain block we came across a validation error. There is a test case in to reproduce the errors and as you will see it is quite unlikely to happen, but if unlucky it definitely could with your code as well.
There is a case where when creating a contract, if the address selfdestructed before, the incarnation is not updated properly, which leads to the storage of the destructed contract to remain accessible by the new one.
I believe the fix for that is proper, but I am open to make it better :-)

Add test and fix for rare case of destruct followed by create

---

.circleci/config.yml
silkworm/node/stagedsync/stages/stage_history_index_test.cpp
silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
third_party/libmdbx/CMakeLists.txt

node: avoid spurious output during unit test execution

third_party: fix MDBX issues in UBSAN build

---

.circleci/config.yml
third_party/libmdbx/CMakeLists.txt

Downgrade MDBX version to [1cac65](https://github.com/erigontech/libmdbx/tree/1cac65363763e7523ed3b52eed8f2c617cead973) compatible with Erigon2.
This reverts #1560 and MDBX-related changes introduced in #1563

third_party: restore libmdbx version to 1cac65

---

silkworm/sentry/discovery/disc_v4/discovery.cpp
silkworm/sentry/discovery/disc_v4/ping/message_handler.hpp
silkworm/sentry/discovery/disc_v4/ping/ping_handler.cpp
silkworm/sentry/discovery/disc_v4/ping/ping_handler.hpp
silkworm/sentry/discovery/disc_v4/ping/ping_message.hpp
silkworm/sentry/discovery/disc_v4/server.cpp
silkworm/sentry/discovery/disc_v4/server.hpp
silkworm/sentry/discovery/discovery.cpp
silkworm/sentry/discovery/node_db/node_db.hpp
silkworm/sentry/discovery/node_db/node_db_sqlite.cpp
silkworm/sentry/discovery/node_db/node_db_sqlite_test.cpp
silkworm/sentry/discovery/node_db/serial_node_db.cpp
silkworm/sentry/discovery/node_db/serial_node_db.hpp

Add a new node to the ping check queue and ping immediately.
This is needed for erigon's [ensureBond()](https://github.com/ledgerwatch/erigon/blob/d62ef03cad02754795199c5e00d01fb53eeecaeb/p2p/discover/v4_udp.go#L600) to work,
otherwise ENRRequest and FindNode requests from new nodes are ignored
(even if they ping us first).
See erigon's v4_udp.go handlePing "Ping back":
https://github.com/ledgerwatch/erigon/blob/d62ef03cad02754795199c5e00d01fb53eeecaeb/p2p/discover/v4_udp.go#L701
bug fix:
Sending multiple UDP messages didn't work,
because bind() fails with "address is busy".
We have to use the same port on both client and server sockets,
so instead let's reuse the socket.

sentry: disc v4 ping back

---

silkworm/core/chain/config.cpp
silkworm/core/chain/config.hpp
silkworm/core/common/base.hpp
silkworm/core/common/test_util.cpp
silkworm/core/common/test_util.hpp

For some reason gcc 11 doesn't like `constinit` in test_util, introduced by PR #1571

Fix gcc 11 compilation

---

CMakeLists.txt

Prior to this change `CMAKE_OSX_ARCHITECTURES` was [empty](https://stackoverflow.com/questions/51024294/cmake-system-processor-seems-to-be-empty-whats-the-best-strategy-for-os-agnost) in `guess_conan_profile` on my machine (Apple M2, macOS Sonoma 14.0, cmake 3.27.6) and so conan profile was determined incorrectly.

cmake: fix guess_conan_profile

---

silkworm/core/execution/evm_test.cpp
silkworm/core/state/intra_block_state.cpp

This reverts the change from PR #1553 because it breaks the state trie root at block [116525](https://etherscan.io/block/116525)

core: revert fix for create-after-destruct

---

cmd/dev/toolbox.cpp
silkworm/node/db/mdbx.cpp
silkworm/node/db/mdbx.hpp
silkworm/node/db/mdbx_test.cpp
silkworm/node/db/memory_mutation_cursor_test.cpp

node: default page size for MDBX database creation is now OS page size

node: read page size from existing MDBX database

---

silkworm/core/common/bytes.hpp

Otherwise I'm getting
```
/home/andrew/silkworm/silkworm/core/common/bytes.hpp:26:33: error: ‘uint8_t’ was not declared in this scope
26 | using Bytes = std::basic_string<uint8_t>;
|                                 ^~~~~~~
```

core: fix gcc13 compilation

---

silkworm/sentry/peer_manager_api.cpp

sentry: fix std::optional double-free error in gcc 11

---

.github/workflows/macOS.yml
.github/workflows/windows.yml

This PR fixes the recent CI failures happening on master branch on [macOS](https://github.com/erigontech/silkworm/actions/runs/6610070383/job/17951288191) and [Windows](https://github.com/erigontech/silkworm/actions/runs/6610070379/job/17951288185) builds.

ci: conan version 1.60 for macOS and Windows

---

docs/CONTRIBUTING.md

https://google.github.io/styleguide/cppguide.html has been recently [updated](https://github.com/google/styleguide/pull/795) to C++20

docs: Google's Style Guide updated to C++20

---

silkworm/node/recsplit/support/common.hpp

This PR includes the relevant part of the following changes made in original RecSplit implementation:
https://github.com/vigna/sux/commit/4169f008ac7090aeda4fa1c194b374879148c535

node: use correct check for BMI instructions in RecSplit

---

silkworm/core/chain/config_map.hpp

This PR fixes MSVC build broken on master after PR #1612. You can check [problem and solution in isolation](https://godbolt.org/z/oda56xWrc).

core: fix ConfigMap conversion error in MSVC

---

silkworm/node/stagedsync/stages/stage_interhashes/_test.cpp
silkworm/node/test/context.cpp
silkworm/node/test/context.hpp

This PR fixes an abnormal termination in `node` unit tests occurring systematically in debug builds with database page size >= 16KB.
The existing unit test code reuses the same `db::PooledCursor` instance on two different tables by calling `bind` on the same `txn`. Even if this usage pattern seems legit, this is the root cause which makes the following assertion to be triggered on next database upsert done (by another cursor) on the same table:
``` assert(page_numkeys(mp) > (unsigned)(i));```
in `page_node` MDBX function. Given that the `bind`-same-cursor-on-same-txn pattern is never used except here and that a brand new `db::PooledCursor` solves the issue, investigating the problem further seems not to be worth it.
Lastly, this PR also contains cosmetic changes to slightly improve …

node: change cursor usage in trie test causing abort in debug

---

silkworm/node/db/access_layer.cpp
silkworm/node/db/access_layer.hpp
silkworm/node/stagedsync/stages/stage.cpp
silkworm/node/stagedsync/stages/stage.hpp
silkworm/node/stagedsync/stages/stage_tx_lookup.cpp

This PR introduces the following changes:
- add capability to set prune progress for staged-sync stages
- make the `TxLookup` stage forward start from last frozen block
- make the `TxLookup` stage unwind stop at last frozen block
Moreover, this PR replaces `std::atomic_bool::operator=` with `std::atomic_bool::store` to remove warning `The value is never used` in CLion.

node: make stage TxLookup start from last frozen block

---

.circleci/config.yml
.github/workflows/macOS.yml
.github/workflows/windows.yml
README.md
conanfile.py

This PR was initially conceived to fix the build on Windows after #1593, but then macOS job started to fail intermittently 😭 so, in order to restore full CI green status, it now contains the following changes:
- fix Windows build broken after #1593 by not enabling option `asio_no_deprecated`
- update Conan to version [1.60.2](https://docs.conan.io/1/changelog.html) on macOS CI job to avoid [this error](https://github.com/conan-io/conan/pull/14363) occurred [here](https://github.com/erigontech/silkworm/actions/runs/6736269123/job/18315664966)
- downgrade Python to version 3.11 because version 3.12 (now present in `macos-13` GA image) triggers [another error](https://github.com/conan-io/conan/issues/14801), which will be fixed in not-yet-available Conan 1.62.0

conan: fix Windows build and upgrade to 1.60.2 for macOS

---

silkworm/silkrpc/commands/debug_api.cpp
silkworm/silkrpc/commands/trace_api.cpp
silkworm/silkrpc/core/evm_debug.cpp
silkworm/silkrpc/core/evm_debug.hpp
silkworm/silkrpc/core/evm_debug_test.cpp
silkworm/silkrpc/core/evm_trace.cpp
silkworm/silkrpc/http/request_handler.cpp
silkworm/silkrpc/json/stream.cpp
silkworm/silkrpc/json/stream.hpp
silkworm/silkrpc/json/stream_test.cpp
silkworm/silkrpc/types/writer.cpp
silkworm/silkrpc/types/writer.hpp
silkworm/silkrpc/types/writer_test.cpp

This PR contains the following improvements for debug_traceBlockByNumber API:
- use less memory allocations by replacing `nlohmann::json` with custom JSON objects
- replace `intx::to_string` with custom function

rpcdaemon: improve debug_traceBlockByNumber performance

---

.circleci/config.yml
README.md

Restore upload of code coverage report to codecov.io removed by PR #1232. I find the [website reports](https://app.codecov.io/gh/erigontech/silkworm) easier to navigate than the text artefacts.

CI: restore codecov upload

---

cmake/compiler_settings.cmake

This significantly reduces the size of the binaries. for example, `libsilkworm_api.so` shrinks from 106 MiB to 34 MiB. If one needs the debug info, CMAKE_BUILD_TYPE `RelWithDebInfo` is the recommended way.

build: no debug info in release builds

---

silkworm/api/silkworm_api.cpp

Fix to avoid core on startup in embedded configuration

api: fix crash in silkworm_add_snapshot after PR 1593

---

silkworm/silkrpc/core/evm_debug.cpp

Fix for wrong dump of stack entries in DebugTracer class

rpcdaemon: fix wrong dump of stack entries in DebugTracer

---

silkworm/infra/concurrency/co_spawn_sw.hpp
silkworm/sentry/discovery/discovery.cpp
silkworm/sentry/discovery/node_db/serial_node_db.hpp

Fixes #1530
* revert #1531
* bring back co_spawn_cancellation_handler with buggy dispatch from asio
* fix co_spawn_cancellation_handler using a shared_ptr

sentry: fix co_await Operation canceled crash (#1530)

---

silkworm/node/etl/in_memory_collector.hpp
silkworm/node/etl/in_memory_collector_test.cpp
silkworm/node/etl/mini_collector.hpp

This is a memory-only reduced version of ETL Collector, with a compatible interface, that I used to measure the performance gain or loss when using only the memory to perform ETL tasks.

node: in-memory ETL collector

---

silkworm/core/execution/call_tracer.hpp
silkworm/core/execution/evm.hpp
silkworm/core/execution/evm_test.cpp
silkworm/core/execution/execution_test.cpp
silkworm/silkrpc/core/evm_access_list_tracer.hpp
silkworm/silkrpc/core/evm_debug.hpp
silkworm/silkrpc/core/evm_trace.hpp

Introduce empty non-pure virtual methods in `EvmTracer` in order not to force subclasses to implement all of them.

core: empty virtual hooks in EVM tracer

---

silkworm/silkrpc/core/evm_debug.cpp

Fix for wrong JSON serialization for error field of DebugLog structure

rpcdaemon: fix JSON stream serialization for DebugLog::error

---

cmd/dev/snapshots.cpp
cmd/dev/toolbox.cpp

cmd: fix layout for table dump in db toolbox tool
cmd: add log trace in snapshots tool
The new `compare` subcommand is currently quite basic but it has already proven useful to diagnose some database discrepancies.

cmd: add compare subcommand to db toolbox

---

cmd/dev/toolbox.cpp

Moreover, any size mismatch in `FREE_DBI` table gets treated differently from other tables: it does not halt the comparison, but emits a warning.

cmd: diff paging in compare command of db toolbox

---

silkworm/node/recsplit/rec_split.hpp

Fix after PR #1675
Problems emerged after integration tests when it is necessary returns block from tx-hash
Restore call to std:.ceil() because:
- ceil() returns the smallest possible integer value which is "greater than or equal to input" (3.3 -> 4; 3 -> 3) 
- cast returns always the integer smaller the input value

fix calculation AggregationBound

---

silkworm/core/execution/evm_test.cpp
silkworm/core/state/intra_block_state.cpp

This PR fixes one incompatibility between Silkworm and Erigon database content related to account state changes.
Specifically, the discrepancy happened on mainnet at block [116525](https://etherscan.io/block/116525), where a contract was deployed at address [0xb214cbce30676bd117f95a8695d34427295cd6f7](https://etherscan.io/address/0xb214cbce30676bd117f95a8695d34427295cd6f7) in transaction 71 and then immediately destroyed in next transaction 72.
When such a sequence happens, i.e. creation followed by self-destruction in the same block, the account state effectively does not change if observed at the start and the end of the block. Hence, such account should not be marked as updated to avoid spurious state changes.

core: avoid account spurious update for create+delete in same block

---

.dockerignore
tests/docker/Dockerfile
tests/docker/README.md
tests/docker/run-docker.sh

This PR introduces a docker container to build silkworm. 
The motivation is to have an environment close to the CI that can be run locally. To speed up builds, the Dockerfile is constructed in a way that caches as much as possible, but still enables fresh builds.
Documentation and scripts provided.

build: dockerize silkworm builds

---

silkworm/infra/CMakeLists.txt
silkworm/node/CMakeLists.txt
silkworm/sentry/CMakeLists.txt
silkworm/sync/CMakeLists.txt

ntdll.lib propagates from silkworm_interfaces to all dependent libs

cmake: remove ntdll.lib duplication

---

silkworm/core/execution/call_tracer.cpp
silkworm/core/execution/evm_test.cpp

This PR fixes one incompatibility between Silkworm and Erigon database content related to call traces.
Specifically, the first discrepancy of this kind happened on mainnet at block [1639553](https://etherscan.io/block/1639553) where an EOA executes a transaction on a contract which in turn delegate-calls another one: the delegating contract must be included as sender in DELEGATECALL trace.

core: fix missing delegating contract as sender in DELEGATECALL trace

---

third_party/gmp/CMakeLists.txt

On some Linux distros libgmp is installed by default (as a shared library), and find_library() was returning it instead of using the static libgmp.a version from conan.

cmake: fix accidental linking with system libgmp

---

silkworm/core/execution/call_tracer.cpp
silkworm/core/execution/call_tracer.hpp
silkworm/core/execution/evm_test.cpp

This PR fixes another incompatibility between Silkworm and Erigon database content related to call traces.
Specifically, the discrepancy happened on mainnet at block [1305821](https://etherscan.io/block/1305821), where transaction 0 hits the fallback function of contract [0xFDf3D6c72F8aF59Fd1D7Fa65D1C12f89f12F9394](https://etherscan.io/address/0xFDf3D6c72F8aF59Fd1D7Fa65D1C12f89f12F9394). After some interactions with another address, such a contract executes a `CREATE` opcode to deploy another contract: this operation "silently succeeds" during one early check before the code deployment, i.e. in this specific case the deploying contract has insufficient balance to cover the expected endowment for the new contract.
When an early return happens (positive or negative, it doesn't matter) …

core: fix missing call trace for create/create2 w/ early return

---

silkworm/core/concurrency/resettable_once_flag.hpp
silkworm/core/types/transaction.cpp
silkworm/core/types/transaction.hpp

According to [Google's style guide](https://google.github.io/styleguide/cppguide.html#Use_of_const), all of a class's `const` operations should be safe to invoke concurrently with each other.

core: make Transaction::hash() thread-safe

---

silkworm/rpc/core/evm_debug.cpp

Changed memory dump output in debug_traceBlockByNumber

rpcdaemon: remove zeroed memory in debug endpoints

---

silkworm/rpc/json/stream_test.cpp
silkworm/rpc/types/writer_test.cpp

This PR fixes the [TSAN error](https://app.circleci.com/pipelines/github/erigontech/silkworm/10139/workflows/4e7d81e6-5e8e-4de9-930d-2ee5a50db174/jobs/44884) introduced by #1714

rpcdaemon: do not set log verbosity twice to fix TSAN error

---

silkworm/rpc/commands/debug_api.cpp

Managed block number passed as string in debug_traceBlockByNumber API (as erigon does)

rpcdaemon: block number as string in debug_traceBlockByNumber

---

silkworm/infra/common/log.cpp
silkworm/infra/common/log.hpp
silkworm/rpc/daemon.cpp

This PR fixes logging initialisation in standalone `rpcdaemon` component.

rpcdaemon: fix missing logging initialization

---

silkworm/rpc/commands/debug_api.cpp

Fix balance and nonce dumps as hex values in debug_accountAt  API

rpcdaemon: fix balance and nonce dumps in debug_accountAt 

---

cmake/copyright.cmake

This PR updates the copyright check to include 2024 and does some refactoring for multiple years: from now on, it's sufficient to append new years to the `SILKWORM_COPYRIGHT_YEARS` list.

cmake: update copyright check for 2024

---

silkworm/rpc/http/json_rpc_validator.cpp
silkworm/rpc/http/json_rpc_validator_test.cpp

As noted in https://github.com/erigontech/silkworm/pull/1749, accessing JSON from `std::map<std::string, nlohmann::json>` seemed to be unusually slow. It turns out it was a simple reference issue and the compiler created a new JSON instance on each access. Fixed.
Before:
```
[ RUN      ] `json_rpc_validator/0`
│ threads: 1
│ iterations: 18165
│ real_time: 38484.28863197544
│ cpu_time: 38483.96917148362
│ time_unit: "ns"
[       OK ] `json_rpc_validator/0
```
After:
```
[ RUN      ] `json_rpc_validator/0`
│ threads: 1
│ iterations: 78563
│ real_time: 9262.071547666672
│ cpu_time: 9261.998650764355
│ time_unit: "ns"
[       OK ] `json_rpc_validator/0`
```
Plus some small fixes and better test coverage

rpcdaemon: JsonRpcValidator perf improvements

---

.circleci/config.yml
cmd/test/fuzzer_diagnostics.cpp
cmd/test/fuzzer_investigation.cpp
cmd/test/fuzzer_test.cpp

PR #1744 recently broke the fuzzer build, but it became evident only during weekly `fuzzer` workflow because the fuzzer build is not executed in any other workflow.
This PR splits the `linux-clang-fuzzer` job into separate build and run steps, including the former also in the `integration` workflow and activating the latter only in the `fuzzer` workflow.

CI: fix fuzzer build and add it to integration workflow

---

silkworm/rpc/daemon.cpp
silkworm/rpc/http/json_rpc_validator.cpp
silkworm/rpc/http/json_rpc_validator.hpp
silkworm/rpc/http/json_rpc_validator_test.cpp
silkworm/rpc/http/request_handler.hpp

This PR moves the JSON RPC spec loading at startup to avoid the performance penalty occurring before #1758 and restores the `JsonRpcValidator` in `RequestHandler`.

rpcdaemon: load JSON RPC validation spec once at startup

---

cmd/test/fuzzer_test.cpp
silkworm/rpc/http/connection.hpp
silkworm/rpc/test/api_test_database.hpp

fix compilation in fuzzer test engine

rpcdaemon: fix clang-tidy and fuzzer build after PR 1762

---

silkworm/capi/silkworm.cpp
silkworm/core/common/util.cpp
silkworm/core/common/util.hpp
silkworm/core/state/in_memory_state.cpp
silkworm/core/state/intra_block_state.cpp
silkworm/node/db/buffer.cpp
silkworm/node/db/buffer.hpp
silkworm/node/db/buffer_test.cpp
silkworm/node/db/mdbx.cpp
silkworm/node/db/mdbx.hpp
silkworm/node/db/mdbx_test.cpp

This PR contains the following changes related to block execution API implementation:
- commit the current state when the batch size crosses over threshold
- commit the state history after each block 
- change the batch size unit from cumulated gas to bytes
- fix many batch size computations in db buffer
- avoid caching read values in db buffer
- sort storage locations to insert ordered data into db
- fix empty element in call traces
- fix unmanaged RW txn destruction
Moreover, some other things as well:
- improve logging in block execution
- add unit tests
All these changes have been made in the process of reaching full binary data compatibility between Erigon and Erigon+Silkworm, step by step, over a long sequence of comparative tests: that's why this PR required quite a long time to be …

capi: block execution commits after state batch has been flushed

---

.clang-tidy
silkworm/sentry/common/message.hpp
silkworm/sentry/rlpx/common/disconnect_reason.hpp
silkworm/sentry/rlpx/framing/message_frame_codec.cpp
silkworm/sentry/rlpx/framing/message_frame_codec.hpp
silkworm/sentry/rlpx/framing/message_stream.hpp
silkworm/sentry/rlpx/peer.cpp

Some crawler clients (Nodecrawler/v1.13.10-stable) send an uncompressed Disconnect message after the handshake, which is an RLPx protocol violation.

sentry: treat invalid snappy data

---

silkworm/node/db/mdbx.hpp
silkworm/node/db/mdbx_test.cpp

This PR fixes a lifetime issue in how `db::ROAccess` and `db::RWAccess` classes receive and store MDBX environment. Objects of both such classes accept and save a _reference_ to a `mdbx::env` instance, which means they are safe to use only as long as such `mdbx::env` instance is alive.
The `mdbx::env` class wraps a raw pointer to `MDBX_env`, hence acting as a _handle pattern_ implementation: it is then feasible and also performance-friendly to pass it by-value. You can clearly pass it also by-reference and be very careful about the involved lifetime, but it looks like an anti-pattern.
In fact, some class (e.g. `chain sync::Sync`) may accept a `mdbx::env` instance by-value e.g. in its constructor (which is totally fine) and naively pass it to a `db::ROAccess` instance outliving such …

node: fix mdbx::env lifecycle in db::ROAccess and db::RWAccess

---

cmd/capi/execute.cpp
cmd/dev/check_log_indices.cpp
cmd/dev/db_toolbox.cpp
cmd/dev/snapshots.cpp
silkworm/infra/common/ensure.hpp
silkworm/infra/common/ensure_test.cpp
silkworm/infra/common/memory_mapped_file.cpp
silkworm/node/db/access_layer.cpp
silkworm/node/db/bitmap.cpp
silkworm/node/db/log_cbor.cpp
silkworm/node/snapshots/index.cpp
silkworm/node/snapshots/rec_split/rec_split.hpp
silkworm/node/snapshots/repository.cpp
silkworm/node/snapshots/snapshot.cpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/forks/canonical_chain.cpp
silkworm/node/stagedsync/stages/stage_hashstate.cpp
silkworm/node/stagedsync/stages/stage_headers.cpp
silkworm/node/stagedsync/stages/stage_senders.cpp
silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/commands/ots_api.cpp

Both compilers, gcc and clang, do not efficiently optimize string arguments for inline methods. As the result, when the following function:
```c++
inline void ensure(bool condition, const std::string& message) {
if (!condition) [[unlikely]] {
throw std::logic_error(message);
}
}
```
is called with the code:
```c++
ensure(envelope_result.has_value(),
"TransactionSnapshot: cannot decode tx envelope: " + to_hex(tx_envelope) + " error: " + to_string(envelope_result));
```
then the string argument is built every time. This is unnecessary as the string argument is only required in the unlikely event of an unmet condition.
During the execution stage, those `ensure()` methods can be called many times per block. This results in wasted resources and additional time required for completion. The …

infra: migrate `ensure` to the dynamic format for performance reasons

---

silkworm/rpc/json/stream.cpp
silkworm/rpc/json/stream.hpp

After #1777 build is broken on Windows due to [some compiler bug](https://developercommunity.visualstudio.com/t/use-of-undefined-type-std::tuplelt;_Ty/10342164). This PR replaces usage of Asio `promise` with `concurrent_channel` in our JSON stream.

rpcdaemon: workaround for Windows build error after PR 1777

---

.gitignore
cmd/dev/snapshots.cpp

Using enumerated parameters with base type size different from `int` breaks CLI11 parsing:
```
% cmd/dev/snapshots --tool decode_segment --snapshot_file /tmp/v1-018300-018400-transactions.seg
--tool: Value  not in range [
Run with --help for more information.
```
```
% cmd/dev/snapshots --help
--tool: Value  not in range [
Run with --help for more information.
```

cmd: fix CLI11 parse regression in snapshots utility

---

silkworm/rpc/http/json_rpc_validator.cpp
silkworm/rpc/http/json_rpc_validator_test.cpp
silkworm/rpc/http/request_handler.cpp
silkworm/rpc/json/call.cpp
silkworm/rpc/json/call_test.cpp

Some RPC methods like eth_createAccessList, eth_estimateGas or eth_call take a generic transaction object as a parameter. This is called `silkworm::rpc::Call` in Silkworm. The object has the `input` field to pass some data. 
Check [specification source code](https://github.com/ethereum/execution-apis/blob/main/src/eth/execute.yaml) and [API documentaion](https://ethereum.github.io/execution-apis/api-documentation/) for the field definition.
Confusingly this field used to be called `data` in the past. And that is how it is referred to in our tests.
This PR makes the validation and parameters backwards compatible, accepting both `input` and `data` for the same field. This is in line with Erigon's approach, see https://github.com/ledgerwatch/erigon/blob/devel/turbo/adapter/ethapi/api.go#L146. …

rpcdaemon: fix json rpc validation and enable for integration tests

---

cmd/common/rpcdaemon_options.cpp
silkworm/node/snapshots/sync.cpp
silkworm/rpc/common/interface_log.cpp
silkworm/rpc/common/interface_log.hpp
silkworm/rpc/common/interface_log_test.cpp
silkworm/rpc/daemon.cpp
silkworm/rpc/http/connection.cpp
silkworm/rpc/http/connection.hpp
silkworm/rpc/http/request_handler.cpp
silkworm/rpc/http/request_handler.hpp
silkworm/rpc/http/server.cpp
silkworm/rpc/http/server.hpp
silkworm/rpc/settings.hpp

This PR introduces opt-in configurable interface log for both Execution Layer and Engine JSON RPC end-points.
The configuration settings for the JSON RPC end-points can be further aggregated to simplify the code but this is left for next PR.

rpcdaemon: add optional interface log in JSON RPC end-points

---

silkworm/rpc/http/json_rpc_validator.cpp
silkworm/rpc/http/json_rpc_validator.hpp
silkworm/rpc/http/json_rpc_validator_test.cpp
silkworm/rpc/http/request_handler.cpp
silkworm/rpc/http/request_handler.hpp

This PR modernises the JSON RPC validator by using `tl::expected` to implement the validation result.
The code is shorter and a bit cleaner and we also gain ~ 8% performance wise.

rpcdaemon: expected result in JSON RPC validator

---

silkworm/capi/silkworm.cpp
silkworm/infra/common/log.cpp
silkworm/infra/common/log_test.cpp
silkworm/infra/common/terminal.cpp
silkworm/infra/common/terminal.hpp

This PR fixes the log format used in C API to reproduce the Erigon format exactly.

capi, infra: add TTY detection to customize log format

---

silkworm/rpc/core/call_many.cpp
silkworm/rpc/core/evm_executor.hpp

Fix for using OverrideState in CallExecutor::executes_all_bundles

rpcdaemon: use of OverrideState in CallExecutor::executes_all_bundles

---

cmake/common/targets.cmake
silkworm/capi/CMakeLists.txt
silkworm/capi/silkworm.cpp
silkworm/capi/silkworm_test.cpp
silkworm/infra/concurrency/signal_handler_test.cpp

This PR introduces very basic unit tests for C API, we will hopefully expand them in the near future.
Moreover, this PR also refactors the `silkworm_capi` target to use the existing `silkworm_library` CMake facility and fixes one unit test for macOS in `infra` library.

capi: some basic unit tests

---

silkworm/node/snapshots/seg/decompressor.cpp
silkworm/node/snapshots/seg/seg_zip.cpp

* fix the last uncovered part calculation in case of a non-empty initial buffer
* seg_unzip: clear the buffer before calling next()
* use append in next_uncompressed() as the doc comment says
* use size() instead of length() for consistency

snapshots: fix seg_unzip

---

silkworm/node/snapshots/sync.cpp
silkworm/node/stagedsync/execution_pipeline.cpp

node: clean exit from execution pipeline with STOP_AT_BLOCK

node: fix snapshot sync progress update with STOP_AT_BLOCK

---

silkworm/sentry/discovery/disc_v4/discovery.cpp
silkworm/sentry/discovery/disc_v4/ping/ping_handler.cpp
silkworm/sentry/discovery/discovery.cpp

Make sure that we never insert the local node into the nodes database. Warn if it did happen by accident with a fix suggestion.

sentry: assertion in ping_check.cpp (#1855)

---

silkworm/sentry/rlpx/auth/ecies_cipher_test.cpp
silkworm/sentry/rlpx/peer.cpp

The error is happening if you delete `<datadir>/nodekey` and the old peers try to reconnect. They use a public key of an old nodekey to encrypt their AuthMessage, and it will fail the MAC check with the new nodekey. The behaviour is the same in erigon, and erigon uses logger.Trace.

sentry: invalid MAC error - log as TRACE

---

silkworm/core/execution/call_tracer.cpp

This PR fixes a problem found while syncing the Sepolia testnet: segmentation fault at block [4337894](https://sepolia.etherscan.io/block/4337894) due to missing check on unexpected contract initialisation code size.
I've been porting all the following missing validations in call tracer for block execution:
- memory gas cost check
- contract initialisation code size check
- out-of-gas checks
Some functions have been temporarily copied and adapted from [evmone](https://github.com/ethereum/evmone) because we need some changes here.
@chfast @JacekGlen as already agreed, we will discuss an improved tracing interface when dust settles a bit (probably after adopting evmone API v2).

core: add missing checks in call tracer

---

tools/deps.py

Example:
```
% ./tests/deps/deps.py silkworm/node/snapshots
silkworm/node/snapshots module depends on:
1. core/chain
2. core/common
3. core/types
4. infra/common
5. infra/concurrency
6. infra/test_util
7. node/db
8. node/db/etl
9. node/db/test_util
10. node/snapshots
11. node/snapshots/bittorrent
12. node/snapshots/config
13. node/snapshots/rec_split
14. node/snapshots/rec_split/common
15. node/snapshots/rec_split/encoding
16. node/snapshots/seg
17. node/snapshots/seg/common
18. node/snapshots/test_util
```

tests: a script to list dependencies of a module

---

cmd/capi/execute.cpp
silkworm/capi/silkworm.cpp
silkworm/capi/silkworm.h
silkworm/capi/silkworm_test.cpp
silkworm/infra/common/bounded_buffer.hpp
silkworm/node/db/mdbx.cpp
silkworm/node/db/mdbx.hpp
silkworm/node/db/mdbx_test.cpp
silkworm/node/db/test_util/temp_chain_data.hpp

This PR mainly deals with providing a proper MDBX transaction handling at the C API interface, namely ensuring the all-or-nothing guarantee when paired the associated `silkworm-go` bindings and the correct usage on the Erigon side.
This is a detailed list of the changes:
- add internal/external MDBX support in C API `silkworm_execute_blocks`: when passed `mdbx_txn` is null, Silkworm will start an internal MDBX transaction and manage its lifecycle (i.e. always either commits or aborts the internal transaction, guaranteed by RAII); on the other hand, if a valid `mdbx_txn` is passed, Silkworm will use such external MDBX transaction to read/write data but it won't touch its lifecycle (i.e. neither commit nor abort is called). Of course, this change has some implications:
- every time we hit …

capi: internal/external txn handling in block execution

---

silkworm/capi/silkworm.cpp
silkworm/capi/silkworm_test.cpp
silkworm/infra/common/bounded_buffer.hpp
silkworm/infra/common/bounded_buffer_test.cpp

Silkworm CAPI has two threads:
- main: for block execution and writing state changes
- block provider: for pre-loading blocks into the buffer
This PR makes sure that when the termination signal (Ctrl+C) is issued then:
- all open db transactions are closed
- threads are joined
- operations can be resumed (db integrity preserved)
Test notes: I've added some unit tests, but the true tests were conducted manually. I ran Erigon with Silkworm and then during the Execution stage pressed Ctrl+C to terminate. Then I restarted Erigon to make sure that the execution was resumed at the point of the last state write. Then I repeated the process multiple times.

capi: correct signal handling

---

silkworm/snapshots/rec_split/encoding/sequence.hpp
silkworm/snapshots/rec_split/encoding/sequence_test.cpp
silkworm/snapshots/rec_split/rec_split.hpp
silkworm/snapshots/rec_split/rec_split_seq_test.cpp

This PR introduces features flag in RecSplit indices for compatibility with Erigon format: https://github.com/ledgerwatch/erigon/pull/9501.
Moreover, this also fixes how an invalid size is handled in integral sequence deserialisation, specifically for GR codes.

snapshots: support features flag in recsplit index

---

silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/execution_pipeline.hpp
silkworm/node/stagedsync/stages/_test.cpp
silkworm/node/stagedsync/stages/stage.cpp
silkworm/node/stagedsync/stages/stage.hpp
silkworm/node/stagedsync/stages/stage_blockhashes.cpp
silkworm/node/stagedsync/stages/stage_blockhashes.hpp
silkworm/node/stagedsync/stages/stage_bodies.cpp
silkworm/node/stagedsync/stages/stage_bodies.hpp
silkworm/node/stagedsync/stages/stage_execution.cpp
silkworm/node/stagedsync/stages/stage_execution.hpp
silkworm/node/stagedsync/stages/stage_finish.cpp
silkworm/node/stagedsync/stages/stage_finish.hpp
silkworm/node/stagedsync/stages/stage_hashstate.hpp
silkworm/node/stagedsync/stages/stage_headers.cpp
silkworm/node/stagedsync/stages/stage_headers.hpp
silkworm/node/stagedsync/stages/stage_history_index.cpp
silkworm/node/stagedsync/stages/stage_history_index.hpp
silkworm/node/stagedsync/stages/stage_history_index_test.cpp
silkworm/node/stagedsync/stages/stage_interhashes.cpp
silkworm/node/stagedsync/stages/stage_interhashes.hpp
silkworm/node/stagedsync/stages/stage_log_index.cpp
silkworm/node/stagedsync/stages/stage_log_index.hpp
silkworm/node/stagedsync/stages/stage_senders.cpp
silkworm/node/stagedsync/stages/stage_senders.hpp
silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
silkworm/node/stagedsync/stages/stage_tx_lookup.hpp
silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp

Instead of passing all node_settings to each stage, each stage accepts only a subset that is needed.

stagedsync: do not share global node_settings with stages

---

silkworm/node/db/tables.hpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/stages/stage.hpp
silkworm/node/stagedsync/stages/stage_call_trace_index.cpp
silkworm/node/stagedsync/stages/stage_call_trace_index.hpp

stagedsync: add CallTraceIndex stage

---

cmake/common/targets.cmake
silkworm/node/CMakeLists.txt
silkworm/node/db/CMakeLists.txt

After #1885 I started to experience linking errors on my machine for targets `snapshots` and `db_toolbox`. The problem was caused by library `silkworm_node` being empty, which in turn was due to a combination of two things:
- one of my Silkworm repo stays in external disk and contains `db` folder in parent path (i.e. `/db/silkworm/...`)
- the exclude regex application in `silkworm_library` CMake function excluded all source files for such weird path
I've added `SILKWORM_SRC_DIR` in each exclude regex token to filter using absolute paths.

cmake: use absolute path when applying exclude regex

---

silkworm/sentry/rlpx/peer.cpp

sentry: fix unhandled exception in peer handshake close

---

silkworm/db/snapshots/index.cpp
silkworm/db/snapshots/index.hpp
silkworm/db/snapshots/rec_split/rec_split.hpp
silkworm/db/snapshots/rec_split/rec_split_par.hpp
silkworm/db/snapshots/rec_split/rec_split_par_test.cpp
silkworm/db/snapshots/rec_split/rec_split_seq.hpp
silkworm/db/snapshots/rec_split/rec_split_seq_test.cpp
silkworm/db/snapshots/snapshot.cpp
silkworm/db/snapshots/test_util/common.hpp

This PR introduces the `less false-positives` feature in our RecSplit implementation and activates such features for hash-to-offset index in transaction snapshots (see also https://github.com/ledgerwatch/erigon/pull/9515)
Depends on #1915

snapshots: less false-positives feature in recsplit

---

cmd/dev/backend_kv_server.cpp
cmd/silkworm.cpp
silkworm/core/types/block.cpp
silkworm/core/types/block.hpp
silkworm/core/types/block_id.hpp
silkworm/core/types/chain_head.hpp
silkworm/db/chain_head.cpp
silkworm/db/chain_head.hpp
silkworm/node/stagedsync/client.hpp
silkworm/node/stagedsync/forks/canonical_chain.hpp
silkworm/sentry/eth/status_data_provider.cpp
silkworm/sentry/eth/status_data_provider.hpp
silkworm/sync/internals/chain_fork_view.hpp
silkworm/sync/internals/header_chain_plus_exec_test.cpp
silkworm/sync/sync_pow.cpp

HeadInfo was identical to an existing ChainHead type. Let's use it instead of defining a new type.

db: replace HeadInfo with ChainHead

---

silkworm/rpc/http/connection.cpp
silkworm/rpc/http/connection.hpp

rpcdaemon: fix Clang Tidy after PR 1914

rpcdaemon: simplify HTTP gzip compression handling

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/rpc-performance-tests.yml

On the self-hosted test runner machine, a software, controllable via REST interface, is capable of fetching different versions of the Erigon database for testing purposes. This PR utilizes the directory controlled by this software in the tests, enabling the ability to switch versions through manual user commands or via automation scripts.

tests: use controllable Erigon datadir 

---

cmake/compiler_settings.cmake
cmake/compiler_warnings.cmake
third_party/erigon-mdbx-go/CMakeLists.txt

Happens when building all mdbx tools targets:
```
[5/5] Linking CXX executable third_party/erigon-mdbx-go/mdbx-go/mdbxdist/mdbx_chk
ld: warning: ignoring duplicate libraries: '-lc++', '-lc++abi'
```
https://stackoverflow.com/questions/77164140/

mdbx-go: no_warn_duplicate_libraries

---

.github/workflows/rpc-performance-tests.yml

The vegeta pattern contains in the http header (accept-Encoding: gzip) therefore if the server is not launched with http-compression enabled, any request is refused with invalid media type

perf_test_workflow: enable http compression on rpcdaemon startup

---

silkworm/rpc/http/connection.cpp

This PR increases the max body size limit accepted by Boost Beast (default value is 1MB) in order to accept incoming request payload sizes up to 30MB, as in Erigon.

rpcdaemon: increase max HTTP request body limit

---

.github/workflows/rpc-integration-tests.yml

Currently, integration tests only save the result in the event of **failure**. 
However, with respect to the objective of making a **historical comparison** of test results, it is useful to know whether integration tests have run or not. 
Therefore, it is proposed to _always save the result_ of such tests, which is then a binary result: success or failure

qa-tests: always save the result

---

silkworm/infra/concurrency/signal_handler.cpp
silkworm/infra/concurrency/signal_handler.hpp
silkworm/infra/concurrency/signal_handler_test.cpp

This PR changes the implementation of `SignalHandler` to relying on `sigaction` system call on Linux and macOS platforms, so that we can use `SA_ONSTACK` flag on registered signal handlers.
Fixes #1940

infra: setup signal handling with SA_ONSTACK flag

---

silkworm/db/buffer.cpp

This PR slightly adjusts the batch_state_size calculation in `buffer.cpp` so it matches the way Erigon does its calculation.
Additionally, there is a small compiler optimization.

db: match batch_state_size calculation with Erigon

---

silkworm/rpc/commands/debug_api.cpp

rpcdaemon: fix debug_storageRangeAt response for non-existent block hash

---

.github/workflows/rpc-performance-tests.yml
silkworm/rpc/commands/debug_api.cpp
silkworm/rpc/common/async_task.hpp
silkworm/rpc/common/async_task_benchmark.cpp
silkworm/rpc/common/async_task_test.cpp
silkworm/rpc/core/call_many.cpp
silkworm/rpc/core/estimate_gas_oracle.cpp
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug_test.cpp
silkworm/rpc/core/evm_executor.cpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/http/connection.cpp

This PR introduces a common `async_task` primitive that can be used to execute a task on some executor and co-await asynchronously for its completion. Typical usage: any I/O thread delegates long-running tasks to a thread pool by calling a coroutine that starts the work and is suspended until completion.
The key factors for introducing this abstraction are:
- implementation of `asio::async_compose` + `asio::post` pattern in one place
- complete exception handling (missing in many current usages)
- avoid code duplication
- improve readability at the call site
The following modules throughout the RPC daemon has been refactored to benefit from `async_task`:
- `http::Connection`
- `evm_debug`
- `emv_trace`
- `call_many`
- `estimate_gas_oracle`
- `evm_executor`

rpcdaemon: extract awaitable async task run by executor

---

cmd/capi/sample-go-client/main.go

This PR fixes the init settings in our Go sample code using the C API library and improves error handling.
It would be nice to have a proper Go test client exercising the C API (or at least part of it) and running some integration tests in our CI, see also #1957.

capi: fix sample Golang client

---

cmd/common/rpcdaemon_options.cpp
silkworm/rpc/common/interface_log.cpp
silkworm/rpc/common/interface_log.hpp
silkworm/rpc/common/interface_log_test.cpp

This PR introduces a configuration flag in RPC interface log to enable/disable the dump of any response (disabled by default).
Dumping the whole response can be useful for debugging some specific request/response pair, but makes the interface log content grow very fast, so it should be enabled carefully.
Command-line options to enable/disable the feature in each ETH/Engine endpoint are also added.

rpcdaemon: add config flag to toggle response dump in interface log

---

silkworm/rpc/commands/admin_api.hpp
silkworm/rpc/commands/debug_api.cpp
silkworm/rpc/commands/debug_api.hpp
silkworm/rpc/commands/engine_api.hpp
silkworm/rpc/commands/erigon_api.hpp
silkworm/rpc/commands/eth_api.hpp
silkworm/rpc/commands/net_api.hpp
silkworm/rpc/commands/ots_api.hpp
silkworm/rpc/commands/parity_api.hpp
silkworm/rpc/commands/rpc_api.hpp
silkworm/rpc/commands/rpc_api_table.hpp
silkworm/rpc/commands/trace_api.hpp
silkworm/rpc/commands/txpool_api.hpp
silkworm/rpc/commands/web3_api.hpp
silkworm/rpc/daemon.cpp
silkworm/rpc/http/connection.cpp
silkworm/rpc/http/connection.hpp
silkworm/rpc/http/server.cpp
silkworm/rpc/http/server.hpp
silkworm/rpc/json/stream.hpp
silkworm/rpc/json_rpc/request_handler.cpp
silkworm/rpc/json_rpc/request_handler.hpp
silkworm/rpc/test/api_test_database.hpp
silkworm/rpc/transport/request_handler.hpp
silkworm/rpc/transport/stream_writer.hpp
silkworm/rpc/transport/stream_writer_test.cpp
silkworm/rpc/ws/connection.cpp
silkworm/rpc/ws/connection.hpp

This PR performs some refactoring to remove any dependency from `http` and `ws` modules to `json_rpc` module to avoid transport-level being dependent on presentation-level, which is kind of an anti-pattern. Namely, a new `transport` module is introduced which defines the `rpc::RequestHandler` interface and will contain both `http` and `ws` modules in the future.
This PR is the first one in a row.
*Extras*
- improve readability in `http::Server` run loop
- move `StreamWriter` from `common` to `transport`
- improve naming in `ws::Connection`
- demote some log traces

rpcdaemon: extract JSON-RPC handler out of transport

---

cmd/capi/execute.cpp
silkworm/capi/common.cpp
silkworm/capi/common.hpp
silkworm/capi/instance.hpp
silkworm/capi/rpcdaemon.cpp
silkworm/capi/silkworm.cpp
silkworm/capi/silkworm.h
silkworm/capi/silkworm_test.cpp
silkworm/infra/concurrency/context_pool_settings.hpp
silkworm/rpc/common/worker_pool.hpp
silkworm/rpc/settings.hpp

This PR exports our Silkworm RPC Daemon configuration settings in the C API interface. The following options can be customised (all of them are opt-in, default values provide a meaningful configuration):
- number of I/O execution contexts to use in concurrency mode
- configuration options for interface log of Execution JSON-RPC end-point
- host address for Execution JSON-RPC end-point
- listening port number for Execution JSON-RPC end-point
- API namespace specification (comma-separated list of API namespaces)
- number of threads in worker pool (for long-run tasks)
- list of CORS domains
- path to the JWT file in UTF-8
- flag indicating if JSON-RPC strict compatibility w/ Erigon is supported
- flag indicating if WebSocket support is enabled
- flag indicating if compression of WebSocket …

capi: export RpcDaemon configuration settings

---

silkworm/rpc/ethdb/kv/state_changes_stream.cpp
silkworm/rpc/ethdb/kv/state_changes_stream_test.cpp
silkworm/rpc/grpc/server_streaming_rpc.hpp

This PR improves the close sequence of `StateChanges` streaming gRPC on client-side after the stream has been closed by server.
*Extras*
rpcdaemon: clean-up some code and comments

rpcdaemon: improve close of state-changes stream after server-side termination

---

.github/workflows/rpc-fuzzer-tests.yml
.github/workflows/rpc-performance-tests.yml
cmake/toolchain/clang_libcxx.cmake

This PR enables long-running fuzzer tests on GitHub Actions:
- Scheduled to run on Sundays for 24 hrs
- The workflow does minimal changes to the system to enable the Clang compilator, but these changes are reverted in the tear-down step
- Saves corpus to be reused by the next workflow run

rpcdaemon: enable fuzzer tests on GitHub Actions

---

cmd/capi/CMakeLists.txt
cmd/capi/main.c
silkworm/capi/silkworm.h

This PR fixes the pure C compilation of our C API header with strict compiler options in order to fix the errors surfaced in [Erigon CI](https://github.com/ledgerwatch/erigon/actions/runs/8760788201/job/24046312870?pr=10002).
A new pure C target named `capi_main` is also added to our build, so that we can hopefully gain early error detection and prevent any unexpected error at the end of the Erigon++ toolchain.

capi: fix C99 compilation

---

silkworm/rpc/common/constants.hpp
silkworm/rpc/http/connection.cpp
silkworm/rpc/http/connection.hpp
silkworm/rpc/http/connection_test.cpp

This PR refines the JSON Web token (JWT) support in HTTP connection by:
- adding unit tests
- implementing the optional check for `issued-at` claim [as specified in Execution APIs](https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md#jwt-claims)
- fixing exception handling
- improving code readability (naming, comments)
*Extras*
Remove unused HTTP constant.

rpcdaemon: improve JWT handling in HTTP connection

---

.circleci/config.yml

This PR removes the periodic execution of Fuzzer tests from CircleCI, given that we moved it to Github Action self-hosted runner.

ci: remove Fuzzer test runner from CircleCI

---

cmd/dev/snapshots.cpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync.hpp
silkworm/db/snapshot_sync_test.cpp
silkworm/node/node.cpp

This PR fixes a [wrong initialisation](https://quuxplusone.github.io/blog/2019/02/18/knightmare-of-initialization/) of the encoding buffer for block numbers, used to fill the content of `HeaderNumber` table at the end of snapshot synchronisation process.
*Extras*
Change namespace for `SnapshotSync` to `silkworm::db`

db: fix block number values in HeaderNumber table after snapshot sync

---

silkworm/db/access_layer.cpp
silkworm/db/access_layer_test.cpp
silkworm/db/mdbx/mdbx.hpp
silkworm/db/test_util/mock_cursor.hpp
silkworm/db/test_util/mock_txn.hpp

This PR handles some data length errors in access layer by adding missing checks for encoded block numbers and hashes read from different database tables (unit tests included).
*Extras*
- demote visibility for state variable in `db::ROTxn`
- small code cleanups

db: missing length errors in access layer

---

silkworm/core/common/bytes.hpp
silkworm/infra/grpc/common/conversion.cpp
silkworm/infra/grpc/common/conversion.hpp
silkworm/infra/grpc/common/conversion_test.cpp

This PR introduces gRPC type conversions tailored for `std::span` byte containers. This additions will be useful to minimise memory allocation when supporting `execution` gRPC protocol types.

infra: gRPC type conversions for std::span

---

.github/workflows/rpc-fuzzer-tests.yml

The recent fuzzer error https://github.com/erigontech/silkworm/actions/runs/8954213003/job/24593581330 is probably caused by the fuzzer engine and not related to the Silkworm RPC. This appeared after we enabled parallel fuzzer jobs. 
In this PR I reduce jobs and increase available memory.

fuzzer: increase available memory

---

silkworm/sync/internals/header_chain.cpp
silkworm/sync/internals/header_chain.hpp
silkworm/sync/internals/header_retrieval_test.cpp

This PR changes the validity check for zero-difficulty headers by rejecting them only if the chain terminal total difficulty is not set.
*Extras*
add unit test for header retrieval

sync: fix validity check for zero-difficulty headers

---

silkworm/sync/messages/inbound_block_bodies.cpp
silkworm/sync/messages/inbound_block_headers.cpp
silkworm/sync/messages/inbound_get_block_bodies.cpp
silkworm/sync/messages/inbound_get_block_headers.cpp
silkworm/sync/messages/inbound_new_block_hashes.cpp
silkworm/sync/messages/outbound_get_block_bodies.cpp
silkworm/sync/messages/outbound_get_block_headers.cpp
silkworm/sync/messages/outbound_new_block.cpp
silkworm/sync/messages/outbound_new_block_hashes.cpp

This PR handles send errors for outbound p2p messages, which may occur if the network channel breaks while some inbound message processing is ongoing.
Currently, if any send error occurs, the program execution stops because any unhandled exception terminates the `BlockExchange` execution loop. There's not much we can do here except swallow the exception because the peer disconnection is already handled in `sentry` module and retry does not make any sense for messages with single destination.

sync: handle send errors for outbound p2p messages

---

.github/workflows/rpc-integration-tests.yml
silkworm/core/execution/evm.cpp
silkworm/core/execution/evm.hpp
silkworm/rpc/core/evm_executor.cpp

Added gas_bailout member to EVM for call simulation

core, rpcdaemon: gas bailout in EVM

---

silkworm/sentry/discovery/discovery.cpp
silkworm/sentry/rlpx/peer.cpp
silkworm/sentry/rlpx/server.cpp
silkworm/sentry/sentry.cpp
silkworm/sentry/status_manager.cpp

This PR introduces some additional exception handling in the following modules of `sentry`:
- run loop of all the `Sentry` main tasks (i.e. `StatusManager`, `Discovery`...): these are long-running tasks which usually should never terminate (unless the user requests a graceful exit), so here we just catch any system exception to log a critical error and relaunch it. As a result, we will see what is the root cause of the error forcing the program to exit, currently it's just a somewhat obscure `co_await: operation cancelled` error
- `rlpx::Peer`: during some tests I've found that sometimes a `std::nested_exception` gets raised, which we can handle properly. Moreover, I've seen `Peer::post_message` rarely failing to spawn `Peer::send_message`, thus causing the program to terminate, so I've …

sentry: add exception handling for main tasks

---

silkworm/rpc/commands/ots_api.cpp
silkworm/rpc/commands/ots_api.hpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace.hpp

Fixes #2015 
Fixes #2016 
Fixes #2018

rpcdaemon: fix ots_searchTransactionsBefore + ots_searchTransactionsAfter 

---

.github/workflows/rpc-fuzzer-tests.yml

The step timeout seems to be overridden by the job timeout, see: https://github.com/erigontech/silkworm/actions/runs/9143609277
This PR ups the job timeout to match the step timeout.

fuzzer: extend job timeout

---

cmd/silkworm.cpp
silkworm/node/CMakeLists.txt
silkworm/node/execution/api/active_direct_service.cpp
silkworm/node/execution/api/active_direct_service_test.cpp
silkworm/node/execution/api/service.hpp
silkworm/node/execution/test_util/sample_protos.hpp
silkworm/node/node.cpp
silkworm/node/node.hpp
silkworm/node/settings.hpp
silkworm/node/stagedsync/execution_engine_test.cpp
silkworm/node/stagedsync/forks/extending_fork.cpp
silkworm/node/stagedsync/forks/extending_fork.hpp
silkworm/node/stagedsync/forks/fork_test.cpp
silkworm/node/stagedsync/forks/main_chain_test.cpp
silkworm/node/test_util/CMakeLists.txt
silkworm/node/test_util/dummy.cpp
silkworm/node/test_util/mock_execution_engine.hpp
silkworm/node/test_util/sample_blocks.hpp
silkworm/rpc/types/execution_payload.hpp
silkworm/sync/chain_sync.cpp
silkworm/sync/chain_sync.hpp
silkworm/sync/settings.hpp
silkworm/sync/sync.cpp
silkworm/sync/sync.hpp
silkworm/sync/sync_pos.cpp
silkworm/sync/sync_pos.hpp
silkworm/sync/sync_pos_test.cpp
silkworm/sync/sync_pow.cpp
silkworm/sync/sync_pow.hpp
silkworm/sync/test_util/mock_execution_client.hpp

This PR changes the `node` and `sync` modules to use the client/server abstractions built around the [`execution`](https://github.com/ledgerwatch/interfaces/blob/master/execution/execution.proto) interface. Specifically:
- create Execution API DirectClient and Server (disabled by config for now) in `node` module facade
- migrate usage of Execution API Client in `sync` module
- bridge Execution API DirectClient from `node` to `sync` facade in `silkworm` main
*Extras*
- extract sample block generation as common fixture in unit tests
- improve readability by adding some type alias
- handle some more error conditions in PoS sync
This PR depends on #2004 
This PR does *not* remove the old in-process-only implementation yet, another PR will follow

node, sync: use new Execution API client/server

---

cmd/common/common.cpp
cmd/common/common.hpp
cmd/rpcdaemon.cpp
cmd/silkworm.cpp
silkworm/infra/CMakeLists.txt
silkworm/infra/common/application_info.cpp
silkworm/infra/common/application_info.hpp
silkworm/node/common/node_settings.hpp
silkworm/node/node.cpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/rpc/daemon.cpp
silkworm/rpc/daemon.hpp
silkworm/rpc/settings.hpp

This PR extracts into one abstraction in `infra` module the application build information for `silkworm` and `rpcdaemon` components.
This is a prerequisite for implementing `engine_getClientVersionV1` API in next PR.

infra, node, rpcdaemon: refactor application build info

---

silkworm/rpc/commands/engine_api.cpp
silkworm/rpc/commands/engine_api.hpp
silkworm/rpc/commands/engine_api_test.cpp
silkworm/rpc/commands/rpc_api.hpp
silkworm/rpc/commands/rpc_api_table.cpp
silkworm/rpc/daemon.cpp
silkworm/rpc/json/client_version.cpp
silkworm/rpc/json/client_version.hpp
silkworm/rpc/json_rpc/methods.hpp

This PR introduces support for [engine_getClientVersionV1](https://github.com/ethereum/execution-apis/blob/main/src/engine/identification.md#clientversionv1) API in `rpcdaemon` module.
Depends on #2039

rpcdaemon: add engine_getClientVersionV1 API

---

silkworm/db/snapshots/snapshot_test.cpp
silkworm/db/snapshots/txn_snapshot_word_serializer.cpp
silkworm/db/snapshots/txn_snapshot_word_serializer.hpp

transactions.seg files have empty words for system transactions. The queries are not encountering them through serializers, because it was only accessing non-empty words by the indexes. Nonetheless, using "seg unzip" command would encounter them and crash.

snapshots: support empty words in tx deserializers

---

silkworm/db/snapshots/body_txs_amount_query.cpp
silkworm/db/snapshots/body_txs_amount_query_test.cpp
silkworm/db/snapshots/index_builder_test.cpp
silkworm/db/snapshots/snapshot_reader.cpp
silkworm/db/snapshots/snapshot_reader.hpp

In order to reach the last element of the body snapshot, we did `it++` N times (and deserialize N times).
Instead, do `it.skip()` N-1 times and `it++` once.

snapshots: optimize BodyTxsAmountQuery using skip

---

cmake/compiler_warnings.cmake

RelWithDebInfo compilation fails using default gcc on stable Ubuntu and Debian, because it produces mismatched-new-delete warnings in asio which are treated as errors.
I have looked at upstream issues, but haven't found anything related. This is about the same warning, but different code: https://github.com/chriskohlhoff/asio/issues/1391
Example:
```
/home/ubuntu/silkworm/silkworm/sync/sync_pos.cpp: In member function ‘virtual silkworm::Task<silkworm::rpc::PayloadStatus> silkworm::chainsync::PoSSync:new_payload(const silkworm::rpc::NewPayloadRequest&, std::chrono::milliseconds)’:
/home/ubuntu/silkworm/silkworm/sync/sync_pos.cpp:304:1: warning: ‘static void boost::asio::detail::awaitable_frame_base<Executor>::operator delete(void*, std::size_t) [with Executor = …
```

cmake: silent mismatched-new-delete on gcc

---

.circleci/config.yml
.github/workflows/macOS.yml
.github/workflows/windows.yml
README.md
tests/docker/Dockerfile

conan 1.60.2 doesn't work on Ubuntu 24.04 producing an error:
ModuleNotFoundError: No module named 'imp'
because Ubuntu 24.04 has upgraded to Python 3.12 where imp is deprecated and is turned into importlib. conan 1.60.2 doesn't support Python 3.12.

cmake: update conan

---

silkworm/rpc/commands/rpc_api_table.cpp
silkworm/rpc/daemon.cpp
silkworm/rpc/engine/remote_execution_engine.cpp
silkworm/rpc/engine/remote_execution_engine.hpp
silkworm/rpc/json_rpc/methods.hpp

This PR adds a stubbed remote implementation for `engine::ExecutionEngine` in `rpc` module, covering at least partially the (unusual) case of querying the Engine API endpoint in `rpcdaemon` run as standalone component.
A proper implementation will rely on a remote client of our internal Execution gRPC API, which is already available (`execution::grpc::client::RemoteClient`) but would require to refactor the `execution` module out of the `node` module in order not to add an undesired dependency between `rpc` and `node`.

rpcdaemon: add stub for remote Execution engine

---

silkworm/node/remote/kv/grpc/server/backend_kv_server.cpp
silkworm/node/remote/kv/grpc/server/backend_kv_server_test.cpp
silkworm/node/remote/kv/grpc/server/kv_calls.cpp
silkworm/node/remote/kv/grpc/server/kv_calls.hpp

This PR introduces stubbed implementation for "temporal" KV API into our BackEnd-KV gRPC server
*Extras*
Add support for `tx_id` field notification sent by gRPC server after opening `Tx` RPC

rpcdaemon: temporal KV server-side stubbed implementation

---

cmd/capi/execute.cpp
cmd/dev/check_changes.cpp
cmd/dev/snapshots.cpp
silkworm/capi/silkworm.cpp
silkworm/db/access_layer.cpp
silkworm/db/snapshot_benchmark.cpp
silkworm/db/snapshot_bundle_factory_impl.cpp
silkworm/db/snapshot_bundle_factory_impl.hpp
silkworm/db/snapshot_repository_test.cpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync_test.cpp
silkworm/db/snapshots/basic_queries.hpp
silkworm/db/snapshots/common/iterator/iterator_read_into_vector.hpp
silkworm/db/snapshots/common/iterator/map_values_view.hpp
silkworm/db/snapshots/path.hpp
silkworm/db/snapshots/repository.cpp
silkworm/db/snapshots/repository.hpp
silkworm/db/snapshots/repository_test.cpp
silkworm/db/snapshots/snapshot_and_index.hpp
silkworm/db/snapshots/snapshot_bundle.hpp
silkworm/db/snapshots/snapshot_bundle_factory.hpp
silkworm/db/snapshots/snapshot_reader.hpp
silkworm/db/snapshots/snapshot_test.cpp
silkworm/db/snapshots/snapshot_type.hpp
silkworm/db/snapshots/txn_queries.hpp
silkworm/db/snapshots/txs_and_bodies_query.hpp
silkworm/node/node.cpp
silkworm/rpc/daemon.cpp

Refactor data access layer (DAL) logic and schema definition out of SnapshotRepository.
* schema is defined in snapshot_bundle.hpp and snapshot_type.hpp, indexes are defined in SnapshotBundleFactory
* find_segment is exposed with a snapshot type parameter
* view_xx_segments is replaced by iteration on bundles in a forward or reverse order (view_bundles_reverse)
* find_block_number is replaced by a new query object - TransactionBlockNumByTxnHashRepoQuery
that runs TransactionBlockNumByTxnHashQuery on a view of bundles and returns the first match
* replace for_each_xx with nested for loops
* refactor queries to take SnapshotAndIndex
DataModel::read_transactions_from_snapshot: remove an extra reserve

snapshots: refactor SnapshotRepository

---

silkworm/db/snapshots/common/iterator/map_values_view.hpp

snapshots: fix build on Apple clang 14

---

.github/workflows/rpc-performance-tests.yml

**This PR adds an earlier version of change point analysis to perf tests.**
The analysis will run at the end of each test, using historical data published to our MongoDB database.
Output will be added to uploaded artefacts. This is an example of output based on real data: [change_point_analysis.pdf](https://github.com/user-attachments/files/15613335/change_point_analysis.pdf)
**Change Point Analysis** is a process for automatically detecting performance changes for a software product in the presence of _noise_. It answers the question: given the measurements taken over time, is the jump we see a statistical fluctuation or is it a regression?
The version we use was developed by the MongoDB QA team and is based on the E-Divisive means statistical algorithm.
They published scientific papers …

qa-tests: add Change Point analysis to perf tests

---

cmd/dev/check_changes.cpp
cmd/dev/scan_txs.cpp
silkworm/capi/silkworm.cpp
silkworm/core/execution/execution.hpp
silkworm/core/execution/execution_test.cpp
silkworm/core/execution/processor.cpp
silkworm/core/execution/processor.hpp
silkworm/core/protocol/blockchain.cpp
silkworm/core/state/in_memory_state.cpp
silkworm/core/state/in_memory_state.hpp
silkworm/core/state/intra_block_state.cpp
silkworm/core/state/state.hpp
silkworm/db/buffer.cpp
silkworm/db/buffer.hpp
silkworm/db/buffer_test.cpp
silkworm/db/test_util/test_database_context.cpp
silkworm/node/stagedsync/stages/stage_bodies.cpp
silkworm/node/stagedsync/stages/stage_execution.cpp
silkworm/node/stagedsync/stages/stage_history_index_test.cpp
silkworm/node/stagedsync/stages_test.cpp
silkworm/rpc/core/local_state.hpp
silkworm/rpc/core/override_state.hpp
silkworm/rpc/core/remote_state.hpp
silkworm/rpc/core/remote_state_test.cpp

The flat_hash_map has a policy (in `rehash_and_grow_if_necessary()`) to grow 2x when its size reaches 25/32 (78%) of capacity.
Previously the batch execution logic was adding things to db::Buffer, and then testing if its size becomes bigger than batch_size. This lead to significant overshooting, because at the growth threshold it will double the memory size and make it batch_size * 2 (even more, because there's also unused 22% of capacity).
In standalone silkworm execution stage the batch_size estimation was based on a gas-based heuristic formula, which lead to significant underestimation and an OOM crash when trying to allocate 4 Gb of RAM at once.
This changes the logic from checking batch_size aposteriori to apriori. If there's a possibility to grow the buffer significantly and …

execution: fix OOM crash due to db::Buffer::accounts realloc (#2064)

---

.github/workflows/rpc-performance-tests.yml

Some tests utilise a prebuilt database.
To facilitate historical comparisons, it is useful to record the exact version of Erigon used to pre-build this database

qa-tests: record the db version used for test

---

silkworm/rpc/commands/erigon_api.cpp
silkworm/rpc/commands/erigon_api.hpp
silkworm/rpc/commands/erigon_api_test.cpp
silkworm/rpc/commands/rpc_api_table.cpp
silkworm/rpc/core/rawdb/chain.cpp
silkworm/rpc/core/rawdb/chain.hpp
silkworm/rpc/core/rawdb/chain_test.cpp
silkworm/rpc/json_rpc/methods.hpp
silkworm/rpc/storage/chain_storage.hpp

The `erigon_cumulativeChainTraffic` API was removed from erigon in release 2.49

rpcademon: remove erigon_cumulativeChainTraffic

---

docs/fuzzer.md
silkworm/rpc/daemon.cpp
silkworm/rpc/json_rpc/request_handler.cpp
silkworm/rpc/json_rpc/request_handler.hpp
silkworm/rpc/json_rpc/validator.cpp
silkworm/rpc/json_rpc/validator.hpp
silkworm/rpc/json_rpc/validator_benchmark.cpp
silkworm/rpc/json_rpc/validator_test.cpp
silkworm/rpc/test_util/api_test_database.hpp

Avoid repetition in `json_rpc::JsonRpcValidator` renaming it as `json_rpc::Validator`

rpcdaemon: rename json_rpc::JsonRpcValidator

---

silkworm/rpc/commands/debug_api.cpp
silkworm/rpc/commands/engine_api.cpp
silkworm/rpc/commands/erigon_api.cpp
silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/commands/ots_api.cpp
silkworm/rpc/core/call_many.cpp
silkworm/rpc/core/estimate_gas_oracle.cpp
silkworm/rpc/core/estimate_gas_oracle_test.cpp
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/rawdb/chain.cpp
silkworm/rpc/json/types.cpp
silkworm/rpc/json/types.hpp
silkworm/rpc/storage/chain_storage.hpp
silkworm/rpc/storage/local_chain_storage.cpp
silkworm/rpc/storage/local_chain_storage.hpp
silkworm/rpc/storage/remote_chain_storage.cpp
silkworm/rpc/storage/remote_chain_storage.hpp
silkworm/rpc/storage/remote_chain_storage_test.cpp
silkworm/rpc/test_util/mock_chain_storage.hpp

This PR removes `std::optional` from the returned type of `ChainStorage::read_chain_config` and raises an exception in case of missing chain configuration.
Fixes #2103
*Extras*
- change the type of exception raised by `read_head_header_hash`
- pass `into::uint256` by reference in `to_quantity`

rpcdaemon: remove optional in read chain config

---

.github/workflows/rpc-performance-tests.yml

Create a pdf with plots of the latency percentile distributions (a plot for each qps and repetition).
Data is created with Vegeta option `report -type=hdrplot` (see rpc-tests [v0.26](https://github.com/erigontech/rpc-tests/releases/tag/v0.26.0))
Relevant documentation:
- [HdrHistogram](https://hdrhistogram.github.io/HdrHistogram/)
- [report --typehdrplot](https://github.com/tsenart/vegeta?tab=readme-ov-file#report--typehdrplot)

qa-tests: add latency percentile analysis

---

cmd/dev/db_toolbox.cpp
silkworm/capi/silkworm_test.cpp
silkworm/db/snapshot_sync_test.cpp
silkworm/db/snapshots/bittorrent/client_test.cpp
silkworm/infra/common/directories.cpp
silkworm/infra/common/directories.hpp
silkworm/infra/common/directories_test.cpp

Make sure that tests do not use a current working directory. They should use TemporaryDirectory for isolation.

fix unit tests to not write in cwd

---

silkworm/db/kv/api/base_transaction.cpp
silkworm/db/kv/api/state_cache.cpp
silkworm/db/kv/api/state_cache.hpp

This PR contains a small refactoring in `kv::api::StateCache` following the move from `rpc` to `db` module made in #2136

db: use ByteView in KV StateCache

---

silkworm/rpc/commands/admin_api.cpp
silkworm/rpc/commands/debug_api.cpp
silkworm/rpc/commands/engine_api.cpp
silkworm/rpc/commands/erigon_api.cpp
silkworm/rpc/commands/erigon_api_test.cpp
silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/commands/net_api.cpp
silkworm/rpc/commands/ots_api.cpp
silkworm/rpc/commands/parity_api.cpp
silkworm/rpc/commands/rpc_api_table_test.cpp
silkworm/rpc/commands/trace_api.cpp
silkworm/rpc/commands/txpool_api.cpp
silkworm/rpc/commands/web3_api.cpp
silkworm/rpc/core/estimate_gas_oracle_test.cpp
silkworm/rpc/core/evm_executor.hpp
silkworm/rpc/json_rpc/request_handler_test.cpp

This PR adds usage of enumeration values for protocol error codes in JSON RPC API implementations, using the following rules:
- all existing error code values have been kept unchanged, except for 100 (which is invalid error code)
- existing error codes hard-coded to 100 have been mapped to `kInvalidParams = -32602`, `kInternalError = -32603` or `kServerError = -32000` depending on the context
*Extras*
- remove unnecessary `co_return` at the end of API handlers
- add some unit tests for API handler dispatching

rpcdaemon: enum values for protocol error codes

---

silkworm/capi/CMakeLists.txt

silkworm_db is a smaller dependency than silkworm_node

capi: depend on silkworm_db rather than silkworm_node

---

silkworm/db/access_layer.cpp
silkworm/db/access_layer.hpp
silkworm/db/bodies/body_snapshot_freezer.cpp
silkworm/db/bodies/body_snapshot_freezer.hpp
silkworm/db/data_migration.cpp
silkworm/db/data_migration.hpp
silkworm/db/freezer.cpp
silkworm/db/freezer.hpp
silkworm/db/headers/header_snapshot_freezer.cpp
silkworm/db/headers/header_snapshot_freezer.hpp
silkworm/db/snapshot_bundle_factory_impl.cpp
silkworm/db/snapshot_freezer.hpp
silkworm/db/snapshots/repository.cpp
silkworm/db/snapshots/repository.hpp
silkworm/db/snapshots/snapshot_bundle.cpp
silkworm/db/snapshots/snapshot_bundle.hpp
silkworm/db/snapshots/snapshot_bundle_factory.hpp
silkworm/db/transactions/txn_snapshot_freezer.cpp
silkworm/db/transactions/txn_snapshot_freezer.hpp
silkworm/db/transactions/txn_snapshot_word_serializer.hpp

Freezer implements a data migration process from mdbx to snapshots.
Each snapshot type implements a SnapshotFreezer interface to copy the data.
The data migration is implemented. Cleanup and stageloop integration will be implemented later.
DataMigration::run implements a single migration pass, later on we'll run it in a loop with some sleep().
SnapshotRepository thread-safety is improved, but not entirely. We can't rely on a single mutex for repo queries that loop over bundles. This has to be addressed later.

db: snapshots freezer

---

.github/workflows/rpc-performance-tests.yml

Protect output files from being overwritten. 
Save the analysis results to the history directory.

qa-tests: save latency percentile distribution analysis data in backup directory

---

silkworm/rpc/http/connection.cpp
silkworm/rpc/http/connection.hpp

rpcdaemon: support compression on HTTP streaming

---

silkworm/core/execution/call_tracer.cpp
silkworm/core/execution/precompile.cpp
silkworm/core/protocol/intrinsic_gas.cpp
silkworm/core/protocol/intrinsic_gas.hpp
silkworm/core/protocol/intrinsic_gas_test.cpp

`num_words` in evmone can overflow potentially (see https://github.com/ethereum/evmone/pull/945), but it's not a problem there because its inputs are guarded by `check_memory`.

core: introduce overflow-safe num_words

---

.github/workflows/rpc-integration-tests.yml
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp

Added static call in gas cost evaluation
code review

rpcdaeomon: static call in gas cost for debug API endpoints

---

silkworm/infra/common/log_test.cpp
silkworm/infra/concurrency/context_pool.cpp
silkworm/infra/concurrency/context_pool_test.cpp

This PR fixes a some failing checks in `infra` unit tests when executed directly on terminal console
*Extras*
- remove one clang tidy warning
- add a couple more tests

Infra: fix regression in unit tests when executed directly on terminal console

---

silkworm/db/kv/api/direct_service.cpp
silkworm/db/kv/api/direct_service.hpp
silkworm/db/kv/api/direct_service_test.cpp
silkworm/db/kv/api/service_router.cpp
silkworm/db/kv/api/service_router.hpp
silkworm/db/kv/grpc/client/remote_client.cpp
silkworm/db/kv/grpc/client/remote_client.hpp
silkworm/db/kv/grpc/client/remote_client_test.cpp
silkworm/db/kv/state_changes_stream_test.cpp
silkworm/db/test_util/test_database_context.hpp
silkworm/infra/grpc/test_util/test_runner.hpp
silkworm/rpc/daemon.cpp

This PR implements the `db::kv::api::Transaction` factory responsibility into the existing KV API clients (both direct and gRPC).
Moreover, the two flavours of KV API clients are now properly created in `rpc::Daemon` at startup.
*TODO*
In case of standalone RpcDaemon, proper running lifecycle and a more polished object composition for KV API direct service is still missing.

db: KV begin_transaction as txn factory

---

silkworm/db/kv/api/endpoint/paginated_sequence.hpp
silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp

This PR introduces support for a hand-crafted paginated sequence of values to be used in the definition of `temporal KV` API endpoints. Such abstraction allows user code to navigate a paginated contiguous sequence of values without bothering about pagination at call site.
If performance measurements in standalone mode (i.e. direct KV client) will show significant overhead caused by this approach, we can relax this requirement to hide pagination at call site and try to obtain faster code.
*Design Alternatives*
We're going to use this abstraction for both direct and gRPC KV client implementations and we cannot block the coroutine scheduler in gRPC case, so we do need a common asynchronous interface definition. This requirement (which could be challenged if performance results are not …

db: paginated sequence for temporal KV API

---

.clang-tidy
cmd/state-transition/state_transition.cpp
cmd/state-transition/state_transition.hpp
cmd/test/backend_kv_test.cpp
silkworm/core/crypto/sha256.c
silkworm/core/state/intra_block_state.cpp
silkworm/node/stagedsync/forks/fork.cpp
silkworm/node/stagedsync/stages/stage_bodies.cpp
silkworm/node/stagedsync/stages/stage_headers.cpp
silkworm/rpc/commands/ots_api.cpp
silkworm/rpc/commands/ots_api.hpp
silkworm/rpc/ethdb/split_cursor.cpp
silkworm/sync/internals/chain_elements.hpp
silkworm/sync/messages/inbound_new_block.cpp
silkworm/sync/messages/inbound_new_block_hashes.cpp

and also cppcoreguidelines-macro-to-enum

clang-tidy: fix cppcoreguidelines-prefer-member-initializer

---

cmd/dev/grpc_toolbox.cpp
silkworm/core/common/bytes_to_string.hpp
silkworm/db/kv/api/direct_service.cpp
silkworm/db/kv/api/direct_service.hpp
silkworm/db/kv/api/endpoint/key_value.hpp
silkworm/db/kv/api/endpoint/paginated_sequence.hpp
silkworm/db/kv/api/endpoint/temporal_range.hpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/api/local_transaction.hpp
silkworm/db/kv/api/service.hpp
silkworm/db/kv/api/transaction.hpp
silkworm/db/kv/grpc/client/endpoint/temporal_range.cpp
silkworm/db/kv/grpc/client/remote_client.cpp
silkworm/db/kv/grpc/client/remote_client_test.cpp
silkworm/db/kv/grpc/client/remote_transaction.cpp
silkworm/db/kv/grpc/client/remote_transaction.hpp
silkworm/db/kv/grpc/client/remote_transaction_test.cpp
silkworm/db/kv/grpc/test_util/sample_protos.hpp
silkworm/db/test_util/mock_transaction.hpp
silkworm/rpc/commands/debug_api_test.cpp
silkworm/rpc/core/account_dumper_test.cpp
silkworm/rpc/core/account_walker_test.cpp
silkworm/rpc/core/storage_walker_test.cpp
silkworm/rpc/test_util/dummy_transaction.hpp

This PR implements temporal KV `history_range` API in gRPC client. The following interface changes become necessary:
- first of all, the declaration of such API must be moved from `api::Service` to `api::Transaction`, as the input `api::HistoryRangeQuery` always needs to specify the `tx_id`, i.e. the unique identifier of the enclosing db transaction
- then, the return type becomes `api::PaginatedKeysValues`, which is a sequence of keys and values paginated by using the new `api::PaginatedSequencePair<K, V>` abstraction
*Extras*
- `cmd`: add `kv_history_range` command in `grpc_toolbox` to allow testing _HistoryRange_ KV RPC wrt Erigon3
- `rpc`: add utility functions to create empty paginators

db: temporal KV client history_range API via gRPC

---

cmd/dev/README.md
cmd/dev/grpc_toolbox.cpp
silkworm/db/kv/api/direct_service.cpp
silkworm/db/kv/api/direct_service.hpp
silkworm/db/kv/api/endpoint/temporal_point.hpp
silkworm/db/kv/api/endpoint/temporal_range.hpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/api/local_transaction.hpp
silkworm/db/kv/api/service.hpp
silkworm/db/kv/api/transaction.hpp
silkworm/db/kv/grpc/client/endpoint/temporal_point_test.cpp
silkworm/db/kv/grpc/client/endpoint/temporal_range.cpp
silkworm/db/kv/grpc/client/endpoint/temporal_range_test.cpp
silkworm/db/kv/grpc/client/remote_client.cpp
silkworm/db/kv/grpc/client/remote_client_test.cpp
silkworm/db/kv/grpc/client/remote_transaction.cpp
silkworm/db/kv/grpc/client/remote_transaction.hpp
silkworm/db/kv/grpc/client/remote_transaction_test.cpp
silkworm/db/kv/grpc/test_util/sample_protos.hpp
silkworm/db/test_util/mock_transaction.hpp
silkworm/rpc/commands/debug_api_test.cpp
silkworm/rpc/core/account_dumper_test.cpp
silkworm/rpc/core/account_walker_test.cpp
silkworm/rpc/core/storage_walker_test.cpp
silkworm/rpc/test_util/dummy_transaction.hpp

This PR implements temporal KV `domain_range` API in gRPC client. The following interface changes become necessary:
- first of all, the declaration of such API must be moved from `api::Service` to `api::Transaction`, as the input `api::DomainRangeQuery` always needs to specify the `tx_id`, i.e. the unique identifier of the enclosing db transaction
- then, the return type becomes `api::PaginatedKeysValues`, which is a sequence of keys and values paginated by using the existing `api::PaginatedSequencePair<K, V>` abstraction
*Extras*
- `cmd`: add `kv_domain_range` command in `grpc_toolbox` to allow testing _DomainRange_ KV RPC wrt Erigon3

db: temporal KV client domain_range API via gRPC

---

docs/CONTRIBUTING.md
silkworm/db/kv/grpc/client/endpoint/temporal_point.cpp
silkworm/db/kv/grpc/client/endpoint/temporal_point.hpp
silkworm/db/kv/grpc/client/endpoint/temporal_point_test.cpp
silkworm/db/kv/grpc/client/endpoint/temporal_range.cpp
silkworm/db/kv/grpc/client/remote_client.cpp
silkworm/db/kv/grpc/client/remote_client_test.cpp
silkworm/db/kv/grpc/server/kv_calls.cpp
silkworm/db/kv/grpc/server/kv_calls.hpp
silkworm/db/kv/grpc/server/kv_server.cpp
silkworm/db/kv/grpc/server/kv_server_test.cpp
silkworm/db/kv/grpc/test_util/sample_protos.hpp
silkworm/infra/grpc/test_util/interfaces/kv_mock_fix24351.grpc.pb.h
silkworm/interfaces/3.21.12/execution/execution.pb.cc
silkworm/interfaces/3.21.12/execution/execution.pb.h
silkworm/interfaces/3.21.12/p2psentry/sentry.pb.cc
silkworm/interfaces/3.21.12/remote/ethbackend.pb.cc
silkworm/interfaces/3.21.12/remote/kv.grpc.pb.cc
silkworm/interfaces/3.21.12/remote/kv.grpc.pb.h
silkworm/interfaces/3.21.12/remote/kv.pb.cc
silkworm/interfaces/3.21.12/remote/kv.pb.h
silkworm/interfaces/3.21.12/remote/kv_mock.grpc.pb.h
silkworm/interfaces/3.21.12/txpool/mining.pb.cc
silkworm/interfaces/3.21.12/txpool/txpool.pb.cc
silkworm/interfaces/3.21.12/types/types.pb.cc
silkworm/interfaces/3.21.12/types/types.pb.h

This PR updates the internal gRPC interfaces to https://github.com/erigontech/interfaces/commit/0d10589c853376fc093fafc4c45d4d2c48f8e9e4, which is compatible with the one used in Erigon2 https://github.com/ledgerwatch/interfaces/commit/b57f05746087760985ae755dd1431a35377a2363 but also contains the change in https://github.com/erigontech/interfaces/commit/51e2d4cc3e3980924696cceb0e79f5560b5c50ea necessary to work with Erigon3 Temporal KV.
*Extras*
- fix encoding/decoding for keys and values in gRPC _HistorySeek_
- fix the procedure to update gRPC interfaces into our Contribution Guide

Interfaces: upgrade to 0d10589

---

cmd/dev/grpc_toolbox.cpp
silkworm/db/kv/api/direct_service.cpp
silkworm/db/kv/api/direct_service.hpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/api/local_transaction.hpp
silkworm/db/kv/api/service.hpp
silkworm/db/kv/api/transaction.hpp
silkworm/db/kv/grpc/client/remote_client.cpp
silkworm/db/kv/grpc/client/remote_client_test.cpp
silkworm/db/kv/grpc/client/remote_transaction.cpp
silkworm/db/kv/grpc/client/remote_transaction.hpp
silkworm/db/kv/grpc/client/remote_transaction_test.cpp
silkworm/db/test_util/mock_transaction.hpp
silkworm/rpc/commands/debug_api_test.cpp
silkworm/rpc/core/account_dumper_test.cpp
silkworm/rpc/core/account_walker_test.cpp
silkworm/rpc/core/storage_walker_test.cpp
silkworm/rpc/test_util/dummy_transaction.hpp

This PR implements temporal KV `history_seek` API in gRPC client. The following interface changes become necessary:
- the declaration of such API must be moved from `api::Service` to `api::Transaction`, as the input `api::HistoryPointQuery` always needs to specify the `tx_id`, i.e. the unique identifier of the enclosing db transaction
*Extras*
- `cmd`: add `kv_ history_seek` command in `grpc_toolbox` to allow testing _ HistorySeek_ KV RPC wrt Erigon3

db: temporal KV client history_seek API via gRPC

---

.github/workflows/rpc-integration-tests.yml

Currently, integration tests only save the outcome on the database: success or failure, and no other information.
Since integration tests are necessary for a PR to be accepted, it is not very useful to save the outcome on the database. This also blocks a PR in case of failure of saving, blocking the developers' work.
This PR removes the "save  results" task.

rpc-integration-tests: avoid saving unuseful result

---

cmd/dev/grpc_toolbox.cpp
silkworm/db/kv/api/direct_service.cpp
silkworm/db/kv/api/direct_service.hpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/api/local_transaction.hpp
silkworm/db/kv/api/service.hpp
silkworm/db/kv/api/transaction.hpp
silkworm/db/kv/grpc/client/endpoint/temporal_point.cpp
silkworm/db/kv/grpc/client/remote_client.cpp
silkworm/db/kv/grpc/client/remote_client_test.cpp
silkworm/db/kv/grpc/client/remote_transaction.cpp
silkworm/db/kv/grpc/client/remote_transaction.hpp
silkworm/db/kv/grpc/client/remote_transaction_test.cpp
silkworm/db/kv/grpc/test_util/sample_protos.hpp
silkworm/db/test_util/mock_transaction.hpp
silkworm/rpc/commands/debug_api_test.cpp
silkworm/rpc/core/account_dumper_test.cpp
silkworm/rpc/core/account_walker_test.cpp
silkworm/rpc/core/storage_walker_test.cpp
silkworm/rpc/test_util/dummy_transaction.hpp

This PR implements temporal KV `domain_get` API in gRPC client. The following interface changes become necessary:
- the declaration of such API must be moved from `api::Service` to `api::Transaction`, as the input `api::DomainPointQuery` always needs to specify the `tx_id`, i.e. the unique identifier of the enclosing db transaction
*Extras*
- `cmd`: add `kv_domain_get` command in `grpc_toolbox` to allow testing _DomainGet_ KV RPC wrt Erigon3
- fix wire format for keys and values in gRPC

db: temporal KV client domain_get API via gRPC

---

.github/workflows/rpc-performance-tests.yml

Performance tests do not (yet) have a status indicating success or failure based on the result of measurements: the performance numbers are compared manually after the test completion. Furthermore, they do not block PRs.
We are working on automatic regression detection, but in the meantime we think it is useful to signal with a test failure any error in saving the measurements, since this is a crucial part of the test to allow a-posteriori analysis.

rpc-performance-tests: preserve the results

---

silkworm/db/access_layer.cpp
silkworm/db/access_layer.hpp
silkworm/db/bodies/body_snapshot_freezer.cpp
silkworm/db/bodies/body_snapshot_freezer.hpp
silkworm/db/freezer.cpp
silkworm/db/freezer.hpp
silkworm/db/headers/header_snapshot_freezer.cpp
silkworm/db/headers/header_snapshot_freezer.hpp
silkworm/db/snapshot_freezer.hpp
silkworm/db/transactions/txn_snapshot_freezer.cpp
silkworm/db/transactions/txn_snapshot_freezer.hpp

Prune block data that was copied to snapshots from mdbx.

db: snapshot freezers cleanup

---

silkworm/capi/fork_validator.cpp

This PR fix Windows build after #2201.
The error was misleading because MSVC 19.40 complains about [Compiler Error C2440](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2440?view=msvc-170), which seems strange at first, but in the end it's due to the missing conversion operator from `std::filesystem::path` to `std::string`.
*Extras*
- remove unused include
- simplify some expressions as suggested by CLion

capi: fix Windows build after PR 2201

---

.github/workflows/rpc-integration-tests.yml
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp

Fix on debug trace api family for call memory gas cost

rpcdaemon: fix memory gas cost in call

---

silkworm/rpc/core/call_many.cpp
silkworm/rpc/core/fee_history_oracle.cpp

Calling preallocate on a collection keeping nlohmann::json caused the push_back to place elements beyond the allocated space.

rpcdaemon: fixing fuzzer tests

---

.circleci/config.yml
.github/workflows/rpc-fuzzer-tests.yml
.gitmodules
README.md
docs/CONTRIBUTING.md
silkworm/core/protocol/rule_set.hpp
silkworm/db/test_util/test_database_context.cpp
tests/docker/Dockerfile
tests/docker/run-docker.sh
third_party/evmone/CMakeLists.txt

third_party: update evmone to v0.12.0

---

.github/workflows/macOS.yml
.github/workflows/windows.yml

ci: avoid cancelling master workflow pushing on ci/* branch

---

silkworm/db/access_layer.cpp
silkworm/db/access_layer.hpp
silkworm/db/bodies/body_snapshot_freezer.cpp
silkworm/db/bodies/body_snapshot_freezer.hpp
silkworm/db/data_migration_command.hpp
silkworm/db/freezer.cpp
silkworm/db/headers/header_snapshot_freezer.cpp
silkworm/db/headers/header_snapshot_freezer.hpp
silkworm/db/snapshot_freezer.hpp
silkworm/db/transactions/txn_snapshot_freezer.cpp
silkworm/db/transactions/txn_snapshot_freezer.hpp

Original mdbx txn_id might have gaps due to chain reorgs. When moving the data to snapshots we remove potential gaps in BlockBodyForStorage txn_id. This makes snapshot files identical across nodes because different nodes might encounter different chain reorgs.
Note: the sequential numbering is called "TxNum" in erigon.

db: BodySnapshotFreezer use sequential txn_id without gaps

---

silkworm/db/access_layer.cpp
silkworm/db/access_layer.hpp
silkworm/db/kv/api/cursor.hpp
silkworm/db/kv/api/local_cursor.cpp
silkworm/db/kv/api/local_cursor.hpp
silkworm/db/kv/api/local_cursor_test.cpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/grpc/client/remote_cursor.cpp
silkworm/db/kv/grpc/client/remote_cursor.hpp
silkworm/db/kv/grpc/client/remote_cursor_test.cpp
silkworm/db/mdbx/mdbx.cpp
silkworm/db/mdbx/mdbx.hpp
silkworm/db/test_util/mock_cursor.hpp
silkworm/infra/grpc/test_util/grpc_matcher.hpp
silkworm/rpc/commands/debug_api_test.cpp
silkworm/rpc/core/account_dumper_test.cpp
silkworm/rpc/core/account_walker_test.cpp
silkworm/rpc/core/storage_walker_test.cpp

This PR adds missing `first` and `last` queries in local (i.e. in-process) implementation of `KV` API cursor.
*Extras*
- remove unused `read_rlp_encoded_header` function from DB access layer
- add unit tests for both remote and local cursor implementations
- add `exception_has_aborted_grpc_status_code` test utility

db: first and last queries in KV local cursor

---

cmd/capi/execute.cpp
cmd/dev/snapshots.cpp
silkworm/db/access_layer.cpp
silkworm/db/snapshot_repository_test.cpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshots/repository.cpp
silkworm/db/snapshots/repository.hpp
silkworm/db/transactions/txn_queries.hpp

depends on https://github.com/erigontech/silkworm/pull/2215
Protect view_bundles and find_segment from threading issues without blocking too much.
The method is similar to the one used for e3 snapshots.
Bundles list is now a shared pointer and follows "copy on write" logic. If multiple readers want to read snapshots, they copy the source shared pointer (increasing a reference count). Modifying the bundles list (e.g. by add_snapshot_bundle) makes a copy. The old list and its iterators will be still usable by the readers from their shared pointers. When all the readers finish, the old list will be destroyed.
view_bundles() returns a BundlesView that holds the bundles list shared pointer for the iteration duration. This ensures that on bundles list modification the iterated list is not …

db: snapshots repository thread safety

---

silkworm/rpc/json_rpc/specification.json

Adding specification for `debug_accountRange` call.

Adding accountRange spec

---

silkworm/db/kv/txn_num.cpp
silkworm/db/kv/txn_num.hpp
silkworm/db/kv/txn_num_test.cpp
silkworm/db/tables.hpp

This PR introduces a basic facility wrapped around `KV` API to read the blockchain transaction (i.e. `txn`) unique numbering by querying `MaxTxNum` table.
See also https://github.com/erigontech/erigon/blob/main/erigon-lib/kv/rawdbv3/txnum.go for reference.

db: txn unique numbering over KV API

---

cmd/dev/db_toolbox.cpp
silkworm/db/data_migration.cpp
silkworm/db/data_migration.hpp
silkworm/db/freezer.cpp
silkworm/db/freezer.hpp
silkworm/db/snapshots/repository.cpp
silkworm/db/snapshots/repository.hpp
silkworm/db/stage_scheduler.hpp
silkworm/db/stages.hpp
silkworm/node/node.cpp
silkworm/node/stagedsync/execution_engine.cpp
silkworm/node/stagedsync/execution_engine.hpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/execution_pipeline.hpp
silkworm/node/stagedsync/forks/main_chain.cpp
silkworm/node/stagedsync/forks/main_chain.hpp
silkworm/node/stagedsync/stages/stage_triggers.cpp
silkworm/node/stagedsync/stages/stage_triggers.hpp

Run freezer data migration as a part of node tasks.
Freezer cleanup requires an RWTxn.
For that reason, schedule it in the stage loop via a helper TriggersStage.

db: integrate snapshot freezer

---

cmd/dev/grpc_toolbox.cpp
silkworm/db/snapshots/common/iterator/map_values_view.hpp
silkworm/db/snapshots/index_builder.hpp
silkworm/db/snapshots/repository.cpp
silkworm/db/snapshots/repository.hpp
silkworm/db/snapshots/seg/decompressor.hpp
silkworm/db/snapshots/snapshot_reader.hpp
silkworm/db/snapshots/snapshot_writer.hpp
silkworm/db/transactions/txs_and_bodies_query.hpp
silkworm/rpc/core/filter_storage.hpp
silkworm/rpc/core/gas_price_oracle.hpp
silkworm/rpc/types/log.hpp
silkworm/sentry/api/router/messages_call.hpp
silkworm/sentry/api/router/peer_events_call.hpp
silkworm/sentry/common/random.hpp
silkworm/sync/packets/hash_or_number.hpp

* using instead of typedef
* [[maybe_unused]] for iterator_category
* no T prefix for concrete type aliases

style: typedef consistency improvements

---

silkworm/core/types/account.cpp

This PR fixes the unit test failures happening on master branch after merging #2251

core: fix decoding account from E3 encoded storage

---

cmd/dev/CMakeLists.txt
cmd/dev/db_toolbox.cpp
silkworm/db/access_layer.cpp
silkworm/db/blocks/bodies/body_snapshot_freezer.cpp
silkworm/db/blocks/headers/header_snapshot_freezer.cpp
silkworm/db/data_migration.cpp
silkworm/db/data_migration.hpp
silkworm/db/data_migration_command.hpp
silkworm/db/freezer.cpp
silkworm/db/freezer.hpp
silkworm/db/snapshot_freezer.hpp
silkworm/db/stage_scheduler.hpp
silkworm/db/transactions/txn_snapshot_freezer.cpp
silkworm/node/stagedsync/stages/stage_triggers.cpp
silkworm/node/stagedsync/stages/stage_triggers.hpp

Fixes after testing db_toolbox freeze command:
* dedicated thread for RWTxn, call tx.commit_and_stop
* simplify schedule callback
* SnapshotRepository setup fixes
* DataMigration and cleanup logging
* cursor->lower_bound in read_stored_header_number_after

db: db_toolbox freeze fixes

---

.clang-tidy
cmd/dev/db_toolbox.cpp
silkworm/core/protocol/intrinsic_gas.hpp
silkworm/db/snapshots/seg/compressor/lcp_kasai.cpp
silkworm/infra/common/log.hpp
silkworm/infra/concurrency/idle_strategy.hpp
silkworm/node/common/node_settings.hpp
silkworm/rpc/common/util.cpp
silkworm/rpc/core/evm_access_list_tracer.hpp
silkworm/sync/internals/chain_elements.hpp

[redundant-inline-specifier](https://clang.llvm.org/extra/clang-tidy/checks/readability/redundant-inline-specifier.html)
[redundant-smartptr-get](https://clang.llvm.org/extra/clang-tidy/checks/readability/redundant-smartptr-get.html)
[simplify-boolean-expr](https://clang.llvm.org/extra/clang-tidy/checks/readability/simplify-boolean-expr.html)

clang-tidy: fix some readability warnings

---

.github/workflows/rpc-integration-tests.yml
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace.hpp

Synthesise OP_STOP as last opcode in `trace` and `debug` API if execution is successful and last opcode executed is NOT in [OP_SELFDESTRUCT, OP_RETURN, OP_STOP]

rpcdaemon: add STOP opcode as last opcode in specific success cases

---

silkworm/infra/concurrency/context_pool_test.cpp
silkworm/infra/grpc/client/client_context_pool.cpp
silkworm/infra/grpc/client/client_context_pool.hpp
silkworm/infra/grpc/client/client_context_pool_test.cpp

This PR fixes a nasty bug that _may_ happen during closure of `rpcdaemon` because of the interaction between how our gRPC client context-pool-based threading model works and its cleanup during shutdown.
Some background:
- the `concurrency::ContextPool` class models a pool of task schedulers a.k.a. execution contexts used to process tasks asynchronously and is based on `boost::asio::io_context` abstraction. When using the multi-threaded scheduling strategy (the default one), `concurrency::ContextPool` uses a pool of N threads and each of them runs exactly one `boost::asio::io_context` task loop
- the `rpc::ClientContextPool` class extends `concurrency::ContextPool` by adding support for gRPC-based execution contexts, specifically using N `agrpc::GrpcContext` objects from …

infra: fix ClientContextPool destruction after mixed dispatching

---

silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/http/jwt.cpp
silkworm/rpc/http/jwt_test.cpp

This PR introduces creation of intermediate folders if configured JWT path does not exist.
*Extras*
- add missing `const` specifier
- fix link in comment

rpcdaemon: fix JWT file creation if path not existent

---

silkworm/rpc/daemon.cpp
silkworm/wasm/silkworm_wasm_api.cpp
silkworm/wasm/silkworm_wasm_api.hpp

This PR fixes the WASM build broken after PR #2253 that changed the signature of `silkworm::State::read_code` method to include the account address, necessary for E3 Temporal KV `DomainGet`.

wasm: fix interface after PR 2253

---

cmd/dev/db_toolbox.cpp

This PR adds `force_update` option to `schema` subcommand of `snapshots` command-line utility to update the database schema to the current Silkworm code version. This is useful when upgrading the code between compatible versions or if at some point embedded versioning was wrong (i.e. not correctly updated to match Erigon's one).

cmd: support version update in schema command of snapshots tool

---

silkworm/infra/common/timer.cpp
silkworm/infra/common/timer.hpp
silkworm/infra/common/timer_test.cpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/stages/stage_headers.cpp

Fixes #2296 
The previous `Timer` class has been renamed as `TimerImpl` and used as implementation facility, wrapped around the new `Timer` which uses RAII to guarantee cancellation on destruction.
*Extras*
- node: demote log traces in stage Headers
- node: add warning in case of sync interrupted by STOP_AT_BLOCK env variable

infra: fix timer cancellation using RAII

---

cmd/dev/snapshots.cpp
cmd/silkworm.cpp
silkworm/db/access_layer.cpp
silkworm/db/access_layer.hpp
silkworm/db/access_layer_test.cpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync.hpp
silkworm/db/snapshot_sync_test.cpp
silkworm/db/snapshots/bittorrent/client_test.cpp
silkworm/db/snapshots/bittorrent/settings.hpp
silkworm/db/snapshots/bittorrent/web_seed_client_test.cpp
silkworm/db/snapshots/config.cpp
silkworm/db/snapshots/config.hpp
silkworm/db/snapshots/config_test.cpp
silkworm/db/util.hpp
silkworm/infra/concurrency/awaitable_condition_variable.hpp
silkworm/infra/concurrency/awaitable_future.hpp
silkworm/node/node.cpp
silkworm/node/node.hpp

* Expand SnapshotSync to be responsible for snapshots management including: owning SnapshotRepository, running Freezer and SnapshotMerger, owning BitTorrentClient and seeding snapshots.
* Node contains SnapshotSync. It waits for the SnapshotSync setup before running other components.
* chainsync::Sync also waits for the SnapshotSync setup before starting.
* BitTorrentClient runs all the time in SnapshotSync (before and after setup) to provide seeding. A torrent client is removed from Node.
* download and related methods use async logic instead of is_stopping flag.
* download_snapshots: adding torrents happens after subscriptions, because the client always runs
* update_database are kept sync and use a dedicated is_stopping_latch_ to quit ASAP
* snapshot_sync_test: refactoring to minimize …

db: move snapshots management from node to snapshot_sync

---

silkworm/db/snapshot_merger.cpp
silkworm/db/snapshot_merger.hpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync.hpp
silkworm/db/snapshots/bittorrent/client.cpp
silkworm/db/snapshots/bittorrent/client_test.cpp
silkworm/db/snapshots/bittorrent/torrent_file.cpp
silkworm/db/snapshots/bittorrent/torrent_file.hpp
silkworm/db/snapshots/config.cpp
silkworm/db/snapshots/config.hpp
silkworm/db/snapshots/config_test.cpp
silkworm/db/snapshots/snapshot_path.hpp
silkworm/db/snapshots/snapshot_repository.hpp
silkworm/db/snapshots/snapshot_size.hpp

* seed locally generated frozen snapshots on startup
* seed locally generated frozen snapshots when they are generated
* exclude small snapshots from seeding/downloading (will be improved later)
* don't ignore IO errors in BitTorrentClient load_file/save_file

db: snapshots seeding

---

silkworm/sentry/rlpx/client.cpp
silkworm/sentry/rlpx/peer.cpp
silkworm/sentry/rlpx/peer.hpp
silkworm/sentry/rlpx/server.cpp

sentry: handle errors when accessing socket endpoints

---

README.md
cmake/toolchain/cxx20.cmake
cmd/capi/sample-go-client/README.md

fixes ld: warning: object file libtorrent-rasterbar.a[2](add_torrent_params.cpp.o) was built for newer 'macOS' version (14.0) than being linked (13.3)

cmake: update min macOS to 14.0

---

.github/workflows/rpc-integration-tests.yml
silkworm/core/state/intra_block_state.cpp
silkworm/rpc/commands/trace_api.cpp
silkworm/rpc/core/evm_executor.cpp
silkworm/rpc/core/evm_executor_test.cpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace.hpp
silkworm/rpc/core/evm_trace_test.cpp

This PR contains:
- gas bailout disabled in `trace_get` and `trace_transaction`
- if gas bailout is enabled, do not subtract gas cost and do not refund gas in bailout-enabled `trace` API
*Details*
These changes required to mark as touched in `IntraBlockState` any address having code or nonce changed w/o any balance change.

rpcdaemon: new gas bailout handling

---

silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync.hpp
silkworm/db/snapshot_sync_test.cpp
silkworm/db/snapshots/snapshot_repository.cpp

download_and_index_snapshots was doing more than 2 things.
* move download_and_index_snapshots logic to setup() for clarity
* move logging to appropriate methods
* remove redundant logging

snapshots: refactor SnapshotSync::download_and_index_snapshots

---

.github/workflows/rpc-integration-tests.yml
.gitmodules
silkworm/core/execution/evm.cpp
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp
silkworm/rpc/core/evm_debug_test.cpp

Relevant changes:
- use customised tracing API from our evmone [fork](https://github.com/erigontech/evmone/tree/gas_cost_in_tracers)
- get the _internal_ gas cost from EVMONE for debug_trace* API

rpcdaemon: gas cost from EVMONE for debug family API

---

.github/workflows/rpc-fuzzer-tests.yml

Also, enable corpus merging to try and minimize its size, see: https://llvm.org/docs/LibFuzzer.html#corpus

test: switch fuzzer to single thread and increase its memory limit

---

cmd/silkworm.cpp
silkworm/capi/silkworm.cpp
silkworm/capi/silkworm_test.cpp
silkworm/db/db_utils_test.cpp
silkworm/db/mdbx/mdbx.cpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync.hpp
silkworm/db/test_util/test_database_context.cpp
silkworm/db/test_util/test_database_context.hpp
silkworm/node/stagedsync/execution_engine_test.cpp
silkworm/node/stagedsync/forks/fork.cpp
silkworm/rpc/commands/rpc_api_test.cpp
silkworm/rpc/test_util/api_test_database.hpp

Rename some variables to follow a convention that `db::open_env()` result is either `chaindata_env` or just `env`.
The majority of places already used this naming.
* SnapshotSync: pass env by value copy as in the other places (Node, Sync, Daemon)
* cmd/silkworm.cpp: get rid of `NOLINT(cppcoreguidelines-slicing)` by explicit casts

db: rename mdbx::env db to env

---

cmd/dev/db_toolbox.cpp
cmd/dev/snapshots.cpp
silkworm/core/state/in_memory_state.cpp
silkworm/core/types/block.hpp
silkworm/db/buffer.cpp

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es63-dont-slice

lint: fix cppcoreguidelines-slicing in snapshots cmd

---

cmd/common/snapshot_options.cpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync_test.cpp
silkworm/db/snapshots/bittorrent/client.cpp
silkworm/db/snapshots/bittorrent/client.hpp
silkworm/db/snapshots/bittorrent/client_test.cpp
silkworm/db/snapshots/bittorrent/settings.hpp
silkworm/db/snapshots/snapshot_settings.hpp

* schedule verification in SnapshotSync::setup after all torrents are seeded
* move verify_on_startup flag
* remove related tests that did nothing

snapshots: fix torrent.verify_on_startup

---

silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp

Review and cleanup of DebugTracer class

rpcdaemon: DebugTracer code refactoring and cleanup

---

cmd/dev/db_toolbox.cpp

Adding `deep` option to `compare` subcommand allowing for content comparison (in addition to failed schema check when deep comparison was launched by default).

Add option to do table deep check with db_toolbox

---

silkworm/node/execution/active_direct_service_test.cpp
silkworm/node/stagedsync/stages/stage_senders.cpp
silkworm/node/stagedsync/stages/stage_senders.hpp
silkworm/node/stagedsync/stages_test.cpp

Fixes #2349 
*Extra*
Remove gMock warnings about "uninteresting calls" when executing `silkworm_node_test`

node: fix revision check for tx type in stage Senders

---

silkworm/node/stagedsync/stages/stage_execution.cpp
silkworm/node/stagedsync/stages_test.cpp

Fixes #2359
This PR restores in stage Execution the invalid block handling logic removed in #1511
Also fixes the invalid block reference lifetime issue causing an incorrect block hash to be stored as bad block hash in `SyncContext` and displayed into the warning log, as described in #2358

node: fix Execution stage unwind after invalid block

---

silkworm/core/execution/evm.cpp
silkworm/core/execution/evm.hpp
silkworm/rpc/core/evm_executor.cpp

Gas deduction and gas+funds validation are now part of evm (core).

core, rpcdaemon: move gas+funds bailout mechanism into evm

---

cmd/dev/backend_kv_server.cpp
cmd/dev/db_toolbox.cpp
silkworm/capi/fork_validator.cpp
silkworm/node/common/node_settings.hpp
silkworm/node/execution/active_direct_service_test.cpp
silkworm/node/execution/direct_service_test.cpp
silkworm/node/execution/header_chain_plus_exec_test.cpp
silkworm/node/node.cpp
silkworm/node/stagedsync/execution_engine.cpp
silkworm/node/stagedsync/execution_engine.hpp
silkworm/node/stagedsync/execution_engine_test.cpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/execution_pipeline.hpp
silkworm/node/stagedsync/forks/extending_fork.cpp
silkworm/node/stagedsync/forks/extending_fork.hpp
silkworm/node/stagedsync/forks/fork.cpp
silkworm/node/stagedsync/forks/fork.hpp
silkworm/node/stagedsync/forks/fork_test.cpp
silkworm/node/stagedsync/forks/main_chain.cpp
silkworm/node/stagedsync/forks/main_chain.hpp
silkworm/node/stagedsync/forks/main_chain_test.cpp
silkworm/node/stagedsync/timer_factory.hpp
silkworm/node/test_util/mock_execution_engine.hpp

* pass TimerFactory instead of using NodeSettings.asio_context in ExecutionPipeline
* pass asio::any_io_executor via constructor instead of using io_context
* C API `silkworm_start_fork_validator`: previously it was passing a dead NodeSettings.asio_context, now ExecutionEngine can manage an internal executor via a private context pool
* extra: rename `start_*` to `run_*` in NodeImpl

node: refactor NodeSettings.asio_context

---

.github/workflows/rpc-integration-tests.yml
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace.hpp

Fix for gas cost in trace_replay* API

rpcdaemon: gas cost in trace_replay* API

---

cmd/sentry.cpp
cmd/silkworm.cpp
silkworm/infra/common/application_info.cpp
silkworm/infra/common/application_info.hpp
silkworm/sentry/sentry.cpp
silkworm/sentry/sentry.hpp

The logic is close to get_node_name_from_build_info

sentry: move make_client_id to ApplicationInfo

---

cmd/common/node_options.cpp
silkworm/node/common/node_settings.hpp
silkworm/node/node.cpp
silkworm/node/settings.hpp

Add an option to control if execution API GRPC server is running. It is disabled by default and chain sync uses an internal execution service with a direct client connection. When enabled, a GRPC server starts, and chain sync must be run as a separate process and connect to it. Note: internal execution service runs in both cases.

node: exec_api_address setting

---

silkworm/capi/silkworm_test.cpp

This PR skips some unit tests in C API to restore build on macOS, see #2389

capi: skip some unit tests in macOS after PR 2308

---

cmd/common/rpcdaemon_options.cpp
silkworm/db/state/version.cpp
silkworm/db/state/version.hpp
silkworm/rpc/daemon.cpp
silkworm/rpc/daemon.hpp
silkworm/rpc/settings.hpp

This PR introduces a new command-line flag `--erigon3` in standalone `rpcdaemon` to indicate that Erigon3 data storage is expected.
The existing automatic mechanism of retrieving the data storage version from Erigon database has been removed because dealing with corner cases (e.g. timeout, periodic retries in case of shutdown and restart...) seems too much effort.
*Extras*
rename other two command-line options for naming coherency

db, rpcdaemon: flag to support E3 data storage

---

.github/workflows/rpc-integration-tests.yml
silkworm/rpc/common/util.cpp
silkworm/rpc/common/util.hpp
silkworm/rpc/common/util_test.cpp
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp
silkworm/rpc/core/evm_debug_test.cpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace.hpp

Updated evmone commit and fix for undefined opcode gas cost

rpcdaemon: undefined opcode gas cost

---

.github/workflows/rpc-fuzzer-tests.yml

Enabling the merge corpus option did not bring the expected benefits. Moreover, since enabling it, the fuzzer terminates early and reports a successful return code. 
This PR disables it and let us investigate it further.

tests: disable merge corpus option for fuzzer

---

cmd/dev/check_changes.cpp
cmd/dev/scan_txs.cpp
cmd/test/ethereum.cpp
silkworm/capi/silkworm.cpp
silkworm/core/execution/call_tracer.cpp
silkworm/core/execution/evm.cpp
silkworm/core/execution/evm.hpp
silkworm/core/protocol/blockchain.cpp
silkworm/core/protocol/blockchain.hpp
silkworm/node/execution/block/block_executor.cpp
silkworm/node/execution/block/block_executor.hpp
silkworm/node/stagedsync/stages/stage_execution.cpp
silkworm/node/stagedsync/stages/stage_execution.hpp
silkworm/rpc/core/evm_executor.cpp
silkworm/rpc/core/evm_executor.hpp

Upgrade evmone to version [0.13.0](https://github.com/ethereum/evmone/releases/tag/v0.13.0) by rebasing erigontech's fork of it: https://github.com/erigontech/evmone/tree/rebase_to_v0.13.
Upgrade intx to version [0.12.0](https://github.com/chfast/intx/releases/tag/v0.12.0).
The new version of evmone manages `ExecutionState` internally and
removes it from public API. This makes object pools for
`ExecutionState`s in Silkworm unnecessary.

evmone: upgrade to version 0.13.0

---

cmd/dev/grpc_toolbox.cpp
silkworm/db/kv/api/endpoint/paginated_sequence.hpp
silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
silkworm/db/kv/grpc/client/remote_transaction_test.cpp

Add support for intersection/union set operations on E3 Data API paginated iterators and change the paginated iterator API exposing `has_next`/`next` stream-like methods, notably:
```c++
PaginatedUint64& paginated = ...;
auto it = co_await paginated.begin();
while (const auto value = co_await it.next()) {
// use *value;
}
```
Furthermore, conceptualise and improve `PaginatedIterator` abstraction and increase test coverage.
*Extra*
- cleanup `RemoteTransactionTest`

db: set operations on paginated Data API iterators

---

cmd/capi/execute.cpp
cmd/dev/check_changes.cpp
cmd/dev/db_toolbox.cpp
cmd/dev/snapshots.cpp
silkworm/capi/silkworm.cpp
silkworm/db/datastore/snapshot_merger.cpp
silkworm/db/datastore/snapshot_merger.hpp
silkworm/db/datastore/snapshots/common/step.hpp
silkworm/db/datastore/snapshots/common/timestamp.hpp
silkworm/db/datastore/snapshots/snapshot_bundle.hpp
silkworm/db/datastore/snapshots/snapshot_bundle_factory.hpp
silkworm/db/datastore/snapshots/snapshot_repository.cpp
silkworm/db/datastore/snapshots/snapshot_repository.hpp
silkworm/db/freezer.cpp
silkworm/db/snapshot_benchmark.cpp
silkworm/db/snapshot_bundle_factory_impl.cpp
silkworm/db/snapshot_bundle_factory_impl.hpp
silkworm/db/snapshot_repository_test.cpp
silkworm/db/snapshot_sync.cpp
silkworm/db/snapshot_sync.hpp
silkworm/db/snapshot_sync_test.cpp
silkworm/db/test_util/make_repository.cpp
silkworm/db/test_util/make_repository.hpp
silkworm/rpc/daemon.cpp

* define a Timestamp type and conversions to/from Step-s (currently it is a separate type in snapshots/common, later on we can consider migrating kv/api to this type)
* Repository can be created with either BlockNum converter or TxnId converter (it will be used later for state snapshots repository). Repository now uses steps internally, and uses a timestamp converter to implement find_segment and max_timestamp_available
* SnapshotBundle requires an explicit step range on construction. Bundle factory is modified to use steps
* SnapshotBundle.block_range() is removed. freezer, merger currently still do conversions to block numbers themselves, in the future they should be also refactored to work with steps

snapshots: timestamp-based repository

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/run_integration_tests.sh
silkworm/db/chain/chain.cpp
silkworm/db/chain/chain.hpp
silkworm/db/chain/chain_test.cpp
silkworm/db/chain/remote_chain_storage.cpp
silkworm/db/chain/remote_chain_storage_test.cpp
silkworm/db/kv/txn_num.cpp
silkworm/rpc/commands/engine_api_test.cpp
silkworm/rpc/core/evm_debug_test.cpp
silkworm/rpc/core/evm_trace_test.cpp
silkworm/rpc/test_util/dummy_database.hpp
silkworm/rpc/test_util/dummy_transaction.hpp

This is necessary when using Erigon3 version greater than v3.0.0-alpha2, because `CanonicalHeader` table gets pruned as well.

rpcdaemon: use ETHBACKEND.canonical_block_hash_from_number

---

.github/actions/fuzzer-common-steps/action.yml
cmake/compiler_settings.cmake

This applies to the Erigon 2 runner only - Erigon 3 runner has already been cleaned up

tests: remove leftovers from the previous runs in conan cache

---

.circleci/config.yml
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/execution_pipeline.hpp

* use string_view for keys to avoid stage not found if the name char* pointers are unstable across .cpp files
* avoid double logging of exceptions
* pass current_stage_name explicitly to avoid a crash when current_stage_ = end
* add missing kTriggersStageKey to the order lists

execution: fix stages lookup in sanitizer builds

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/run_integration_tests.sh
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp

Change in response error field for debug_traceTransaction API in E3

rpcdaemon: debug_traceTransaction error field

---

.github/workflows/run_integration_tests.sh
silkworm/db/tables.hpp
silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/commands/ots_api.cpp

Moved ots_getTransactionBySenderAndNonce  on new KV APIs
*Extras*
fix clang tidy after #2465

rpcdaemon: ots_getTransactionBySenderAndNonce for e3

---

silkworm/sync/block_exchange.cpp
silkworm/sync/internals/body_sequence.cpp
silkworm/sync/internals/header_chain.cpp
silkworm/sync/internals/random_number.hpp
silkworm/sync/messages/inbound_new_block.cpp
silkworm/sync/messages/inbound_new_block_hashes.cpp

We discourage the use of singletons and global variables in general.
For now use a global variable within sync.

sync: remove singleton from core

---

silkworm/capi/silkworm_test.cpp
silkworm/db/kv/api/local_cursor_test.cpp
silkworm/db/test_util/test_database_context.cpp
silkworm/db/test_util/test_database_context.hpp
silkworm/node/stagedsync/stages_test.cpp
silkworm/rpc/commands/rpc_api_test.cpp

This is a consistency refactoring so that each test manages its own TemporaryDirectory. TemporaryDirectory manages its cleanup.

db: always pass TemporaryDirectory to TestDatabaseContext

---

silkworm/db/kv/api/endpoint/paginated_sequence.hpp
silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/grpc/client/remote_transaction.cpp
silkworm/db/kv/grpc/client/remote_transaction.hpp
silkworm/rpc/test_util/dummy_transaction.hpp

Fix `page_token` management in Range queries: add `page_token` parameter to `PaginatedSequence::Paginator` and `PaginatedSequence::PageResult`.

rpcdaemon: page_token management in Data API Range ops

---

silkworm/rpc/commands/ots_api.cpp

Added check on transaction nonce

rpcdaemon: check transaction nonce in ots_getTransactionBySenderAndNonce

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/run_integration_tests.sh

Moved to integration tests v1.12 skipping debug_traceBlockByNumber not working ones

integration: update rpc-tests to v1.12.0

---

.github/workflows/run_integration_tests.sh
.github/workflows/start_integration_rpcdaemon.sh
.github/workflows/stop_integration_rpcdaemon.sh
cmake/parallel_jobs_count.sh
cmake/run_smoke_tests.sh
cmake/run_unit_tests.sh
cmake/setup/compiler_install.sh
silkworm/core/chain/config_test.cpp
tests/docker/run-docker.sh
tests/perf/run_with_perf.sh
tests/perf/run_with_toplev.sh
tests/perf/vegeta_attack_getLogs_rpcdaemon.sh
tests/perf/vegeta_attack_getLogs_silkrpc.sh
tools/lint/log_macros_fix.sh

run_unit_tests.sh was always succeeding after adding a grep after cmake (see https://github.com/erigontech/silkworm/pull/2501 ), because the full `cmake | grep` pipe was always succeeding even if cmake fails. `set -o pipefail` fixes this.
Add `set -e && set -o pipefail` in all bash scripts for safety.

ci: fix unit test failure propagation

---

silkworm/db/test_util/mock_chain_storage.hpp
silkworm/sync/block_exchange.hpp
silkworm/sync/chain_sync.cpp
silkworm/sync/chain_sync.hpp
silkworm/sync/sync_pos.cpp
silkworm/sync/sync_pos.hpp
silkworm/sync/sync_pos_test.cpp
silkworm/sync/sync_pow.cpp
silkworm/sync/sync_pow.hpp
silkworm/sync/test_util/mock_block_exchange.hpp

Inherit both MockBlockExchange and BlockExchange from a common interface to avoid creating BlockExchange dependencies that are irrelevant for the test (sentry, data store).

sync: refactor MockBlockExchange for PoSSyncTest

---

silkworm/db/blocks/blocks_index_builders_factory.cpp
silkworm/db/blocks/schema_config.hpp
silkworm/db/datastore/snapshot_merger.cpp
silkworm/db/datastore/snapshots/schema.cpp
silkworm/db/datastore/snapshots/schema.hpp
silkworm/db/datastore/snapshots/segment/segment_reader.cpp
silkworm/db/datastore/snapshots/segment/segment_reader.hpp
silkworm/db/datastore/snapshots/segment/segment_writer.cpp
silkworm/db/datastore/snapshots/segment/segment_writer.hpp
silkworm/db/datastore/snapshots/snapshot_bundle.cpp
silkworm/db/datastore/snapshots/snapshot_bundle.hpp
silkworm/db/datastore/snapshots/snapshot_repository.cpp
silkworm/db/datastore/snapshots/snapshot_repository.hpp
silkworm/db/state/schema_config.cpp
silkworm/db/state/schema_config.hpp

* .kvei and .bt schema (only schema for now, TODOs added for opening files)
* configure KVSegment compression kind: uncompressed by default, Storage & Commitment .kv has keys compressed, Code .kv has values compressed (.ef is always uncompressed)
* configure Segment compression: history is uncompressed by default, compressed for Code .v
* disable Commitment history

snapshots: more state schema configurations

---

cmake/run_unit_tests.sh
cmd/dev/grpc_toolbox.cpp
silkworm/db/kv/api/endpoint/temporal_point.hpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/api/local_transaction.hpp
silkworm/db/kv/api/transaction.hpp
silkworm/db/kv/grpc/client/endpoint/temporal_point.cpp
silkworm/db/kv/grpc/client/endpoint/temporal_point.hpp
silkworm/db/kv/grpc/client/endpoint/temporal_point_test.cpp
silkworm/db/kv/grpc/client/remote_transaction.cpp
silkworm/db/kv/grpc/client/remote_transaction.hpp
silkworm/db/kv/grpc/client/remote_transaction_test.cpp
silkworm/db/kv/grpc/test_util/sample_protos.hpp
silkworm/db/state/remote_state_test.cpp
silkworm/db/state/state_reader.cpp
silkworm/db/state/state_reader_test.cpp
silkworm/db/test_util/mock_transaction.hpp
silkworm/rpc/commands/debug_api.cpp
silkworm/rpc/commands/debug_api_test.cpp
silkworm/rpc/core/account_dumper_test.cpp
silkworm/rpc/core/account_walker_test.cpp
silkworm/rpc/core/evm_debug_test.cpp
silkworm/rpc/core/evm_executor_test.cpp
silkworm/rpc/core/evm_trace_test.cpp
silkworm/rpc/core/storage_walker_test.cpp
silkworm/rpc/test_util/dummy_transaction.hpp

This PR splits `db::kv::api::Transaction::get_latest` (renamed as such in #2530, formerly known as `domain_get`) into two different methods both mapped into the same gRPC call `rpc GetLatest(GetLatestReq) returns (GetLatestReply);` in `kv.proto`:
- `get_latest`: corresponds to `GetLatest` with latest=true, i.e. timestamp `ts` ignored
- `get_as_of`: corresponds to `GetLatest` with latest=false, i.e. timestamp `ts` used
This refactoring matches the way E3 captures the different semantics internally.
It would be cleaner to split the responsibilities also at the gRPC interface level e.g. having both `GetLatest` and `GetAsOf` also there or alternatively rename `GetLatest` as `Get`.

db: split internal TKV get_latest method to match e3

---

silkworm/core/protocol/validation.cpp
silkworm/core/protocol/validation.hpp
silkworm/core/protocol/validation_test.cpp
silkworm/rpc/core/evm_executor_test.cpp

This is an attempt to merge common code paths for both `pre_validate_transaction` and `call_pre_check`.

core: unify transaction validation for execution and simulate paths

---

silkworm/db/datastore/snapshots/btree/btree_index.cpp
silkworm/db/datastore/snapshots/elias_fano/elias_fano.hpp
silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder.hpp
silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder_test.cpp
silkworm/db/datastore/snapshots/history.hpp
silkworm/db/datastore/snapshots/history_accessor_index.hpp
silkworm/db/state/accounts_domain.hpp
silkworm/db/state/address_decoder.hpp
silkworm/db/state/address_decoder_test.cpp
silkworm/db/state/code_domain.hpp
silkworm/db/state/commitment_domain.hpp
silkworm/db/state/hash_decoder.hpp
silkworm/db/state/hash_decoder_test.cpp
silkworm/db/state/log_address_inverted_index.hpp
silkworm/db/state/log_topics_inverted_index.hpp
silkworm/db/state/receipts_domain.hpp
silkworm/db/state/receipts_domain_test.cpp
silkworm/db/state/storage_domain.hpp
silkworm/db/state/storage_domain_test.cpp
silkworm/db/state/traces_from_inverted_index.hpp
silkworm/db/state/traces_to_inverted_index.hpp

* generic decoder for reading II .ef values
* generic encoder for doing lookups on history .vi keys
* entity-specific decoders for reading domains and IIs

snapshots: state snapshot files decoders

---

silkworm/core/execution/evm.cpp
silkworm/core/execution/evm.hpp

Move the implementation of the get_block_hash() from EvmHost to EVM where it is cached. This is in preparation for evmone APIv2 where this method is used.

core: move get_block_hash() from EvmHost to EVM

---

silkworm/core/execution/evm.cpp
silkworm/core/execution/evm.hpp

Use the owned pointer to VM type from EVMC to manage the evmone's VM. This also prepares for evmone APIv2 usage where the `evmc::VM&` is needed.

core: use evmc::VM to own evmone's VM

---

silkworm/core/common/test_util.hpp

The recent changes adding Prague network config for tests accidentally enabled Prague in the Cancun config.

test: fix Prague/Cancun test config

---

silkworm/core/execution/processor.cpp

Refactor the computation of the execution gas limit for a transaction. This small change helps with evmone APIv2 integration.

evm: refactor computation of execution gas limit

---

cmd/test/ethereum.cpp
silkworm/core/execution/processor.cpp
silkworm/core/execution/processor.hpp
silkworm/core/state/intra_block_state.hpp
third_party/evmone/CMakeLists.txt

This is the part of the full replacement of the evmone API proposed in #2480.
Here we translate structures representing blocks/transactions and implement required interfaces (StateView and BlockHashes). Transactions are also executed in evmone APIv2 but effects of the execution (StateDiff) are not applied to the state. The state transitions are still handled by Silkworm in the old way (IntraBlockState + evmone/EVMC).
The results of both executions are compared against each other to verify the evmone APIv2 works correctly.
In summary, we execute every transaction twice, but this allows us to verify the correctness of the new API and its integration. Moreover, the unit tests and RPC are unaffected by the change. We plan to incrementally move the EVM execution to the new API.

Use evmone APIv2 on the side

---

.github/workflows/rpc-integration-tests.yml
silkworm/db/kv/state_reader.cpp
silkworm/db/kv/state_reader.hpp
silkworm/execution/local_state.cpp
silkworm/execution/local_state.hpp
silkworm/execution/remote_state.hpp
silkworm/execution/remote_state_test.cpp
silkworm/execution/state_factory.cpp
silkworm/execution/state_factory.hpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace_test.cpp

This PR introduces:
- state management on TxnId for `TraceCallExecutor`
- update API `trace_replay_transaction`
- update API `trace_get`
- update API `trace_transaction`
This PR is connected to: https://github.com/erigontech/rpc-tests/pull/304

rpcdaemon: use transaction-level state in trace API

---

silkworm/rpc/commands/ots_api.cpp
silkworm/rpc/core/evm_trace.cpp

This PR implements state on TxnId for the following API:
-  `ots_trace_transaction`
- `ots_getTransactionError`
- `ots_getInternalOperations`
Fixes random crash on `ots_hasCode`

rpcdaemon: use transaction-level state in ots API 

---

silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug_test.cpp

This PR introduces transaction-level state for the following API:
- `debug_trace_transaction`
- `debug_traceCall`
- `debug_traceCallMany`

rpcdaemon: use transaction-level state in debug API

---

cmd/test/ethereum.cpp

Now with evmone APIv2 execution even more stack space is needed for Debug+Asan builds.
evmone will try to optimize this aspect later.

test: increase stack size for cmd/test/ethereum

---

silkworm/core/protocol/merge_rule_set.cpp
silkworm/core/protocol/validation.cpp

Destruct empty accounts created during interaction with system accounts, requests or operations. This leaves the intra block state in sanity.
This helps to partially switch to EVM execution via evmone APIv2.

evm: clean up empty accounts after system contracts

---

silkworm/core/execution/processor.cpp

evmone execution via APIv2 provides enough information (including logs) to fully build a transaction receipt. Use it before Silkworm execution. This also modifies some asserts and drops Silkworm's logs' vector allocation optimization.

evm: create txn receipt using results from evmone APIv2

---

cmake/compiler_settings.cmake
cmd/capi/CMakeLists.txt
silkworm/capi/CMakeLists.txt
silkworm/capi/fork_validator.cpp
silkworm/capi/instance.hpp
silkworm/capi/rpcdaemon.cpp
silkworm/capi/silkworm.cpp
silkworm/capi/silkworm_test.cpp

Problem:
Linking silkworm_node.lib to both silkworm_capi.dll and silkworm_capi_test.exe produces 2 sets of global data (identical symbols),
which is a conflict according to ASAN ODR:
https://github.com/google/sanitizers/wiki/AddressSanitizerOneDefinitionRuleViolation
Solution:
Build silkworm_capi_static.lib separately, and use it with silkworm_capi_static_test.exe and capi/execute.exe so
that the linker can resolve duplicate symbols.
fixes https://github.com/erigontech/silkworm/issues/1881

capi: fix capi_test with ASAN (#1881)

---

silkworm/core/execution/execution_test.cpp
silkworm/core/execution/processor.cpp
silkworm/core/execution/processor_test.cpp
silkworm/core/state/intra_block_state.hpp

Implement handling of evmone's StateDiff and apply it to the IntraBlockState after each transaction
if evmone APIv2 is abled in ExecutionProcessor.
Also enable evmone APIv2 in direct unit tests for ExecutionProcessor.

evm: apply state diff from evmone APIv2 if enabled

---

cmd/dev/check_changes.cpp
cmd/dev/scan_txs.cpp
cmd/state-transition/state_transition.cpp
silkworm/core/execution/execution.hpp
silkworm/db/test_util/test_database_context.cpp

Enable evmone APIv2 by the flag in the ExecutionProcessor in:
- cmd/dev/check_changes
- cmd/dev/scan_tx
- cmd/state_transition
- db unit tests
- execution unit tests via `execute_block()`

evm: enable evmone APIv2 in tool/test utils

---

cmake/run_unit_tests.cmake
cmake/run_unit_tests.sh
tsan_suppressions.txt

After #1881 re-enabled C-API unit tests, we're experiencing intermittent failures related to MDBX in TSAN build, e.g. [here](https://app.circleci.com/pipelines/github/erigontech/silkworm/14921/workflows/c5f9e071-66e6-4862-853a-dabcd0e4b7d9/jobs/65928).
The root cause is that MDBX is [not compatible with Thread Sanitiser](https://github.com/erigontech/mdbx-go/blob/839cb7b1a9a5e6f8cff751ec1b25814d24a7ab38/mdbxdist/mdbx.c#L861), so we must suppress MDBX data races for unit tests in TSAN build.

cmake: TSAN suppression for MDBX false-positives in unit tests

---

silkworm/db/kv/api/local_transaction.cpp
silkworm/execution/state_factory.cpp
silkworm/execution/state_factory.hpp
silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/commands/eth_api_test.cpp
silkworm/rpc/commands/rpc_api_test.cpp
silkworm/rpc/core/call_many.cpp
silkworm/rpc/core/call_many.hpp
silkworm/rpc/core/estimate_gas_oracle.cpp
silkworm/rpc/core/estimate_gas_oracle.hpp
silkworm/rpc/core/estimate_gas_oracle_test.cpp
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_executor.cpp
silkworm/rpc/core/evm_executor.hpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace_test.cpp
silkworm/rpc/core/receipts.cpp

This PR contains:
- removed StateFactory::create_state_txn()
- modified StateFactory::create_state() uses txn_id as input no more block_num
- StateFactory::user_txn_id_at() new method that return txn_id from block_num and txn_index
- modify APIs using new StateFactory interface

rpcdaemon: StateFactory rework

---

silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/stages/stage_headers.cpp
silkworm/node/stagedsync/stages/stage_interhashes.cpp
silkworm/node/stagedsync/stages/stage_interhashes.hpp

Fixes #2597 by replacing incremental mode with full-regeneration mode also for small block intervals.
This is the output of the `staged_pipeline debug_unwind` command:
```
INFO [12-13|23:37:26.132 UTC] Debug unwind datadir: ~/silkworm
INFO [12-13|23:37:32.558 UTC] Reopen snapshot repository folder: ~/silkworm/snapshots
INFO [12-13|23:37:34.978 UTC] Total reopened bundles: 72 max block available: 20'474'999
INFO [12-13|23:37:34.978 UTC] Debug unwind: forward to=1'000'000 START
INFO [12-13|23:37:34.978 UTC] ExecutionPipeline                        Forward start
INFO [12-13|23:37:34.978 UTC] [5/13 Execution]                         op=kForward from=0 to=1000000 span=1000000 
INFO [12-13|23:38:04.979 UTC] [5/13 Execution]                         block=808598 blocks/s=26953 txns/s=37097 …
```

node: replace incremental with full mode in InterHashes stage

---

cmd/dev/staged_pipeline.cpp
silkworm/node/stagedsync/stages/stage_blockhashes.cpp

Fixes #2593 
Note: the off-by-one error in reached block number reported back by BlockHashes only happens if the target block does _not_ correspond to the highest saved block (hence, more blocks exist in the canonical chain after the target one).
*Extras*
- improve error logs
- avoid CLion warning
- add missing `STOP_AT_BLOCK` set in `forward` subcommand of `staged_pipeline`

node: fix reached block num in BlockHashes for existing blocks

---

docs/db_toolbox.md

This copies the only page in https://github.com/erigontech/silkworm/wiki into the https://github.com/erigontech/silkworm/tree/master/docs .
I suggest to keep using /docs as a primary source of public docs and disable the GH wiki.

docs: copy db_toolbox doc from GH wiki

---

.github/workflows/rpc-integration-tests.yml
silkworm/core/common/util.hpp
silkworm/rpc/commands/erigon_api.cpp
silkworm/rpc/core/block_reader.cpp
silkworm/rpc/core/block_reader_test.cpp
silkworm/rpc/core/logs_walker.cpp
silkworm/rpc/types/filter.hpp

Moved erigon_getLatestLogs on new KV APIs

rpcdaemon: erigon_getLatestLogs for e3

---

silkworm/node/stagedsync/stages/stage_triggers.cpp
silkworm/node/stagedsync/stages/stage_triggers.hpp
silkworm/node/stagedsync/stages/stage_triggers_test.cpp

Fixes #2604 
The problem was hidden behind the lifecycle of the trigger task caller: its coroutine frame could be destroyed before being spawned.

node: fix task caller lifecycle in Triggers schedule

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/run_integration_tests.sh

Enable test 7 & 9 for debug_traceCallMany
Fixes #2050

rpcdaemon: enable debug_traceCallMany tests 

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/run_integration_tests.sh
silkworm/rpc/commands/debug_api.cpp

Add support for block number provided using tags in debug_traceBlockByNumber
Fixes #1802

rpcdaemon: debug_traceBlockByNumber support for block tags

---

silkworm/core/common/assert.hpp
silkworm/core/common/small_map.hpp
silkworm/core/protocol/bor/config.cpp

Address the following error when compling with gcc 14.2:
```
at /home/andrew/silkworm/silkworm/core/common/small_map.hpp:48:15,
inlined from ‘static std::optional<silkworm::protocol::bor::Config> silkworm::protocol::bor::Config::from_json(const nlohmann::json_abi_v3_11_3::json&)’ at /home/andrew/silkworm/silkworm/core/protocol/bor/config.cpp:71:50:
/usr/include/c++/14/bits/stl_pair.h:607:48: error: array subscript [15, 576460752303423485] is outside array bounds of ‘const silkworm::SmallMap<long unsigned int, long unsigned int> [1]’ [-Werror=array-bounds=]
607 |         second = std::forward<second_type>(__p.second);
|                                            ~~~~^~~~~~
/home/andrew/silkworm/silkworm/core/protocol/bor/config.cpp: In static member function ‘static …
```

core: address error=array-bounds in gcc14

---

silkworm/db/kv/state_reader_test.cpp
silkworm/execution/remote_state_test.cpp

`silkworm_db_test` and `silkworm_execution_test` show some expectation failures, e.g.
```
Actual function call count doesn't match EXPECT_CALL(transaction, first_txn_num_in_block(1'000'001))...
Expected: to be called once
Actual: never called - unsatisfied and active
```

rpcdaemon: remove useless Catch2 expectations

---

silkworm/node/stagedsync/stages/stage_execution.cpp
silkworm/node/stagedsync/stages/stage_hashstate.cpp
silkworm/node/stagedsync/stages/stage_interhashes.cpp

Properly handle `STOP_AT_BLOCK` environment variable in `Execution` stage even in case the previous stage (i.e. `Senders`) has already gone behind the `STOP_AT_BLOCK` value.
This is particularly handy when using the `staged_pipeline` subcommands which exploit `STOP_AT_BLOCK` in combination with `START_AT_STAGE` environment variable (e.g. `forward`, `debug_unwind`), thus possibly producing different progress values across the stages.
*Extras*
- use macro log facility in `Execution`, `HashState` and `InterHashes` stages

node: handle STOP_AT_BLOCK in Execution stage

---

silkworm/core/execution/processor.cpp
silkworm/core/protocol/validation.cpp
silkworm/core/protocol/validation.hpp
silkworm/rpc/core/evm_executor.cpp

The bailout option to validate_call_funds() makes it no-op function. Drop this option from the function so that the transaction validation code is not aware of the bailout semantic. Instead, ignore the validation result in the single place where it matters.

evm: drop bailout option from validate_call_funds()

---

silkworm/core/execution/processor.cpp
silkworm/core/execution/processor.hpp
silkworm/rpc/core/evm_executor.cpp

In the `ExecutionProcessor::call()` the bailout flag is passed by parameter but is also accessible as `evm().bailout`. It would be wrong if these flags are out of sync. Therefore, drop the bailout parameter and only use `evm().bailout` in the implementation.

evm: de-duplicate bailout flag

---

.circleci/config.yml

The conan.cmake file contains a lot of configuration for building conan dependencies, and should be added to the cache key for the same reasons as conanfile.py and conan profile.

CI: add conan.cmake to the cache killer key

---

.circleci/config.yml

Extra compilers find 2 types of problems:
1. "lint" - warnings, style, adherence to standard C++ etc. These type of problems are typically found more by the latest compiler versions. They are usually not critical and easy to fix, so can be postponed to the master integration workflow.
2. Usage of newer language and library features that are not available on old compiler versions. These type of problems are critical for GCC, because we make our releases (via silkworm-go) using the minimal GCC version. Such problems are not easy to fix as they might require reimplementing parts of the code without relying on the new features.
We shouldn't postpone critical and potentially hard work to the master integration workflow, therefore I suggest to use minimal compiler versions on the "light" PR …

CI - gcc 11 on PR workflow

---

silkworm/core/rlp/decode_test.cpp
silkworm/db/datastore/concat_view.hpp
silkworm/db/datastore/kvdb/inverted_index_range_by_key_query_test.cpp
silkworm/db/datastore/snapshots/bittorrent/torrent_file.cpp
silkworm/db/datastore/snapshots/elias_fano/list_iterator.hpp
silkworm/infra/concurrency/task_group_test.cpp
silkworm/infra/concurrency/timeout_test.cpp
silkworm/infra/grpc/server/server_context_pool.cpp
silkworm/interfaces/CMakeLists.txt
silkworm/rpc/commands/debug_api.cpp
silkworm/rpc/commands/erigon_api.cpp
silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/commands/ots_api.cpp
silkworm/rpc/commands/trace_api.cpp
silkworm/sentry/discovery/node_db/node_db_sqlite_test.cpp
silkworm/sentry/message_receiver.cpp
silkworm/sentry/rlpx/crypto/hmac.cpp

Fix the errors in Windows build after #2632:
- `kvdb/inverted_index_range_by_key_query_test.cpp`: explicit conversion from `std::filesystem::path` to `std::string`
- `snapshots/elias_fano/list_iterator.hpp`: `ListIterator::operator*` now returns `value_type` to fix MSVC conversion error. We could rename `ListIterator` as `ValueListIterator` to highlight it indeed iterates over primitive type values (i.e. integers)
plus other errors come to light after these:
- `local_transaction.cpp`, `concat_view_test.cpp`: add dual overloaded `operator==` and `operator!=` for `std::default_sentinel_t` in `ConcatView`
*Extras*
fix some MSVC warnings

ci: fix Windows build after PR 2632

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/run_integration_tests.sh
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp

Fixes #1652 supporting optional `txIndex` parameter in `debug_traceCall`

rpcdaemon: debug_traceCall with txIndex

---

.clang-tidy
silkworm/db/cli/snapshots.cpp
silkworm/db/datastore/kvdb/cursor_iterator.hpp
silkworm/db/datastore/kvdb/domain_delete_query.hpp
silkworm/db/datastore/kvdb/domain_put_latest_query.hpp
silkworm/db/datastore/kvdb/domain_put_latest_query_test.cpp
silkworm/db/datastore/kvdb/domain_put_query.hpp
silkworm/db/datastore/kvdb/inverted_index_range_by_key_query_test.cpp
silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.cpp
silkworm/db/datastore/snapshots/inverted_index_range_by_key_query.hpp
silkworm/db/state/account_codecs.hpp
silkworm/db/state/accounts_domain.hpp
silkworm/db/state/code_domain.hpp
silkworm/db/state/commitment_domain.hpp
silkworm/db/state/receipts_domain.hpp
silkworm/db/state/storage_domain.hpp
silkworm/execution/local_state.cpp

improve DomainGetLatestQuery wrappers - bind a fixed domain name to each query.
DomainPutLatestQuery fix and unit test.
DomainPutQuery - use current_step
disable CheckTriviallyCopyableMove to reduce false positives

datastore: improve domain get and put queries

---

.github/workflows/rpc-integration-tests.yml
silkworm/db/kv/grpc/client/endpoint/temporal_point.cpp
silkworm/db/kv/state_reader.cpp
silkworm/execution/local_state.cpp
silkworm/execution/local_state.hpp
silkworm/execution/remote_state.hpp
silkworm/execution/state_factory.cpp
silkworm/execution/state_factory.hpp
silkworm/rpc/commands/debug_api.cpp
silkworm/rpc/commands/eth_api.cpp
silkworm/rpc/commands/parity_api.cpp
silkworm/rpc/commands/trace_api.cpp
silkworm/rpc/core/block_reader.cpp
silkworm/rpc/core/block_reader.hpp
silkworm/rpc/core/call_many.cpp
silkworm/rpc/core/call_many.hpp
silkworm/rpc/core/estimate_gas_oracle.cpp
silkworm/rpc/core/estimate_gas_oracle.hpp
silkworm/rpc/core/estimate_gas_oracle_test.cpp
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_debug.hpp
silkworm/rpc/core/evm_executor.cpp
silkworm/rpc/core/evm_executor.hpp
silkworm/rpc/core/evm_trace.cpp
silkworm/rpc/core/evm_trace.hpp

Updated API to manage query on latest Block:
- `eth_getBalance` + integration_test
- `eth_getTransactionCount` + integration_test
- `eth_getCode` + integration_test*
- `eth getStorageAt` + integration_test
- `eth_call` + integration_test*
- `eth_callBunlde` + integration_test
- `eth_createAccessList` + integration_test*
- `ots_hasCode` + integration_test*
- `parity_listStorageKeys` + integration_test
- `eth_callMany` + integration_test*
- `trace_call` + integration_test*
- `trace_callMany` 
- `debug_traceCall`  + integration_test*
- `debug_traceCallMany` + integration_test*
- `ots_getContractCreator` - always on latest
- `eth_estimateGas` - always on latest
- `trace_block`
- `trace_replayBlockTransaction`
This PR is associated to rpc-tests  https://github.com/erigontech/rpc-tests/pull/323

rpcdaemon: StateReader's txn_id must be nullopt in case of latest block

---

silkworm/execution/local_state.cpp
silkworm/execution/local_state.hpp

Both `LocalState` and `RemoteState` are implementations of the `State` interface aimed at providing support for call execution, i.e. transaction re-execution or simulation required by many RPC end-points.
As such, `LocalState` must use a read-only database transaction because:
1. it doesn't need any read-write support (no persistent change is produced)
2. can be instantiated multiple times concurrently to offer parallel call execution

execution: use read-only tx in LocalState

---

silkworm/core/types/eip_7685_requests.cpp
silkworm/core/types/eip_7685_requests_test.cpp

Intermediate hashes of empty requests shouldn't be used for computing final signature. See: https://github.com/ethereum/EIPs/pull/8989

Don't compute hashes of empty requests

---

silkworm/core/protocol/param.hpp

Updating contract addresses for pectra devnet 5.

Updating contract addresses

---

silkworm/core/execution/processor.cpp
silkworm/core/execution/processor_test.cpp

Fixes https://github.com/erigontech/silkworm/issues/2690.

evm: properly handle chain id in evmone APIv2

---

silkworm/core/execution/processor.hpp
silkworm/node/execution/block/block_executor.cpp

This include a evmone change where we make sure the tracer is invoked even for empty code.

evm: enable evmone APIv2 in block executor

---

cmd/capi/execute.cpp
silkworm/capi/fork_validator.cpp
silkworm/capi/instance.hpp
silkworm/capi/rpcdaemon.cpp
silkworm/capi/silkworm.cpp
silkworm/capi/silkworm.h
silkworm/capi/silkworm_test.cpp
silkworm/capi/snapshots.cpp
silkworm/db/data_store.cpp
silkworm/db/data_store.hpp
silkworm/db/datastore/domain_get_as_of_query.hpp
silkworm/db/datastore/snapshots/domain.hpp
silkworm/db/datastore/snapshots/history_get_query.hpp
silkworm/db/datastore/snapshots/schema.hpp
silkworm/db/datastore/snapshots/snapshot_bundle.cpp
silkworm/db/datastore/snapshots/snapshot_bundle.hpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/state/schema_config.cpp
silkworm/db/state/schema_config.hpp
silkworm/db/test_util/temp_snapshots.hpp
silkworm/execution/domain_state.hpp
silkworm/execution/domain_state_test.cpp
silkworm/execution/local_state.cpp
silkworm/execution/local_state.hpp

Split state repository into 2: latest and historical.
* "latest" contains Domains data
* "historical" contains II and History data
This fixes a problem of having unlimited frozen steps in domain snapshots. II and History snapshots are capped at 64 steps, but Domain can grow to 1024. When it happens, the snapshot bundles become not full (e.g. a domain file with 256 steps doesn't align to a history file with 64 steps).
DomainGetAsOfQuery now accepts both repositories and uses them accordingly. `optional<snapshots::History>` is removed from snapshots::Domain, because it is a separate entity. DomainState only uses the latest state repository.
refactorings:
* call composite structs "bundle" in the C API to reflect our terminology
* refactor snapshot addition methods to the same structure
* …

db: split latest and historical snapshots repos

---

silkworm/db/access_layer.cpp

datastore: canonical hash by number in snapshots

---

silkworm/db/datastore/snapshots/common/encoding/sequence.hpp

snapshots: extend max encoded integer sequence length

---

silkworm/rpc/daemon.cpp

rpcdaemon: raise file descriptor limit at startup

---

silkworm/db/datastore/snapshots/btree/btree.cpp

Current implementation works with Apple Clang, but is not guaranteed by the C++ standard: see Return Value section [std::basic_string::compare](https://en.cppreference.com/w/cpp/string/basic_string/compare)

db: fix std::basic_string::compare result in snapshot BTree

---

silkworm/rpc/core/call_many.cpp
silkworm/rpc/core/estimate_gas_oracle.cpp
silkworm/rpc/core/estimate_gas_oracle_test.cpp
silkworm/rpc/core/evm_debug.cpp
silkworm/rpc/core/evm_executor.cpp
silkworm/rpc/core/evm_executor.hpp
silkworm/rpc/core/evm_executor_test.cpp
silkworm/rpc/core/evm_trace.cpp

In ExecutionResult changed 
`std::optional<int64_t> error_code;`
in
`std::optional<evmc_status_code> status_code;`

rpcdaemon: refactoring for ExecutionResult::error_code

---

silkworm/db/datastore/common/ranges/merge_unique_many_view.hpp
silkworm/db/datastore/common/ranges/merge_unique_many_view_test.cpp
silkworm/db/datastore/domain_range_latest_query.hpp
silkworm/db/datastore/kvdb/domain_range_latest_query.hpp
silkworm/db/datastore/kvdb/history_range_query.hpp
silkworm/db/datastore/snapshots/domain_range_latest_query.hpp
silkworm/db/datastore/snapshots/history_range_query.hpp
silkworm/db/kv/api/local_transaction.cpp

* make sure transform predicate moves Bytes instead of copying
* apply caching after transform to avoid accidental double move
* fix DomainRangeLatestQuery to hold std::shared_ptr<SnapshotBundle> of affected bundles for the lifetime of the results range
* deduce merge_unique_many template args

datastore: reduce transform copies

---

silkworm/db/datastore/common/ranges/caching_view.hpp
silkworm/db/datastore/common/ranges/merge_many_view.hpp
silkworm/db/datastore/common/ranges/vector_from_range.hpp
silkworm/db/datastore/snapshots/history_range_in_period_query.hpp
silkworm/db/datastore/snapshots/segment/kv_segment_reader.hpp
silkworm/db/datastore/snapshots/segment/kv_segment_test.cpp
silkworm/db/datastore/snapshots/segment/segment_reader.hpp
silkworm/db/datastore/snapshots/segment/segment_test.cpp

* owning_view: support SegmentReader (make it movable)
* caching_view: move instead of assigning to support more cases
* merge_many: hold produced ranges, not only their iterators

datastore: fix debug_getModifiedAccountsBy regression

---

.github/workflows/rpc-integration-tests.yml
.github/workflows/run_integration_tests.sh

Re-enable skipped APIs after fix in #2771 
This PR is connected to https://github.com/erigontech/rpc-tests/pull/349

integration tests: update exception list after PR 2771

---

silkworm/db/state/address_codecs.hpp
silkworm/db/state/storage_codecs.cpp
silkworm/db/state/storage_codecs.hpp
silkworm/db/state/storage_codecs_benchmark.cpp

Optimize away 2,7% of time spent in encode_word() by avoiding copies using a binary-compatible StorageAddressAndLocation structure.

datastore: optimize StorageAddressAndLocation encoding

---

silkworm/db/data_store.cpp
silkworm/db/data_store.hpp
silkworm/db/datastore/common/CMakeLists.txt
silkworm/db/datastore/common/entity_name.hpp
silkworm/db/datastore/data_store.hpp
silkworm/db/datastore/kvdb/database.cpp
silkworm/db/datastore/kvdb/database.hpp
silkworm/db/datastore/kvdb/inverted_index_range_by_key_query_test.cpp
silkworm/db/datastore/kvdb/schema.hpp
silkworm/db/datastore/snapshots/common/util/iterator/map_values_view.hpp
silkworm/db/datastore/snapshots/schema.hpp
silkworm/db/datastore/snapshots/snapshot_bundle.cpp
silkworm/db/datastore/snapshots/snapshot_bundle.hpp
silkworm/db/datastore/snapshots/snapshot_repository.hpp
silkworm/db/datastore/snapshots/snapshot_repository_ro_access.hpp

Optimize entity lookup by EntityName taking 1-2% of time using a raw pointer comparison and hash strategy for EntityName, and using a absl::flat_hash_map instead of std::map.

datastore: speedup lookup by EntityName

---

.github/workflows/rpc-integration-tests.yml
docs/JSON-RPC-API.md
silkworm/db/kv/api/state_cache.cpp
silkworm/db/kv/api/state_cache.hpp
silkworm/db/test_util/mock_state_cache.hpp
silkworm/rpc/commands/erigon_api.cpp
silkworm/rpc/json/cache_validation_result.cpp
silkworm/rpc/json/cache_validation_result.hpp
silkworm/rpc/types/cache_validation_result.hpp

Closes #2072 
Depends on https://github.com/erigontech/rpc-tests/pull/356

rpcdaemon: implement erigon_cacheCheck

---

docs/code_style.md

Updates with decisions discussed and voted at the workshop meeting.
Andrew confirmed P25 changing to the SPDX short form Apache boilerplate (as in Linux kernel and evmone).

docs: code style updates

---

silkworm/core/types/eip_7685_requests.cpp
silkworm/core/types/eip_7685_requests_test.cpp

This is a late fix added to EIP - it has come out of the testing of one of the testnets.

EIP-6110 Deposit contract fix 

---

silkworm/db/blocks/schema_config.hpp
silkworm/db/datastore/common/entity_name.cpp
silkworm/db/datastore/common/entity_name.hpp
silkworm/db/datastore/kvdb/schema.hpp
silkworm/db/datastore/snapshots/history_range_by_keys_query.hpp
silkworm/db/datastore/snapshots/history_range_in_period_query.hpp
silkworm/db/datastore/snapshots/schema.hpp
silkworm/db/snapshot_repository_test.cpp
silkworm/db/state/schema_config.hpp

Problem:
ASAN makes constexpr string_view address unstable between translation units.
Solution:
Use Java String intern() approach to produce stable addresses.
Although it disallows constexpr usage it is more flexible
and supports EntityName reuse across multiple DLLs and runtimes.

datastore: ASAN-compatible EntityName

---

silkworm/rpc/core/receipts.cpp

While fetching receipt there was incorrect key used for querying cumulative gas.

rpcdaemon: fix key used while querying cumulative gas used for receipt

---

silkworm/capi/silkworm.cpp
silkworm/core/state/state.hpp
silkworm/db/state/receipts_domain.hpp
silkworm/execution/domain_state.cpp
silkworm/execution/domain_state.hpp

We store relevant pieces of receipt into db every time a txn is executed by silkworm.

capi: single individual txn receipts into database 

---

silkworm/capi/rpcdaemon.cpp
silkworm/db/chain/local_chain_storage.cpp
silkworm/db/chain/local_chain_storage.hpp
silkworm/db/kv/api/direct_service.cpp
silkworm/db/kv/api/direct_service.hpp
silkworm/db/kv/api/direct_service_test.cpp
silkworm/db/kv/api/local_transaction.cpp
silkworm/db/kv/api/local_transaction.hpp
silkworm/db/kv/state_changes_stream_test.cpp
silkworm/rpc/daemon.cpp
silkworm/rpc/daemon.hpp
silkworm/rpc/test_util/api_test_database.hpp
silkworm/sync/sync.cpp

It is possible to cache the ChainConfig structure after reading it from mdbx, because it is immutable after the node has started.
This optimization shaves off 0,6% of total time during stress_test_eth_call_20M.tar.

db: cache chain config in local kv::api

---

silkworm/capi/silkworm_test.cpp
silkworm/capi/snapshots.cpp
silkworm/db/blocks/schema_config.cpp
silkworm/db/cli/snapshots.cpp
silkworm/db/datastore/common/entity_name.hpp
silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.cpp
silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.hpp
silkworm/db/datastore/snapshots/common/cache.hpp
silkworm/db/datastore/snapshots/common/key_hasher.cpp
silkworm/db/datastore/snapshots/common/key_hasher.hpp
silkworm/db/datastore/snapshots/common/key_hasher_test.cpp
silkworm/db/datastore/snapshots/domain_cache.hpp
silkworm/db/datastore/snapshots/domain_get_latest_query.hpp
silkworm/db/datastore/snapshots/history_get_query.hpp
silkworm/db/datastore/snapshots/inverted_index_cache.hpp
silkworm/db/datastore/snapshots/inverted_index_find_by_key_segment_query.hpp
silkworm/db/datastore/snapshots/inverted_index_seek_query.hpp
silkworm/db/datastore/snapshots/snapshot_bundle.cpp
silkworm/db/datastore/snapshots/snapshot_repository.cpp
silkworm/db/datastore/snapshots/snapshot_repository.hpp
silkworm/db/datastore/snapshots/snapshot_repository_ro_access.hpp
silkworm/db/state/schema_config.cpp

- Introduce Domain LRU cache (one for each entity) used in `DomainGetLatestQuery `
- Introduce InvertedIndex LRU cache (one for each entity) used in `InvertedIndexSeekQuery`
- Introduce `exec_raw` in segment queries to avoid multiple key encoding
- Move `BloomFilterKeyHasher` and rename as `KeyHasher` for reuse in snapshot LRU caches
MacBookPro M1-Max 64GB RAM
- master: f22d3473dafbab954d8387914960c5d1074bfc47
```
% ./run_perf_tests.py -m 2 -p pattern/mainnet/stress_test_eth_getLogs_15M.tar -r 5 -t 1000:20 -y eth_getLogs
Performance Test started
[1. 1] daemon: executes test qps: 1000 time: 20 -> [R=100.00% max=1.68s]
[1. 2] daemon: executes test qps: 1000 time: 20 -> [R=100.00% max=1.058s]
[1. 3] daemon: executes test qps: 1000 time: 20 -> [R=100.00% max=1.032s]
[1. 4] daemon: executes …
```

db: add D/II LRU caches in snapshots

---

cmd/dev/staged_pipeline.cpp

Fixes #2830 by using capture by-reference for `chain_config` in `make_bodies_stage_factory`
*Extras*
- add support for custom `DataDirectory` in `forward`, `unwind`, `debug_unwind`
- use `std::ranges::find` instead of `std::find`
- using `const&` instead of `&` for `EnvConfig` where possible
- harmonise the usage of namespace `datastore`

cmd: fix ChainConfig lifetime in staged_pipeline dev tool

---

conanfile.py

The grpc conan recipe was updated on 2025-03-25 to revision 2b1ac43c5934cc4bcc326335166e8838, see the output of:
conan list 'grpc/1.67.1#*' -r=conancenter -f=compact
That update is broken on conancenter - it doesn't have any associated binary packages as [reported in this issue](https://github.com/conan-io/conan-center-index/issues/26959), see the output of:
conan list 'grpc/1.67.1#2b1ac43c5934cc4bcc326335166e8838:*' -r=conancenter -f=compact
Hardcode the previous recipe revision from 2025-02-24 that contains associated binary packages on conancenter:
conan list 'grpc/1.67.1#c214ddb4e04e8d9a44d3a100defc9706:*' -r=conancenter -f=compact

cmake: fix conan grpc binary download

---

silkworm/capi/silkworm.cpp

Store receipts in a temporary database upon completion of a transaction batch. Erigon can later retrieve and use them as needed.

capi: store transient receipts in mdbx

---

silkworm/node/cli/staged_pipeline.cpp
silkworm/node/stagedsync/execution_pipeline.cpp
silkworm/node/stagedsync/stages/stage_triggers.cpp
silkworm/node/stagedsync/stages/stage_triggers.hpp

Handle progress for stage Triggers according to the progress rules checked by execution pipeline. This guarantees that it works when doing multiple forward/unwind using `staged_pipeline` dev tool and also plays nicely with `STOP_AT_BLOCK` debug option.
*Extra*
- fix block removal in `unwind` command of `staged_pipeline` dev tool

node: handle stage Triggers progress

---

cmake/conan.cmake

ld: warning: object file (.../libutf8_validity.a[3](utf8_range.c.o)) was built for newer 'macOS' version (15.0) than being linked (14.0)
This is a pure C library, and "cxxflags" are not respected, need to pass "cflags".

cmake: fix protobuf macOS link warning in libutf8_validity

---

silkworm/capi/instance.hpp
silkworm/capi/silkworm.cpp
silkworm/core/state/state.hpp
silkworm/execution/domain_state.cpp
silkworm/execution/domain_state.hpp

This simplifies interface to `State` - we don't have to implement `insert_receipts()` anymore since these are properly populated every time a new transaction is executed.

capi: calculate receipts' properties after each txn
